### ISSUE TITLE
Update from 5.7.0 to 6.2.0 is breaking

### ISSUE THREAD

**Issue by nerdmed** [tinycreative/react-native-intercom#104]
Dear team this update is breaking my build. Why isn't there any changelog or update instructions for a major version? Do i need to relink the package? Do i need to update the framework or even remove it? Do i need to update the search paths or something? Here is a screen of the error.

<img width="1318" alt="bildschirmfoto 2017-06-15 um 17 34 01" src="https://user-images.githubusercontent.com/3820220/27189373-772b045a-51f1-11e7-988c-7e7fa9072ede.png">

**Comment by MattyK14** [comment]
Anything?

**Comment by nerdmed** [comment]
is this package even maintained?

**Comment by browniefed** [comment]
No, I don't use this but am in charge of "maintaining" it.
People submit patches, I merge, and publish.
