### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by nazarTrynko** [tinycreative/react-native-intercom#106]
I have error on android: "Something went wrong. Couldn't load your conversations". Console gives:
```
Intercom React Native Error TypeError: IntercomWrapper.registerForPush is not a function
    at IntercomClient.js:221
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at IntercomClient.js:220
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:98
    at Object.callTimer (JSTimersExecution.js:95)
    at Object.callImmediatesPass (JSTimersExecution.js:199)
    at Object.callImmediates (JSTimersExecution.js:214)
    at MessageQueue.js:222
    at guard (MessageQueue.js:46)
    at MessageQueue.__callImmediates (MessageQueue.js:222)
    at MessageQueue.js:109
    at guard (MessageQueue.js:46)
```

**Comment by nazarTrynko** [comment]
Resolved with user registering: Intercom.registerIdentifiedUser({ userId: 'bob' }); but still registerForPush is not a function

**Comment by and-0-1** [comment]
Im having the same issue even with Intercom.registerIdentifiedUser already in use. 
Android simulator works just fine but when installed on a device and trying to open the chat window i just get the "Something went wrong. Couldn't load your conversations" message.
Don't know what is wrong

**Comment by cauboy** [comment]
I've the same problem on Android
```
Intercom React Native Error TypeError: IntercomWrapper.registerForPush is not a function
    at IntercomClient.js:221
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at IntercomClient.js:220
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:262
    at _callTimer (JSTimers.js:143)
    at Object.callImmediatesPass (JSTimers.js:443)
```

On iOS everything works fine.

Having a look into the native code, `registerForPush` is defined within the iOS code but not within Android. Is it supposed to be like this?

Any other ideas what might be wrong?

__Update:__
I've the feeling that it is supposed to be like this. `registerForPush` is only needed for iOS, so you might want to put it in a if clause:
```javascript
if (Platform.OS === 'ios') {
   Intercom.registerForPush()
}
```

To make pushes work on Android I've had to call
```javascript
Intercom.sendTokenToIntercom(deviceToken)
```
After I registered my device for pushes and received the deviceToken.

**Comment by Hanzig** [comment]
Hi everyone! I'm having the same issue, and I'm not sure what's causing that. Below is my code:

`class HomeView extends PureComponent {

	static propTypes = {
		infoBoxType: PropTypes.string,
		navigation: PropTypes.shape({
			activeRouteName: PropTypes.string,
		}).isRequired,
	};

	componentDidMount() {
		Intercom.registerForPush();
		Intercom.addEventListener(Intercom.Notifications.UNREAD_COUNT, this._onUnreadChange);
		Intercom.displayMessageComposer();
	}

	componentWillUnmount() {
		Intercom.removeEventListener(
			Intercom.Notifications.UNREAD_COUNT, this._onUnreadChange);
	}

	componentWillMount() {
		Intercom.handlePushMessage();
	}

	_onUnreadChange = ({ count }) => {
		console.log(count);
	}

	render() {

		return (
                   <View />
		);
	}

}`
<img width="302" alt="screen shot 2017-11-16 at 08 36 14" src="https://user-images.githubusercontent.com/1893613/32877325-ac9abb9a-caa9-11e7-9995-422176dc9427.png">

I tried with `Intercom.registerIdentifiedUser({ userId: 'bob' });` as well, but no luck. I'm just wondering where should the register call be? Thanks a lot in advance!

**Comment by seankwalker** [comment]
~~@andoni0305, did you manage to find a solution? I'm having the same error when running on device.~~ EDIT: For me, the error was that I was using the same API key for iOS and Android, just changing `ios_sdk` to `android_sdk`... needless to say, that doesn't work 😛

**Comment by aharon-vish** [comment]
is there an answer to that issue?

**Comment by evanjmg** [comment]
@cauboy you sir are awesome!
