### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by asimolmez** [tinycreative/react-native-intercom#107]
When I linked `react-native-intercom` to my project, I am seeing these errors. I don't want change `build.gradle` file because it is not related to my project. Have you got suggestions?

```
/node_modules/react-native-intercom/android/build/intermediates/res/merged/release/values-v24/values-v24.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
```
```

Error:Execution failed for task ':react-native-intercom:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

I looked at related questions on StackOverflow and old issues but these did not fix my problem. FYI

**Comment by jpokrzyk** [comment]
I changed my `app/build.gradle` android sdks to the following to fix that
```gradle
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
```

**Comment by agrass** [comment]
@jpokrzyk It's ok to change compileSdkVersion just like this???  We suppose to use v23 with RN or no?

**Comment by jpokrzyk** [comment]
@agrass It works fine for me.

**Comment by agrass** [comment]
Great, you are using in production??? You already tested in different models of phones??

**Comment by jpokrzyk** [comment]
Yea it's in production but I wouldn't say we "tested" it. None of our crash reporting tools are firing but that doesn't really mean much.

The only thing I'm saying is that's how I got past though compilation errors. Use at your own risk. Seems fine to me though.

**Comment by evanjmg** [comment]
Any update on this?

**Comment by evanjmg** [comment]
I got it working with v23 using the v26 build sdk, but run it on an earlier device -
 > https://github.com/tinycreative/react-native-intercom/pull/92

**Comment by punksta** [comment]
works fine with 26 api level

**Comment by cfmitrah** [comment]
I'm getting this below error when i create a release apk of the app
Execution failed for task ':react-native-intercom:verifyReleaseResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

my SDK versions:
compileSdkVersion 28
buildToolsVersion "28.0.3"

**Comment by darshan-raj** [comment]
Facing the same error. The error trace is:

```Failed to generate resource table for split ''
/Users/darshan/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/68a5a7c2c36825ccfc043e07cc73f1df/res/values-v28/values-v28.xml:5:5-8:13: AAPT: 
No resource found that matches the given name (at 'dialogCornerRadius' with value '?android:attr/dialogCornerRadius').


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-intercom:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt```

**Comment by Dineshchitta** [comment]
@darshan-raj Did you resolve the issue ?

**Comment by Subway19** [comment]
@darshan-raj  @Dineshchitta  did you resolve this?

**Comment by Dineshchitta** [comment]
@Subway19 We downgraded the version to `10.2.0` and in android build.gradle we are using
 `compile 'io.intercom.android:intercom-sdk:4.+'` . It is working fine

**Comment by Subway19** [comment]
@Dineshchitta  can you please also tell me your `app/build.gradle` important field values like `compileSdkVersion`, `buildToolsVersion `and `targetSdkVersion` ?  I have spent 2 days in this issue!!

**Comment by Dineshchitta** [comment]
```
compileSdkVersion 26
buildToolsVersion "26.0.2"
minSdkVersion 16
targetSdkVersion 25

```

@Subway19

**Comment by Subway19** [comment]
@Dineshchitta  thanks so much. Working now. :) :+1:
