### ISSUE TITLE
React-native 0.45 and Intercom 6.2.0 broken

### ISSUE THREAD

**Issue by mmckinley8** [tinycreative/react-native-intercom#108]
After running:
`npm install -g react-native-intercom`
`react-native link`

Builds are failing due to 'Intercom/intercom.h file not found'. Has anyone else run into this issue and has a work around/solution?

**Comment by browniefed** [comment]
You must download and add Intercom. This doesn't ship with Intercom

**Comment by mmckinley8** [comment]
@browniefed you mean download the native SDK and bridge it?

**Comment by browniefed** [comment]
Yes follow the manual installation guideline here https://github.com/intercom/intercom-ios
