### ISSUE TITLE
Error: Cannot read property 'UNREAD_CHANGE_NOTIFICATION' of undefined

### ISSUE THREAD

**Issue by grifotv** [tinycreative/react-native-intercom#109]
After adding the line `import Intercom from 'react-native-intercom';` I get the following error:

![screen shot 2017-06-30 at 19 19 09](https://user-images.githubusercontent.com/435351/27748877-0ac27d1e-5dc9-11e7-9c83-796ede406011.png)

I followed all steps of the iOS installation. Could you kindly point me to the right direction?

**Comment by ohtangza** [comment]
I am also having this issue... by the following instruction here.

**Comment by ohtangza** [comment]
I had this because the library is not linked well, now solved.

**Comment by grifotv** [comment]
@ohtangza could you let me know how you linked the library? thanks

**Comment by PrimeLens** [comment]
I'm stuck on this as well.
 Sorry, I'm new to the native eco system but  how do you link the library?

**Comment by PrimeLens** [comment]
Looked in the other thread and someone mentions "lRNIntercom.a" yet this file does not exist in the folder structure. 
Please advise what library, what file and how you linked if in Android Studio. Thanks!

edit:
I solved my problem by editing App > build.gradle and changing 
`buildToolsVersion "23.0.2"` to `buildToolsVersion "25.0.2"`

**Comment by ghost** [comment]
You also get this when trying to test using Jest. I have tried to mock but then get memory overflow problems.

**Comment by ohtangza** [comment]
@grifotv In my case, I run `react-native link` again and then restarted the packager.

**Comment by irritant** [comment]
If you encounter this issue while testing with Jest, try this mock:

```
// jest/mocks/react-native-intercom.js:
const mockReactNativeIntercom = {
  registerIdentifiedUser: jest.genMockFn().mockReturnValue(Promise.resolve()),
  registerUnidentifiedUser: jest.genMockFn().mockReturnValue(Promise.resolve()),
  updateUser: jest.genMockFn().mockReturnValue(Promise.resolve()),
  reset: jest.genMockFn().mockReturnValue(Promise.resolve()),
  logEvent: jest.genMockFn().mockReturnValue(Promise.resolve()),
  handlePushMessage: jest.genMockFn().mockReturnValue(Promise.resolve()),
  displayMessenger: jest.genMockFn().mockReturnValue(Promise.resolve()),
  hideMessenger: jest.genMockFn().mockReturnValue(Promise.resolve()),
  displayMessageComposer: jest.genMockFn().mockReturnValue(Promise.resolve()),
  displayMessageComposerWithInitialMessage: jest.genMockFn().mockReturnValue(Promise.resolve()),
  displayConversationsList: jest.genMockFn().mockReturnValue(Promise.resolve()),
  getUnreadConversationCount: jest.genMockFn().mockReturnValue(Promise.resolve()),
  setLauncherVisibility: jest.genMockFn().mockReturnValue(Promise.resolve()),
  setInAppMessageVisibility: jest.genMockFn().mockReturnValue(Promise.resolve()),
  setupAPN: jest.genMockFn().mockReturnValue(Promise.resolve()),
  registerForPush: jest.genMockFn().mockReturnValue(Promise.resolve()),
  setUserHash: jest.genMockFn().mockReturnValue(Promise.resolve()),
  setBottomPadding: jest.genMockFn().mockReturnValue(Promise.resolve()),
  addEventListener: jest.fn(),
  removeEventListener: jest.fn()
};

export default mockReactNativeIntercom;

// jest/setup.js:
import mockReactNativeIntercom from './mocks/react-native-intercom';
jest.mock('react-native-intercom', () => mockReactNativeIntercom);
```

**Comment by ghost** [comment]
Many thanks @irritant it appears my issue is elsewhere causing jest to fail with an out of memory error now.

**Comment by ignatevdev** [comment]
I had the same issue, the package is installed and linked, but still receive the same error.
The problem was in the fact, that this package doesn't come with Intercom library, you have to install it yourself.

In my case, I was targeting iOS and after following the instructions here the problem is solved.
https://github.com/intercom/intercom-ios

Just make sure, that after you add a "Run script" in your Build phases, this script is placed after "Embed frameworks"

**Comment by ajonno** [comment]
thanks @NSLS your post was a great help as I also had same problem and resolved (in same manner)

one thing written into the Intercom iOS installation docs, which i needed to change (my builds were failing) was the bash script path. In my app, I had dragged/dropped the Intercom.framework path directly underneath the projects root. ie per this screenshot

![image](https://user-images.githubusercontent.com/3005269/29246021-2df384d0-802f-11e7-8aec-81aaab42f094.png)

because of that, the path to the .sh needed to be as follows:
![image](https://user-images.githubusercontent.com/3005269/29246025-59e56b9e-802f-11e7-9905-e314e20365fc.png)

this might not be obvious to some so thought I'd add it in here. in reality Intercom should add a footnote to their iOS install docs about this.

**Comment by lorenzorheinicke** [comment]
Thank for the all of instructions above. I still had this issue on iOS after trying everything above. The final steps that fixed the problem, for me, were:
1. In XCode, in the project navigator right click Libraries ➜ Add Files to [your project's name]
2. Go to node_modules ➜ react-native-intercom➜ iOS and add IntercomWrapper.h, IntercomWrapper.m, IntercomEventEmitter.h and IntercomEventEmitter.m.

Build your iOS project and try again. 

This worked for me.

**Comment by isAlmogK** [comment]
I'm encountering this issue when I run my first jest test, I have the required lib in iOS and intercom is working just fine 

Here is the output 

Test suite failed to run

    TypeError: Cannot read property 'UNREAD_CHANGE_NOTIFICATION' of undefined
      
      at new IntercomClient (node_modules/react-native-intercom/lib/IntercomClient.js:26:117)
      at Object.<anonymous> (node_modules/react-native-intercom/lib/IntercomClient.js:356:16)
      at Object.<anonymous> (app/lib/helpers/intercomHelpers.js:5:174)


My test is simple 
```
it('renders correctly', () => {
    const tree = renderer.create(
        <Login />
    ).toJSON();
    expect(tree).toMatchSnapshot();
}); 
```

Anyone have any ideas how to fix this

**Comment by nicolasadamini** [comment]
Something that works for me: 
```
jest.mock('react-native-intercom', () => {}, { virtual: true });
```

**Comment by kevinmcalear** [comment]
- [x] k 
- [x] sdf
- [ ] sdf
- [ ] sdf
- [ ] sdf
- [ ] _**penis**_ [rtyui](url)

**Comment by idan6189** [comment]
any solution?

**Comment by anshul-kai** [comment]
Struggling here as well...

**Comment by anshul-kai** [comment]
Was able to solve using [this](https://github.com/tinycreative/react-native-intercom/issues/174#issuecomment-406829978)

**Comment by ryanmargheriti** [comment]
I am also having this problem. New to the RN ecosystem so hard for me to debug. I have tried all the potential fixes in this and other threads to no avail.

**Comment by Annihil** [comment]
For me neither, it does not seem to be related to a configuration problem as it builds and runs just fine on both platforms.
It's only while executing Jest unit tests that are importing react-native-intercom...

Mocking the module did not fix the problem for me

**Comment by Annihil** [comment]
Alleluia, I found how to work around this problem!
Use `require` for all of your imports importing react-native-intercom in your tests and
```js
jest.mock('react-native-intercom', () => {});
```

**Comment by alishaevn** [comment]
> Thank for the all of instructions above. I still had this issue on iOS after trying everything above. The final steps that fixed the problem, for me, were:
> 
> 1. In XCode, in the project navigator right click Libraries ➜ Add Files to [your project's name]
> 2. Go to node_modules ➜ react-native-intercom➜ iOS and add IntercomWrapper.h, IntercomWrapper.m, IntercomEventEmitter.h and IntercomEventEmitter.m.
> 
> Build your iOS project and try again.
> 
> This worked for me.

In addition to the 4 files listed above, I also added:
- IntercomUserAttributesBuilder.m
- IntercomUserAttributesBuilder.h 
(I noticed that IntercomUserAttributesBuilder.h is imported in the IntercomWrapper.m file)

Adding the 6 files finally allowed me to import Intercom using `import Intercom from 'react-native-intercom'` and actually call Intercom `Intercom.logEvent('viewed_screen', { extra: 'metadata' })` without getting any red screens.

**Comment by Subway19** [comment]
https://github.com/tinycreative/react-native-intercom/issues/317

**Comment by gulllberg** [comment]
> If you encounter this issue while testing with Jest, try this mock:
> 
> ```
> // jest/mocks/react-native-intercom.js:
> const mockReactNativeIntercom = {
>   registerIdentifiedUser: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   registerUnidentifiedUser: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   updateUser: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   reset: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   logEvent: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   handlePushMessage: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   displayMessenger: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   hideMessenger: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   displayMessageComposer: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   displayMessageComposerWithInitialMessage: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   displayConversationsList: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   getUnreadConversationCount: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   setLauncherVisibility: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   setInAppMessageVisibility: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   setupAPN: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   registerForPush: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   setUserHash: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   setBottomPadding: jest.genMockFn().mockReturnValue(Promise.resolve()),
>   addEventListener: jest.fn(),
>   removeEventListener: jest.fn()
> };
> 
> export default mockReactNativeIntercom;
> 
> // jest/setup.js:
> import mockReactNativeIntercom from './mocks/react-native-intercom';
> jest.mock('react-native-intercom', () => mockReactNativeIntercom);
> ```

Worked for me, but I had to replace genMockFn() with fn()
