### ISSUE TITLE
Android docs unclear, where is this meant to be placed?  –  Intercom.initialize(  getApplicationContext(), key, id )

### ISSUE THREAD

**Issue by PrimeLens** [tinycreative/react-native-intercom#111]
The  method  `getApplicationContext`  is defined in  `IntercomIntentService.java`  but the docs aren't clear and it almost suggests the line should be placed in javascript.
Where should it be placed so it makes use of the `getApplicationContext` method?

For android only, see README.md

**Comment by PrimeLens** [comment]
bump.
anyone?

**Comment by qmegas** [comment]
In `YOUR_PROJECT_FOLDER\android\app\src\main\java\your-app-namespace-path\MainApplication.java`
Inside `onCreate` function.
