### ISSUE TITLE
iOS handlePushMessage

### ISSUE THREAD

**Issue by zachrnolan** [tinycreative/react-native-intercom#113]
Hi All, 

First off, thanks to all who contribute to this project.

I recently implemented push notifications through Intercom and I'm receiving them successfully on my test device. I'm trying to send push messages with an iOS link to open a specific screen in my app and I'm not sure how/where to put my routing logic.

I see there is a method called `handlePushMessage`, but I don't see any documentation on how to use it. I'm trying something like this:

```
AppState.addEventListener('change', this.handleAppStateChange)

handleAppStateChange(currentAppState) {
    Intercom.handlePushMessage((a) => {
      console.log('a: ', a)
    })
}
```

I'm not getting any console log. I'm assuming I should be able to call this method and get back the link that I had set on the push message so I could perform the appropriate routing.

If anyone could steer me in the right direction, I would greatly appreciate it.

Thanks!

**Comment by zachrnolan** [comment]
A little more context:

I'm using branch.io to handle deep linking and have it working with another push notification platform (onesignal). Our goal is to move from one signal to intercom for sending manual push notifications.

I'm able to receive push notifications (using intercom and this library) on both iOS and Android. The only difference is the handling of the deep link. Android just worked out of the gate, so when I tap on the push notification, it takes me to the correct screen in the app. For iOS, tapping the push notification only opens the app and doesn't carry over the deep link.

**Comment by fryossi** [comment]
Hi,
[iOS] Same for me. I can't get the deep link when tapping on the notification (works fine when getting push while the app is open).

**Comment by zachrnolan** [comment]
@browniefed anyway you can help out with this? Are there any examples of how to handle deep links coming from Intercom?

**Comment by vvusts** [comment]
@zachrnolan did you ever solved it?

**Comment by zachrnolan** [comment]
@vvusts, unfortunately, I haven't. Let me know if you figure it out.

**Comment by MayoudP** [comment]
Any update here ?

**Comment by bogdan-vol** [comment]
@zachrnolan Have you ever succeeded in setting up deep link for iOS?
I'm trying to open the app from a URL from the chat box. On android it worked out of the box. On iOS deep linking also works with other apps (other messengers, email app etc) but intercom just opens safari, where I get the 'Open' button at the top.

**Comment by zachrnolan** [comment]
@bogdan-vol I eventually gave up on Intercom deep links for iOS. Some projects I've done recently have decided to go with products like CleverTap. Let me know if you ever figure it out.

**Comment by ZeerakHameem32** [comment]
Hi any update guys? 
I can't get the deep link from iOS push when the app is closed / or when the app cold starts. Works fine when the app is in memory.
Android works fine.

**Comment by trudyga** [comment]
@ZeerakHameem32 , If the application is **opened** by the deep link you can access `getInitialUrl` method of the Linking module. See docs [here](https://reactnative.dev/docs/linking#getinitialurl).
```js
import { Linking } from 'react-native';

const initialUrl = await Linking.getInitialURL();

handleLink(initialUrl); // handle Link in this function 
```

If you have configured everything correctly this should work. I hope this helps you.
