### ISSUE TITLE
duplicate symbol _OBJC_CLASS_$_IntercomEventEmitter

### ISSUE THREAD

**Issue by nazarTrynko** [tinycreative/react-native-intercom#114]
I have problems with resolving duplicate symbol _OBJC_CLASS_$_IntercomEventEmitter in 
```
.../Build/Products/Debug-iphonesimulator/react-native-intercom/libreact-native-intercom.a(IntercomEventEmitter.o)
.../Build/Products/Debug-iphonesimulator/libRNIntercom.a(IntercomEventEmitter.o)
duplicate symbol _OBJC_METACLASS_$_IntercomEventEmitter in:
```
and other similar.
`4 duplicate symbols for architecture x86_64`

Already tried removing `-ObjC` from "Other Linker Flags"

**Comment by jpokrzyk** [comment]
@nazarTrynko You get anywhere with this?

**Comment by martimarkov** [comment]
Are you using react-native 0.48?

**Comment by nazarTrynko** [comment]
I'm on 0.45, but I managed this problem somehow

**Comment by martimarkov** [comment]
Hmm. I’m still having it right now. Did you run react-native link and added to pod files or just link is enough?

**Comment by nazarTrynko** [comment]
@martimarkov I don't really remember, but could be that I used only pods and it finally worked. Or just react-native link, cause in pods I only have pod 'Intercom' and in Header Search Paths "$(SRCROOT)/../node_modules/react-native-intercom/iOS"

**Comment by LordParsley** [comment]
I encountered this too and referenced `Intercom` directly from my Podfile as a workaround:

```
pod 'Intercom'
# pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'
```

Previously I was only referencing `react-native-intercom`.

**Comment by nhanha** [comment]
I'am having the same issue right now.
I do the above steps, but it does not help.

![image](https://user-images.githubusercontent.com/4194655/113099350-024cd600-9224-11eb-8a45-512795441617.png)

**Comment by nhanha** [comment]
I am having the same issue. I tried above comment, but it does not help.

> duplicate symbol '_OBJC_CLASS_$_IntercomEventEmitter' in:
> ......
> _ld: 6 duplicate symbols for architecture arm64_
> _clang: error: linker command failed with exit code 1 (use -v to see invocation)_

Do you have any more ideas to resolve it?

**Comment by nhanha** [comment]
After I removed **libRNIntercom.a**  at "**Link Binary with Libraries**", It works.
