### ISSUE TITLE
registerIdentifiedUser inconsistent between iOS and Android

### ISSUE THREAD

**Issue by solussd** [tinycreative/react-native-intercom#115]
On iOS, passing both "userId" and "email" keyvals results in a call to Intercom's `registerUserWithUserId:email:` method with both userId and email. 

(iOS implementation: https://github.com/tinycreative/react-native-intercom/blob/master/iOS/IntercomWrapper.m#L17)

On Android, if both are passed a `Registration` object is created with only the "email" keyval and it is passed to `Intercom.client().registerIdentifiedUser`.

(Android implementation: https://github.com/tinycreative/react-native-intercom/blob/master/android/src/main/java/com/robinpowered/react/Intercom/IntercomModule.java#L39)

Passing both is useful in the case where multiple (unique) userIds have the same email address. I believe the iOS implementation is correct.

**Comment by agrass** [comment]
I had some troubles with this as well. Because I use user_id, and Intercom SDK throw error: "Multiple existing users match this email address" due the user_id was not used

**Comment by rolfb** [comment]
Why was this closed? It doesn't seem to be solved yet.

**Comment by rolfb** [comment]
Nevermind, this seems fixed by #343 - just awaiting merge and release.
