### ISSUE TITLE
Changes between v5 and v7?!

### ISSUE THREAD

**Issue by nerdmed** [tinycreative/react-native-intercom#119]
It is really hard to update to new major versions without having any infos. Any chance to maintain a Changelog or releases on github? Just one sentence about what is breaking between major versions or which versions are pinned and a link would be great. And an info if it safe to update!

Would be great to see this.

Best Matt

**Comment by peterpme** [comment]
@nerdmed Can you please not spam your issues? These are real people like yourself trying to make this a better library.

Perhaps you could go through the code changes  and write the release log yourself 😄

In the mean time, sticking to version 5 sounds like your best bet!

Thanks

**Comment by nerdmed** [comment]
@peterpme thanks for your friendly response that encourages a lot to support this library and to use it. 👎

**Comment by nerdmed** [comment]
PS.: It was an github bug that created the multiple issues
