### ISSUE TITLE
Error: No known class method

### ISSUE THREAD

**Issue by Leo-Kaveh** [tinycreative/react-native-intercom#12]
I followed the guideline in README.md step by step. I don't use CocoaPods so I added intercom library manually. When I built the project, I got this error:
"No known class method for selector 'registerForNotifications' " in IntercomWrapper.m file.
<img width="1221" alt="screen shot 2016-04-16 at 12 40 53 pm" src="https://cloud.githubusercontent.com/assets/5405159/14579904/7c41536a-03d0-11e6-976b-f5ddacc2f765.png">

Does it necessary to use CocoaPods ? or the problem is something else?

**Comment by browniefed** [comment]
I believe this would require you to add in the `Framework Search Paths` correctly. Latest master has this working automatically, however it's not currently published.

**Comment by asamiller** [comment]
I published the updates to npm last night. Try updating to `1.1.0`.

**Comment by Leo-Kaveh** [comment]
I used the latest update but it didn't work!
Let me explain what I'm doing:
1. I install react-native-intercom by using this command: "npm install react-native-intercom"
2. In xcode, I added IntercomWrapper.h and IntercomWrapper.m files under library directory.
3. I added intercom library manually as describe by Intercom :
![screen shot 2016-04-17 at 3 00 00 pm](https://cloud.githubusercontent.com/assets/5405159/14586422/23c98864-04ad-11e6-9816-d21b3b2efda3.png)

but in the end I got the error again!

**Comment by browniefed** [comment]
Sorry forgot to update the documentation. The library is now a static lib, you do not need to copy and paste things in you can just use https://github.com/rnpm/rnpm or you can follow this for the manual way https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content

However I highly suggest you install RNPM

**Comment by Leo-Kaveh** [comment]
As I'm completely a rookie in this field, there is a hight probability that I'm doing something wrong! 
I added the library by using this: "rnpm install react-native-intercom". 
The library is installed successfully:
![screen shot 2016-04-18 at 10 01 30 am](https://cloud.githubusercontent.com/assets/5405159/14594519/91840204-054c-11e6-951d-de50eff7e8db.png)

I didn't add the intercom library manually this time but I got another error in IntercomWrapper.m file:
'Intercom/Intercom.h' file not found!
<img width="1226" alt="screen shot 2016-04-18 at 10 00 04 am" src="https://cloud.githubusercontent.com/assets/5405159/14594489/5f302d3c-054c-11e6-83bc-6347de3cf22b.png">

Should I install an intercom library by using rnpm or something else is going wrong?

**Comment by browniefed** [comment]
This time add intercom library like you did before

**Comment by browniefed** [comment]
@A-Kaveh did you get this figured out? Basic process manually add Intercom like you did before, `rnpm link`, you should be good to go

**Comment by Leo-Kaveh** [comment]
Unfortunately NO. I did use `rnpm link`, but it didn't work!

**Comment by browniefed** [comment]
Ah damn, I will need to look into this tonight. Sorry about the trouble.

**Comment by browniefed** [comment]
Just tested it and it works just fine :/. 

Make sure you add the code to your `AppDelegate.m`

```
#import "Intercom/intercom.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Initialize Intercom
    [Intercom setApiKey:@"<#ios_sdk-...#>" forAppId:@"<#your-app-id#>"];
}
```

**Comment by Leo-Kaveh** [comment]
The problem is this part: `#import "Intercom/intercom.h"`
If I don't add the intercom library manually, "Intercom" won't be recognized!
Please look at the second image I posted here.

**Comment by browniefed** [comment]
Yes, I know, we do not ship with Intercom so you need to add it manually, or use pods.

**Comment by browniefed** [comment]
So the process is.
`rnpm link`
Drag over the Intercom framework into Xcode.
Add `#import "Intercom/intercom.h"` to the top of `AppDelegate.m`
Then add `[Intercom setApiKey:@"<#ios_sdk-...#>" forAppId:@"<#your-app-id#>"];` inside the application method.

**Comment by Leo-Kaveh** [comment]
Finally the error is gone! I didn't use the intercom library completely yet but I could built the project without error.
Thank you @browniefed  a lot for your patient.

**Comment by browniefed** [comment]
Fantastic!
