### ISSUE TITLE
Integration with Expo

### ISSUE THREAD

**Issue by jgkiano** [tinycreative/react-native-intercom#120]
Hi,  is it possible to integrate this with an application built with expo without having to eject. Thanks

**Comment by browniefed** [comment]
No it isn't, this is not an accepted module into Expo.
However if you brought it up to them they may consider adding it.

**Comment by slorber** [comment]
There is already a Canny for that: https://expo.canny.io/feature-requests/p/add-intercom-support

Note that for users coming from Expo detached, for SDK23 you can use v8.1.0 of this lib.

If you want push to be displayed as notifications in Android, you should add the following dependencies:

```
  compile('io.intercom.android:intercom-sdk-fcm:3.+') {
      exclude group: "com.google.firebase", module: 'firebase-messaging'
  }
  compile 'com.google.firebase:firebase-messaging:9.8.0'
```
