### ISSUE TITLE
Add "post a note" API integration

### ISSUE THREAD

**Issue by GeoffreyPlitt** [tinycreative/react-native-intercom#124]
The native SDKs have an ability to post a private note to a conversation:
https://developers.intercom.com/reference#replying-to-a-conversation

Can we get this exposed in the RN lib?

**Comment by GeoffreyPlitt** [comment]
Any update on this? It's already in the native SDKs so we just need it to be exposed here.

**Comment by GeoffreyPlitt** [comment]
@browniefed

**Comment by jtreanor** [comment]
Hi @GeoffreyPlitt,

Adding notes to conversations is not supported in Intercom’s Messenger for any platform (iOS, Android or Web). Since that is what this project is based on unfortunately this will not be possible.

The documentation you have linked to is for Intercom’s REST API. Unfortunately, currently the only way to add a note is to use that.

**Comment by GeoffreyPlitt** [comment]
Gotcha. So let's say I use the REST api to start a conversation. Can this library open to that conversation by ID or something? Or the reverse: if I start a conversation with this library, can I then use the REST api to post a message into that same conversation, by ID? How does this library expose those IDs? I don't see that in the README.

**Comment by GeoffreyPlitt** [comment]
@jtreanor Thoughts?

**Comment by jtreanor** [comment]
Conversation ids are not exposed by this library. I suggest talking to Intercom's support team about what you are trying to do here. There may be something simpler you can do to achieve what you want here. You can chat to them through the Messenger on [https://intercom.com](https://intercom.com).

**Comment by GeoffreyPlitt** [comment]
@jtreanor I'm not sure you saw my latest question. I AM trying to use the REST api, but I'll need the ID of the conversation I think, right? How do I get that from your lib?

**Comment by GeoffreyPlitt** [comment]
Gotcha, thanks!

**Comment by GeoffreyPlitt** [comment]
Update: So the Intercom team told me I can use a mixture of webhooks, backend REST api calls, and sending the context from the app to our backend, to sort of work around this. As long as a single user is not creating multiple simultaneous conversations it will probably work, although not ideal. Just thought I'd share this update in case other people find this bug and are curious what I ended up doing.
