### ISSUE TITLE
React-Native - Android Color

### ISSUE THREAD

**Issue by nyanofthemoon** [tinycreative/react-native-intercom#126]
Using custom color code chosen in Intercom app settings #2896d3.
Color works on iOS but returns a different blue on Android.
Using latest react-native-intercom and latest react-native as of date.

**Comment by javiercr** [comment]
We are using the latest version of the library and we see the custom color both on Android and iOS. 

@nyanofthemoon are you sure you're using the same intercom app id for Android and iOS? Is it possible you may be using Intercom's test app id for Android and the production one for iOS?

**Comment by hannigand** [comment]
I get this problem on iOS. When I first build my application, it defaults to the _Intercom blue_. After I interact with the button, it then successfully changes to the colour I set in the Intercom settings.

**Comment by mkmlh** [comment]
@nyanofthemoon is it happens in push notification side? it happens to me on Android Oreo.
What i've to do is make sure your icon is transparent.
Transparent icon will filled up with intercom colour which is from intercom->messenger->style your messenger->Change Action colour into your desired ones 
_voila_
