### ISSUE TITLE
auto send in displayMessageComposerWithInitialMessage 

### ISSUE THREAD

**Issue by Naveen-ICARUS** [tinycreative/react-native-intercom#129]
HI,
This is a wonderful library, saves lot of my time 

Actually this is not an issue but I looking for a feature from Intercom, I don't know whether it is already exist or not. What i wanted is to send initial message when a user begin new chat using **displayMessageComposerWithInitialMessage()** method, the message is coming in input field in the chat   window but its not sending it automatically (which is feature I'm looking for). After surfing internet I didn't get any example or resource regarding this. Please let me know whether this feature exist or not.

-Thank you

**Comment by khunghang16** [comment]
.
