### ISSUE TITLE
Link the library

### ISSUE THREAD

**Issue by Leo-Kaveh** [tinycreative/react-native-intercom#13]
When I wanted to show a message composer, I just got this warning:
<img width="377" alt="screen shot 2016-05-07 at 12 41 54 pm" src="https://cloud.githubusercontent.com/assets/5405159/15091039/4481a920-1451-11e6-91cb-7f7b2092e56c.png">
and nothing happened! So I reviewed the README.md again and checked the linking process. 

After using `rnpm link` command, the terminal output is like this:
![screen shot 2016-05-07 at 12 20 01 pm](https://cloud.githubusercontent.com/assets/5405159/15090967/715f3aa0-144e-11e6-8320-abbf831d2870.png)
Three library are linked as you can see but there is no intercom library. So I tried to link the library manually. Base on the instructions(https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content), first step is adding `.xcodeproj` file to the Xcode but there is no such a file in intercom library (under `node_modules` directory). On the other hand, the library is added to `dependencies` in `package.json` file. Do I need to link the library at all?

Is the linking process causes the error? or something else is going wrong?

**Comment by browniefed** [comment]
That should work just fine, I'm sorry I don't know enough about what you are doing to say this is any fault of the intercom library. I can add and link everything just fine on my end so I don't know how much I can help out.

**Comment by Leo-Kaveh** [comment]
@browniefed what about the warning? Don't you have any idea?

**Comment by browniefed** [comment]
You seem to have some bad code somewhere, you'll need to do some debugging. I would try creating a new sample project with `react-native init` and trying to do an install of `react-native-intercom`

**Comment by Leo-Kaveh** [comment]
Thanks @browniefed. I'm looking forward to see your project.

**Comment by browniefed** [comment]
@A-Kaveh I'm saying you should try this, not me. I know it works. Just confirm that things are working in an fresh environment for you.

**Comment by Partysun** [comment]
@browniefed help pls ;)
react-native init sample
npm i --save react-native-intercom
rnpm link
react-native run-ios

And this is result.
![screenshot 2016-05-22 21 56 14](https://cloud.githubusercontent.com/assets/522287/15455248/2ec59d26-2068-11e6-91a7-05818acbddc0.png)
![screenshot 2016-05-22 21 56 37](https://cloud.githubusercontent.com/assets/522287/15455249/308a55d4-2068-11e6-9ad4-c47a9ffc62c1.png)

**Comment by Partysun** [comment]
@A-Kaveh maybe it helps you.

Resolved. After next steps...

_How to install CocoaPods? Use google.
Remember after cocoapods has installed, you should launch pod setup._

### Install Intercom via Pod

```
cd ios
pod init
```

open Podfile and add "... pod 'Intercom' ..."
`pod install`
![screenshot 2016-05-23 12 53 04](https://cloud.githubusercontent.com/assets/522287/15463833/570968da-20e5-11e6-95c5-9da1b13f1077.png)

### fix ldflags => Build Settings

![screenshot 2016-05-23 12 57 19](https://cloud.githubusercontent.com/assets/522287/15463951/ee2f2f06-20e5-11e6-9a70-5d6a457f821f.png)

open workspace instead xcodeproj
open AppDelegate.m and

```
...
#import "Intercom/intercom.h"


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [Intercom setApiKey:@"ios_sdk-your-apikey" forAppId:@"your-app-id"];
...
```

### And install react-native-intercom

```
npm i --save react-native-intercom
rnpm link react-native-intercom
```

Yep.. It works after that. 👌

**Comment by browniefed** [comment]
@Partysun thank you for that, I should make it more clear that you MUST add the library yourself. We do not ship with it for many reasons.
If you don't mind I'll be sure and add this to the README.

**Comment by Partysun** [comment]
@browniefed Yes. I installed more than 10 different cool react-native modules in my current project and I have only one without native libs installed with a module.
For example hockeyapp, facebook, player, webrtc has dep. libs installed.

**Comment by browniefed** [comment]
Yea I understand, I chose not to ship with it to avoid having to constantly update this with whatever version or system people choose to use (manual installation/carthage/pods/etc).

**Comment by peterp** [comment]
@browniefed would you be willing to revisit this decision? You mentioned that you're not actively maintaining or using this library and are instead just shipping changes. So at this stage, based on your reason above for not linking the library, would you be willing to allow the community to add the linking of the library?
