### ISSUE TITLE
Is this package up to date and working? 

### ISSUE THREAD

**Issue by isAlmogK** [tinycreative/react-native-intercom#131]
Just tried to install this for Android get nothing but errors? Is this package still active ?

**Comment by javiercr** [comment]
We're using it in production both for Android and iOS. What are the errors?

**Comment by isAlmogK** [comment]
This is the error I'm getting 
 Cannot read property 'UNREAD_CHANGE_NOTIFICATION' of undefined

My code : 
```
var Intercom = require('react-native-intercom');

componentWillUnmount() {
        this.setState = {}
        Intercom.removeEventListener(Intercom.Notifications.UNREAD_COUNT, this._onUnreadChange);
    }

    componentDidMount() {
        Intercom.addEventListener(Intercom.Notifications.UNREAD_COUNT, this._onUnreadChange)

    }
_onUnreadChange = ({ count }) => {

    }

 // Launch intercom
    _intercomLaunch(){
        Intercom.displayMessageComposer();
    }
```

**Comment by isAlmogK** [comment]
I'm closing this got it working, link did work correctly for some reason

**Comment by stueynet** [comment]
@AlmogRnD I am having the exact same issue. Have tried the set up from scratch multiple times and no luck. Can you give a bit more detail on how you fixed this?

**Comment by isAlmogK** [comment]
@stueynet I updated react and update my build and gradel to a higher number

**Comment by stueynet** [comment]
@AlmogRnD updated to 0.48?
