### ISSUE TITLE
Intercom version range in podspec can lead to breakage

### ISSUE THREAD

**Issue by pandeiro** [tinycreative/react-native-intercom#134]
As of right now, building an app with react-native-intercom (version 7.x.x) on iOS fails to compile due to the error "No known class method for selector 'updateUserWithAttributes:'" (IntercomWrapper.m).

As the upstream library changes its API surface, these breakages can occur any time if version ranges are used.

Please consider pegging to a specific version of Intercom to increase stability.

**Comment by browniefed** [comment]
Fixed in v8
