### ISSUE TITLE
Does the package support identity verification

### ISSUE THREAD

**Issue by isAlmogK** [tinycreative/react-native-intercom#138]
I wanted to know if the package supports identity verification - https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-identity-verification-on-your-web-product 

We have it enabled in our app but when we launch the composer screen I'm getting "Something went wrong" 

Here is my code:
// Launch intercom
    ```
_intercomLaunch(){
        const userInfo = store.getState().user;
        Intercom.registerIdentifiedUser({userId: userInfo.id});
        Intercom.setUserHash({userHash: userInfo.hashedId});

        Intercom.updateUser({
            email: userInfo.email,
            name: userInfo.fullName,
        });
        Intercom.displayMessageComposer();
    }
```

Also treid the following 

 ```
const userInfo = store.getState().user;
        //Intercom.registerIdentifiedUser({userId: userInfo.id});
        Intercom.setUserHash({userHash: userInfo.hashedId});

        Intercom.updateUser({
            userId: userInfo.id,
            email: userInfo.email,
            name: userInfo.fullName,
        });
```

**Comment by isAlmogK** [comment]
Closing this an issue on my end

**Comment by inspireui** [comment]
Hi, could you share your solution as i have turned on the identity verification then could not load the Intercom - [![Screenshot from Gyazo](https://gyazo.com/b4161387592926234ee38180725e7c84/raw)](https://gyazo.com/b4161387592926234ee38180725e7c84)

It's ok if turn off the option

**Comment by isAlmogK** [comment]
I have the following and it works hope it helps 

```
registerIdentifiedUser: function (userInfo, hashedIds) {
        //console.log(userInfo)
        Intercom.registerIdentifiedUser({userId: userInfo.id});
        // For ios Intercom Hash
        if(Platform.OS === 'ios' ) {
            Intercom.setUserHash(hashedIds.ios);
        }

        // For android Intercom Hash
        if(Platform.OS === 'android' ) {
            Intercom.setUserHash(hashedIds.android);
        }
        Intercom.updateUser({
            email: userInfo.email,
            name:  userInfo.fullName,
            created_at: userInfo.createdAt,
            phone: userInfo.mobile,
        });
        return true;
    },
```

**Comment by inspireui** [comment]
Thank you so much, is the hashedIds string generated from your server side ?

**Comment by isAlmogK** [comment]
Yes but there is some intercom settings you need to do, check their docs

**Comment by inspireui** [comment]
Great, i got it. Thank you for quickly response!
