### ISSUE TITLE
Receiver 'ICMUserAttributes' for class message is a forward declaration

### ISSUE THREAD

**Issue by afilp** [tinycreative/react-native-intercom#142]
I have updated our project to the latest React Native and Intercom versions.

I have been using the `pod` logic for Intercom with success.

However, now I get the following message when building the app:

`Receiver 'ICMUserAttributes' for class message is a forward declaration`

And this is associated with a total of 19 errors, referring to the `attributes`, all of them inside the `IntercomUserAttributesBuilder.m` file

Is this a bug? Or do I need to change something? Thanks!

**Comment by afilp** [comment]
Hello, does anybody else have this problem?

**Comment by mbifulco** [comment]
Hi - I'm also running into this @afilp.  I just upgrade `react-native-intercom`, and ran `react-native-git-upgrade` to get me to rn v.0.51.0.
