### ISSUE TITLE
Question about enabling push notifications 

### ISSUE THREAD

**Issue by isAlmogK** [tinycreative/react-native-intercom#144]
I would like to enable push notifications should I be following this guide https://developers.intercom.com/docs/cordova-phonegap-push-notifications

Or following the pure IOS / Android guide  - https://developers.intercom.com/docs/ios-push-notifications

**Comment by isAlmogK** [comment]
closing this as I have it working

**Comment by johnculviner** [comment]
@AlmogRnD which guide did you use or how did you get this working? Having alot of issues with this and have tried everything I can think of

**Comment by johnculviner** [comment]
I got it working finally. make sure your cert is right and you can send push notifications your self before trying to get intercom to work as you will not get any error messages out of them: https://developers.intercom.com/v2.0/docs/ios-push-notifications
