### ISSUE TITLE
Cannot build android (react:native:intercom:unspecified > com.facebook.react:react-native:0.50.3)

### ISSUE THREAD

**Issue by mmckinley8** [tinycreative/react-native-intercom#153]
Just successfully installed on iOS but am receiving the following compilation error on android.

intercom version: 9.0.0
react-native version: 0.50.3

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-intercom'.
      > Could not resolve all dependencies for configuration ':react-native-intercom:_debugPublishCopy'.
         > Could not find com.android.support:appcompat-v7:26.1.0.
           Searched in the following locations:
               file:/Users/MichaelMcKinley/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
               file:/Users/MichaelMcKinley/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
               file:/Users/MichaelMcKinley/Development/movespring/mobile/android/sdk-manager/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
           Required by:
               MoveSpring:react-native-intercom:unspecified > com.facebook.react:react-native:0.50.3
         > Could not find com.android.support:design:26.1.0.
           Searched in the following locations:
....
               file:/Users/MichaelMcKinley/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
               file:/Users/MichaelMcKinley/Development/movespring/mobile/android/sdk-manager/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
           Required by:
               MoveSpring:react-native-intercom:unspecified > io.intercom.android:intercom-sdk-base:4.1.4 > com.intercom:android-composer-gallery:1.3.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

**Comment by HilSny** [comment]
You can fix this issue by adding to android/build.gradle:

```
 maven {
          url "https://maven.google.com"
        }
```

Like so: 
```
allprojects {
    repositories {
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
          url "https://maven.google.com"
        }
    }
```

You also need to be compiling for 26 and have your build tools at 26.0.1:
