### ISSUE TITLE
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by slorber** [tinycreative/react-native-intercom#154]
I get this error on app startup on Android

Intercom React Native Error java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long

Not sure but this might be related to

```
Intercom.addEventListener(
      Intercom.Notifications.UNREAD_COUNT,
      onIntercomUnreadChange,
    );
```

Surprisingly it does not seem to break my app

**Comment by fryossi** [comment]
Related to ` Date dateSignedUpAt = new Date((long)value);` on line 234, but the value is double- ` deconstructedMap.put(key, readableMap.getDouble(key));` on line 264.

**Comment by flatsteve** [comment]
Hi all. Does anyone have any advice on this? 

I'm also running into this problem and it crashes the app for me:

      FATAL EXCEPTION: mqt_native_modules
      java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String

**Comment by abdallahnofal** [comment]
> Hi all. Does anyone have any advice on this?
> 
> I'm also running into this problem and it crashes the app for me:
> 
> ```
>   FATAL EXCEPTION: mqt_native_modules
>   java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
> ```

This problem related to the data that you send to Intercom. All what you have to do is to make sure you make all values Strings for example 

> `Intercom.registerIdentifiedUser({ userId: String(user_id) });`
