### ISSUE TITLE
Can not update Users on Android

### ISSUE THREAD

**Issue by apolishch** [tinycreative/react-native-intercom#155]
```
 Intercom.registerIdentifiedUser({userId: user.id})
      return Intercom.updateUser({
        email: user.email,
        name: user.name
      })
```

The above code works perfectly on iOS. On Android it creates a user with a userId, but the user is never updated.

Any ideas how/why this is happening and how/why to fix it?

**Comment by Borovensky** [comment]
Same here. Any updates or solutions on this?

**Comment by cmansel** [comment]
On android I've noticed that updateUser updates the name and email but sets sets them as custom attributes. This means the main email and name Intercom fields are not updated and Intercom functions which require them cannot be used.

**Comment by Rajat421** [comment]
facing the same issue any update on  this

**Comment by NirpE** [comment]
Is this library active anymore? This bug causes pretty fatal issues with the Intercom platform.
