### ISSUE TITLE
Intercom.h file not found

### ISSUE THREAD

**Issue by mrharel** [tinycreative/react-native-intercom#16]
HI,
I installed the lib and when i compile i get an error that the file `Intercom/Intercom.h` was not found. 

<img width="1275" alt="screen shot 2016-05-25 at 14 09 43" src="https://cloud.githubusercontent.com/assets/473889/15539417/93d8447c-2282-11e6-80d8-fe0f11227f59.png">

Where is this folder and file, i can't even find them in the `node_modules`

am i missing something?

**Comment by browniefed** [comment]
You need to download (either manually or use pods) and add to your project yourself. We do not ship with the library.

**Comment by browniefed** [comment]
You can follow the manual install instructions from here https://github.com/intercom/intercom-ios

**Comment by mrharel** [comment]
@browniefed thanks, that did the trick. 
It is not trivial for JS developers who has no background in mobile to handle all this integration specific stuff. 

Thanks for the help!

**Comment by af-inf** [comment]
@browniefed Thanks, how about Android? Do you have instructions there?
