### ISSUE TITLE
'custom_attributes` does not work on Android

### ISSUE THREAD

**Issue by ohtangza** [tinycreative/react-native-intercom#161]
Hello! 

### Symtom

When we call,

```
 Intercom.updateUser({
   email,
   custom_attributes: {
     custom_test: 'Testing...',
   },
});
```

The output of the above code is as follows:
<img width="377" alt="screen shot 2018-01-10 at 10 12 13 am" src="https://user-images.githubusercontent.com/1323963/34751252-c4e1a0cc-f5ee-11e7-8f9e-25b537885e9a.png">

I think the below line has some issue:

```
// https://github.com/tinycreative/react-native-intercom/blob/59d5cfe517fe0f15366343b21021f072db03dab4/android/src/main/java/com/robinpowered/react/Intercom/IntercomModule.java#L240
builder.withCustomAttributes((Map)value);
```

In the original documentation, it always uses `builder.withCustomAttribute()`. Do we have to use `.withCustomAttribute()` other than `withCustomAttributes()` do update custom_attribute?
 
### Note
- I made a pull request related to this line few months ago (#137).
- Related code : https://github.com/tinycreative/react-native-intercom/blob/db2214b592c724ef6102d18a6f26d30d937289fc/android/src/main/java/com/robinpowered/react/Intercom/IntercomModule.java#L222
- I did not test iOS yet, so I'm not sure if there is the same issue in iOS.

**Comment by fryossi** [comment]
custom_attributes works for me in both android/iOS
