### ISSUE TITLE
No known class method for selector 'logout'

### ISSUE THREAD

**Issue by isAlmogK** [tinycreative/react-native-intercom#173]
I just updated my react native intercom package (9.4) and also update react-native 

but I'm now getting the following build errors 

No known class method for selector 'logout'

No known class method for selector 'presentHelpCenter'

**Comment by browniefed** [comment]
I believe it is now reset

**Comment by isAlmogK** [comment]
@browniefed not sure I understand in my code I have 

// Clears intercom
        Intercom.reset()

**Comment by browniefed** [comment]
I think you need to update your intercom version

**Comment by isAlmogK** [comment]
@browniefed I did that followed the Manual Installation 
https://github.com/intercom/intercom-ios

and my current package is 
"react-native-intercom": "^9.4.0", 

Still getting the build error

**Comment by isAlmogK** [comment]
Got it working had to delete everything and reinstall

**Comment by evanjmg** [comment]
Reset does not log you out. I'm still logged into the old user when I login with a new user

**Comment by WALReactNative** [comment]
React native Intercom version - 10.2.0
Pod version - 4.1.9
@AlmogRnD Facing the same issue. You mentioned that you deleted everything.
I tried steps below:
- Unlinked the package.
- removed the package(using Yarn)
- Removed intercom related line from the podfile
- Installed pods
- Removed derived data.
- Cleaned the project in Xocde.
- added the package using yarn.
- Install the required pods
- Linked the packge.

I still get the same error. Could you please help me out here. Thanks.
