### ISSUE TITLE
Build error "cannot read property unread change notification of undefined" 

### ISSUE THREAD

**Issue by isAlmogK** [tinycreative/react-native-intercom#174]
Getting the following build error on iOS, I'm on the latest version of react native, this package and the intercom ios SDK. 
<img width="377" alt="screen shot 2018-02-20 at 4 29 09 pm" src="https://user-images.githubusercontent.com/169507/36408707-4658048e-165b-11e8-9936-8333c28f8436.png">

**Comment by isAlmogK** [comment]
Anyone have any ideas about this?

**Comment by Swappdevelopment** [comment]
Hey! Got the same issue and solved it. You need to do the following:

1. Follow the three steps at this link: https://github.com/intercom/intercom-ios

2. Open **Xcode** -> Right click **Libraries** and select **Add File to Project Name** -> Select RNIntercom.xcodeproj located in node_modules/react-native-intercom/iOS

3. Open **General Settings** -> **Build Phases** -> **Link Binary with Libraries** and add libRNIntercom.a

Hope this help!

**Comment by isAlmogK** [comment]
@Swappdevelopment  I did this and now I'm getting No Known class method for selector 'logout' No known class method for selector presentHelpCenter

**Comment by isAlmogK** [comment]
@Swappdevelopment I was able to fix No Known class method for selector but I'm still getting unread issue

**Comment by LucasLpr** [comment]
I have the same issue only on Android ... Working on IOS

**Comment by dylanslade** [comment]
@AlmogRnD Did you ever end up solving this?

**Comment by dylanslade** [comment]
Got it, I needed to add the `libRNIntercom.a` to the linked frameworks and Libraries section for all of my build targets and use the latest version of the iOS Intercom SDK (currently 5.0.2).

**Comment by anshul-kai** [comment]
For other looking to solve this, right-click your Libraries folder in Xcode and then "Add files to <project>". Select RNIntercom.xcodeproj from your `<project>/node_modules/react-native-intercom/iOS` folder. Then you should be able to easily add the library `libRNIntercom.a` under Build Phases > Link Binary with Libraries.

**Comment by ryanmargheriti** [comment]
The above hasn't solved this problem for me, unfortunately.

**Comment by Annihil** [comment]
For me neither, it does not seem related to a configuration problem as it builds just fine on both platform.
It's only while running jest unit tests that are importing react-native-intercom...
