### ISSUE TITLE
Android - (evaluating 'IntercomEventEmitter.UNREAD_CHANGE_NOTIFICATION')   

### ISSUE THREAD

**Issue by Swappdevelopment** [tinycreative/react-native-intercom#176]
I used to have this issue on iOS and solved it but now i'm having the same issue with Android. I'm able to remove this by adding "new IntercomPackage()" in:

```
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
          new RCTCameraPackage(), new IntercomPackage()
    );
  }

```
However my Intercom icon is not showing and i can't call any function while on iOS it's working perfectly. Any idea on how to solve this issue?

**Comment by isAlmogK** [comment]
+1

**Comment by MayeuldP** [comment]
same here for iOS
