### ISSUE TITLE
Getting No known class method for selector 'presentHelpCenter'

### ISSUE THREAD

**Issue by gidox** [tinycreative/react-native-intercom#180]
Hello everyone, I'm having problems to start the app.

![screen shot 2018-02-28 at 1 23 46 pm 2](https://user-images.githubusercontent.com/5483102/36805191-c0ca0d2c-1c8a-11e8-8305-5f4e24f9fe54.png)

I'm using Cocoapods

**Comment by HilSny** [comment]
Make sure you have the latest version the sdk. We had this issue because we were using an old version and grabbing the new one solved it.

You can grab it here: https://github.com/intercom/intercom-ios

**Comment by gidox** [comment]
resolved @HilSny  thanks

**Comment by DanielLourie** [comment]
@gidox how did you solve this?
