### ISSUE TITLE
'RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by isAlmogK** [tinycreative/react-native-intercom#181]
Getting the following error when I try to compile 

'RCTEventEmitter.h' file not found

**Comment by ericlewis** [comment]
Same here. Latest version of RN.

**Comment by isAlmogK** [comment]
I got it working, I needed to fully uninstall the current version of react-native-intercom and the ios SDK make sure it's unlinked, then I just did npm install react-native-intercom, do not link it and the pod install

**Comment by aminosman** [comment]
I was able to solve this issue by not including react-native-intercom in my pod file (if you already have it there simply remove it and rerun pod install) and I linked the library the way react native docs say to manually link a library as seen in the [https://facebook.github.io/react-native/docs/linking-libraries-ios.html](docs). Make sure you do step 3 as well. That allowed me to build again.

**Comment by russelRajitha** [comment]
still have issue. i tried all solutions. `react native version : 0.60.5`
```
/react-native/React/Modules/RCTEventEmitter.h:8:9: 'React/RCTBridge.h' file not found
/project_path/node_modules/react-native-intercom/iOS/IntercomEventEmitter.m:9:9: In file included from /project_path/node_modules/react-native-intercom/iOS/IntercomEventEmitter.m:9:
/project_path/node_modules/react-native-intercom/iOS/IntercomEventEmitter.h:12:9: In file included from /project_path/node_modules/react-native-intercom/iOS/IntercomEventEmitter.h:12:
```

**Comment by surgetom** [comment]
> still have issue. i tried all solutions. `react native version : 0.60.5`
> 
> ```
> /react-native/React/Modules/RCTEventEmitter.h:8:9: 'React/RCTBridge.h' file not found
> /project_path/node_modules/react-native-intercom/iOS/IntercomEventEmitter.m:9:9: In file included from /project_path/node_modules/react-native-intercom/iOS/IntercomEventEmitter.m:9:
> /project_path/node_modules/react-native-intercom/iOS/IntercomEventEmitter.h:12:9: In file included from /project_path/node_modules/react-native-intercom/iOS/IntercomEventEmitter.h:12:
> ```

Did you find a solution to this ?

**Comment by ghostgarrix** [comment]
@surgetom any solution?

**Comment by surgetom** [comment]
@ghostgarrix Yes! solved it!

The issue was how I did the install. (First note that I did the manuel install of Intercom.)
I was doing step 4ii wrong. 

Open "General Settings" -> "Build Phases" -> "Link Binary with Libraries" and add libRNIntercom.a

this step - needs to be done to the this file "RNIntercom.xcodeproj"

I was doing it to my root project file. 

after do a `pod install` the build from the terminal `yarn ios` not xCode.

**Comment by ghostgarrix** [comment]
@surgetom thank you man, turns out i figured it out by reseting and doing the install steps again (as they're shown in the github i didn't see ur answer at the moment so couldn't try it), but still, thank you. i'm now heading to face android errors haha

**Comment by surgetom** [comment]
@ghostgarrix, Android had a handful of issues, but I was able to resolved them with Google searches. But if you get stuck let me know.

**Comment by ghostgarrix** [comment]
@surgetom it's done! Android went pretty fast actually, just had to upgarde gradle plugin version. Thanks again man.

**Comment by luansingjavier** [comment]
This work for me on iOS
1. npm install react-native-intercom
2. npx react-native link react-native-intercom
3. cd ios and pod install
