### ISSUE TITLE
Could not resolve all dependencies issue 

### ISSUE THREAD

**Issue by dannstuff** [tinycreative/react-native-intercom#182]
Hi, I've tried to set up your package using the installation guide on yours and intercoms website. Upon running the app to see if it is working, im getting a lot of errors about dependencies. I think the individual dependency its complaining about it - com.android.support:appcompat-v7:27.0.2.

here is the full error message (sorry about bad quality image) 
![error](https://user-images.githubusercontent.com/15126482/37036713-65017274-2148-11e8-9061-8684727e733b.png)

any ideas? Thanks, 
Dan.

**Comment by KemikalGeneral** [comment]
Is there anyone to answer this? I have this problem also after upgrading to v10.2.0
