### ISSUE TITLE
Intercom UI is broken (doesn't show background)

### ISSUE THREAD

**Issue by nirpeled** [tinycreative/react-native-intercom#184]
Hey everyone,

I'm using this package for a while now and recently I'm experiencing some UI issues (see screenshots).
I recently upgraded to Expo 25 that is bundled with React Native 0.52 - any chance it's related?

**Intercom is OFF:**
![img_1217](https://user-images.githubusercontent.com/6830805/38172446-54df20c2-35b5-11e8-99c2-8cdf7ec4fbb9.PNG)

**Intercom is ON:**
![img_1218](https://user-images.githubusercontent.com/6830805/38172447-550415b2-35b5-11e8-8166-dbcd23bfea78.PNG)

**Intercom's conversations UI:**
![img_1219](https://user-images.githubusercontent.com/6830805/38172448-552589c2-35b5-11e8-9779-f78f65fbabff.PNG)

Thanks,

Nir

**Comment by weslley39** [comment]
I'm with the same problem :(

**Comment by nirpeled** [comment]
@weslley39 what version of react-native-intercom and react-native are you using?

**Comment by weslley39** [comment]
`"react-native-intercom": "10.2.0"`
`"react": "16.2.0"`
`expo: sdk 25`

**Comment by nirpeled** [comment]
Same as I got... I'm thinking about downgrading, WDYT?

**Comment by weslley39** [comment]
I will try to update to the latest release of expo sdk (26), and see if it will work. I post the details later

**Comment by weslley39** [comment]
With the new Expo Sdk the problem persists.

react-native: 0.54.2
react: 16.3.0-alpha.1
react-native-intercom: 10.2.0

**Comment by nirpeled** [comment]
Any chance it's related to the Intercom package that **react-native-intercom** is wrapping?

**Comment by weslley39** [comment]
Update: This bug only happens on iOS, Android is working fine!

**Comment by nirpeled** [comment]
Anyone...? Thanks :)

**Comment by weslley39** [comment]
I decided to get all my expo ios detached project and throw away, start one new structure from scratch with `ext init`, and then do the detach with `exp detach`, copy all the new generated files to my current project and install all the dependencies with `react-native link`. After all this process, for some reason, that unfortunately, I don't know, the intercom just worked, with the background white.

**Comment by nirpeled** [comment]
@weslley39 Wow that's pretty amazing... 
Did you have other integrations to add back?
In my case I do have a few but I might give it a try - thanks!

**Comment by weslley39** [comment]
I have facebook sdk, one signal, intercom and react-native-splash-screen.
