### ISSUE TITLE
error: package com.robinpowered.react.Intercom does not exist

### ISSUE THREAD

**Issue by nirpeled** [tinycreative/react-native-intercom#186]
Hey everyone,

I've been using this package for a while (for an iOS version) now and everything works great! I recently started working on an Android version - went through all the steps, made all changes required but then I get this error:

![image](https://user-images.githubusercontent.com/6830805/38541333-717e0556-3ca7-11e8-9e25-ce0608f0d3b5.png)

What am I missing here?

**I'm using:**
expo: 25.0.0
react: 16.2.0
react-native: 0.52
react-native-intercom: 10.2.0

Thanks 😃

**Comment by nirpeled** [comment]
Anyone...?

**Comment by ryansunaidi** [comment]
Hi I got that issue too, and i start using Intercom web view https://github.com/donovantc/react-native-intercom-webview
now it works on my app

**Comment by nirpeled** [comment]
Thanks @ryansunaidi - I'll check it out 😄

**Comment by The0racle** [comment]
Has anyone figured this out? Is there a step missing from the documentation or this library will no longer work?

**Comment by nirpeled** [comment]
I ended up using a WebView to show it on web-mode, it's a little bit hacky because you'll need to pass some injected javascript with all your uid and user info + pass an onHide callback so it will auto-close the WebView when the X is pressed - but this looks and works like magic 😄 

Here are some screenshots on how it looks:

<img width="258" alt="screen shot 2018-06-02 at 9 51 13" src="https://user-images.githubusercontent.com/6830805/40871767-b30a3680-664a-11e8-9e06-feae86f0eca4.png">
<img width="258" alt="screen shot 2018-06-02 at 9 51 32" src="https://user-images.githubusercontent.com/6830805/40871768-b32b6490-664a-11e8-8ade-6eb9c181a51a.png">
<img width="258" alt="screen shot 2018-06-02 at 9 51 41" src="https://user-images.githubusercontent.com/6830805/40871769-b34c1fb4-664a-11e8-908e-5e65ed76b372.png">

**Comment by ValterSantosMatos** [comment]
@nirpeled I had the same, and the reason was that I didn't link the package, so I was missing `compile project(':react-native-intercom')` in the dependencies.
