### ISSUE TITLE
Status bar conflict between Intercom and React Native app

### ISSUE THREAD

**Issue by TheAlmightyBob** [tinycreative/react-native-intercom#187]
Our app normally has a white status bar with black text:
![image](https://user-images.githubusercontent.com/7707864/38708378-dfd71956-3e6a-11e8-813b-d73f206866b3.png)

When Intercom messenger is displayed, it has a black status bar with white text:
![image](https://user-images.githubusercontent.com/7707864/38708424-03c29624-3e6b-11e8-9aa2-339b643139f0.png)

If the app is then resized (via rotation or iPad split-screen mode) and Intercom is dismissed, the status bar returns to white but keeps the white text from Intercom, thus becoming invisible:
![image](https://user-images.githubusercontent.com/7707864/38708446-28f86ab8-3e6b-11e8-9f7b-f6955b4fc582.png)

This is with `UIViewControllerBasedStatusBarAppearance` set to the RN-recommended value of `false`. If it is set to `true`, the text color never changes in Intercom... so the rest of our app remains fine, but the status bar text is invisible while Intercom is displayed.

**Comment by geldarhb** [comment]
Happening on my end as well. Status bar changes are being ignored once Intercom launcher is displayed.
@TheAlmightyBob did you find any solution for that?

**Comment by TheAlmightyBob** [comment]
@geldarhb We have not found a solution.

**Comment by tobiastornros** [comment]
@TheAlmightyBob Please provide your solution.

**Comment by TheAlmightyBob** [comment]
@tobiastornros I think you misread. I do not have a solution.

**Comment by tobiastornros** [comment]
@TheAlmightyBob haha yeah sorry! 💃

**Comment by TheAlmightyBob** [comment]
@browniefed This is still an issue. Why was this closed?

**Comment by browniefed** [comment]
Send a PR happy to accept it.

**Comment by browniefed** [comment]
That being said I don't think there is a solution as Intercom is its own beast with limited control over how it displays.
