### ISSUE TITLE
Unable to find explicit activity class {com.example.dev/io.intercom.android.sdk.activities.IntercomMessengerActivity}

### ISSUE THREAD

**Issue by maartenschumacher** [tinycreative/react-native-intercom#190]
I get this runtime error when trying to launch the intercom messenger:

```
Unable to find explicit activity class {com.example.dev/io.intercom.android.sdk.activities.IntercomMessengerActivity}; have you declared this activity in your AndroidManifest.xml?
```

If I declare the activity in the manifest explicitly it works fine, but then it crashes on the next activity, like IntercomArticleActivity. Is there a way not to have to declare these activities explicitly?

**Comment by hiradary** [comment]
same problem with react native navigation.
```
Unable to find explicit activity class {com.baman/com.reactnativenavigation.controllers.NavigationActivity}; 
have you declared this activity in your AndroidManifest.xml?
```

**Comment by ganesh-papola** [comment]
any solution or issue closed for no reason?

**Comment by mukesh-aramark** [comment]
Error: android.content.ActivityNotFoundException:
 Unable to find explicit activity class {com.goodunclecore5/io.intercom.android.sdk.activities.IntercomMessengerActivity};
 have you declared this activity in your AndroidManifest.xml?


Please provide solution for it.
