### ISSUE TITLE
iOS - Warning: Module IntercomEventEmitter requires main queue setup since it overrides `constantsToExport`

### ISSUE THREAD

**Issue by aarondail** [tinycreative/react-native-intercom#191]
This is a warning you get sometimes during development.  AFAIK it doesn't cause a problem, but it is also simple to fix (again, AFAIK).

<img width="300" alt="ss123" src="https://user-images.githubusercontent.com/3768353/39217072-2c2ded22-47d3-11e8-9c65-a26288283eb6.png">

You just have to define a method called `requiresMainQueueSetup` and have it return true in IntercomEventEmitter.

Here is an example:
https://github.com/airbnb/lottie-react-native/pull/226/files

**Comment by thaapasa** [comment]
I made a pull request for this based on the @aarondail's suggestion. Please merge :)
