### ISSUE TITLE
'Intercom/Intercom.h' file not found

### ISSUE THREAD

**Issue by onlydave** [tinycreative/react-native-intercom#198]
`app/node_modules/react-native-intercom/iOS/IntercomUserAttributesBuilder.m:10:9: 'Intercom/Intercom.h' file not found`

react-native-intercom: 11.0.0
intercom-ios: 5.0.2

Tried every combination of Search Paths, adding and removing Libraries and the framework, react-native link but can't get the app to build. Worked with react-native-intercom 10.2.0 and an older version of the iOS SDK

**Comment by HilSny** [comment]
Yeah this looks like a bug on RNIntercom. According to the IOS docs it is now `import Intercom` instead of `import Intercom/Intercom.h` 

See here: https://developers.intercom.com/docs/ios-installation

It must be a change with the new sdk

**Comment by onlydave** [comment]
Looking at it with fresh eyes again this morning I think it has to do with these changes to the framework search paths for users like myself that installed the Intercom SDK manually in the ios folder

[https://github.com/tinycreative/react-native-intercom/compare/v10.2.0...master#diff-a4523dff5b274217f03e1a5b8856e750](https://github.com/tinycreative/react-native-intercom/compare/v10.2.0...master#diff-a4523dff5b274217f03e1a5b8856e750)

**Comment by wangsha** [comment]
Current setting assume you install intercom-ios via cocapod or manually.
If you use **carthage**, add `$(SRCROOT)/../../../ios/Carthage/Build/iOS` to **RNIntercom.xcodeproj**'s framework search path.

Before:
<img width="602" alt="screen shot 2018-05-09 at 11 08 20 pm" src="https://user-images.githubusercontent.com/221029/39823081-cc4edeee-53de-11e8-8b8b-0e1898b15904.png">

After:
<img width="974" alt="screen shot 2018-05-09 at 11 08 42 pm" src="https://user-images.githubusercontent.com/221029/39823097-d676594c-53de-11e8-88b0-bf80a7139940.png">

**Comment by onlydave** [comment]
Was installed manually but still couldn't get it to run correctly. Our app is in production a while now with a fair few dependencies so it would be hard to pin down but in the end, I moved everything to use cocoapods.

It'd be worth someone with a simpler setup or just trying a new app and manual install route, I might be able to check this but can't promise I'll get a chance soon

**Comment by michaelknoch** [comment]
check this https://github.com/tinycreative/react-native-intercom/pull/203
another workaround would be symlinking the carthage frameworks folder to the included carthage dir

**Comment by RossKinsella** [comment]
I resolved this by locking my `package.json` react-native-intercom to 10.2.0 (It was on 11.0.0 after `yarn install react-native-intercom` and then manually installing ios SDK 4.1.9

**Comment by vovanmozg** [comment]
It helped me https://github.com/intercom/intercom-ios#manual-installation

**Comment by darshan-raj** [comment]
Any solution for this problem? I'm facing the same issue. I did a manual installation as described here [https://developers.intercom.com/docs/ios-installation#section-option-3-install-intercom-manually](https://developers.intercom.com/docs/ios-installation#section-option-3-install-intercom-manually) and tried other options too but to no avail.
intercom-ios version is 5.0.4

**Comment by sndkd** [comment]
'Intercom/Intercom.h' file not found, I followed the manual installation without using cocoapods or carthage. Intercom.framework is at the root level of the project and library is added manually. Can anyone help, what could be the issue

**Comment by ryanm2000** [comment]
Also having this problem. New to the ecosystem so its very hard for me to help track down

**Comment by gordysc** [comment]
I also struggled with this.  Downgrading to 10.2 fixed my problems.

**Comment by beausmith** [comment]
Based upon the advice in this thread (and others) I wrote the install steps I took to get `react-native-intercom` working:
https://github.com/tinycreative/react-native-intercom/pull/215
https://github.com/tinycreative/react-native-intercom/pull/218

Thanks, y'all.

**Comment by harrisrobin** [comment]
Following:
https://github.com/intercom/intercom-ios#manual-installation

helped me solve the problem without downgrading.

**Comment by aaroncraigongithub** [comment]
I'm seeing this still with the latest version.  Is `react-native link` ever going to be a thing for this lib?

**Comment by browniefed** [comment]
No.

**Comment by aaroncraigongithub** [comment]
Wow seriously?  Sort of speechless at this answer, but I guess we don't need Intercom all that much, now that I think about.

**Comment by browniefed** [comment]
It already works with react-native link, it is a decision to not ship intercom with the JavaScript library due to issues with how people use the library with native dependency stuff like Pods, etc. There are pretty straight forward instructions on adding the library from the Intercom folk.

I do not use this library. I let people submit PRs for stuff and merge what seems correct.

**Comment by harrisrobin** [comment]
@aaroncraigongithub this package has nothing to do with Intercom. If you need `react-native link` so badly then why not try to hire someone to do it or do it yourself?

Several people have managed to get it working by fixing it to a specific version until we wait for a fix on the new one. I got it working without react-native link and use cocoapods which i actually find much better.

Good luck!

**Comment by aaroncraigongithub** [comment]
Sorry, I was reacting to the single word "No" response and the closing of the issue with no further comment, which seems to me a poor way to respond to a legitimate request.

Since most react native packages offer a simple install mechanism with `react-native link`, it seems entirely reasonable an expectation to have of this repo.  

An alternative response to "No [closes issue]" could also have been "I don't have any plans to implement this due to lack of time, but I am totally open to any PRs", or "I don't think this is the right direction for this package, so I won't be implementing it, but feel free to fork this repo and do as you please" or whatever.

I admit I thought this was maintained by Intercom (and find it a little unsettling that they don't invest in this project themselves), so I do apologize for any offense my ignorance may have caused.
