### ISSUE TITLE
Android - Intercom.Notifications.UNREAD_COUNT of undefined

### ISSUE THREAD

**Issue by LcsLpr** [tinycreative/react-native-intercom#201]
Intercom.addEventListener(Intercom.Notifications.UNREAD_COUNT, this.onUnreadChange)

This eventListener is working very well on IOS, however it makes crashing the application on Android...
It says that UNREAD_COUNT is undefined...

Something to fix this ?

**Comment by LcsLpr** [comment]
Any work around ?

**Comment by Dallas62** [comment]
Looks like an error when you import the Android / iOS library.

I had it on iOS because I didn't import Intercom's pod.

**Comment by LcsLpr** [comment]
The imports are well done. Intercom is working very well, it is only this feature who is working on IOS and not on Android. I tried on an empty project as well. Same thing

> import com.robinpowered.react.Intercom.IntercomPackage;
> import io.intercom.android.sdk.Intercom;
