### ISSUE TITLE
Argument list too long: recursive header expansion ...

### ISSUE THREAD

**Issue by elnygren** [tinycreative/react-native-intercom#202]
As was suggested in comments of PR https://github.com/tinycreative/react-native-intercom/pull/163

> Could we improve this by being more specific?
> `$(SRCROOT)/../../../ios/Pods/Intercom/`

This library is not working for me not with manual install nor with pod based install (`pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'`) due to this error.

Is there some specific reason why this library has to search through everything in Pods? 

Edit: btw. the problem, at least for me, is definitely when React is installed in Pods dir, there are just too many files to go through recursively as React brings a little something called node_modules into the play :)

**Comment by afilp** [comment]
Is there any solution as I am also stuck with this, thanks!

**Comment by MayeuldP** [comment]
Same here, it doesn t work anymore !

**Comment by mistenkt** [comment]
Same here.

**Comment by patelbrinda** [comment]
I am facing the same issue, Anyone can Please suggest something !

**Comment by nicubarbaros** [comment]
Still the same problem ((

**Comment by mistenkt** [comment]
Works fine on a fresh project with manual install, but as soon as i try to integrate this into an existing project that uses pods we get this issue.

Edit: Changing the Framework Search Paths in RNIntercom.xcodeproj fixes it.

Change this:

```
FRAMEWORK_SEARCH_PATHS = (
    $(inherited)",
    "~/Documents/Intercom",
    "$(SRCROOT)/../../../ios/**",
    "$(SRCROOT)/../../../ios/Pods/**",
    "$(SRCROOT)/../../../ios/Carthage/Build/**",
);
```

to this:

```
FRAMEWORK_SEARCH_PATHS = (
    $(inherited)",
    "$(SRCROOT)/../../../ios",
);
```

**Comment by declanelcocks** [comment]
Any update to this? Same issue as @mistenkt, have to run `rm -rf ios/build` virtually every time.

**Comment by kafaichoi** [comment]
For those manual install this library, you can try to set `FRAMEWORK_SEARCH_PATHS` in `RNIntercom.xcodeproj` 
 as `$(SRCROOT)/../Intercom.framework` and delete others like `"$(SRCROOT)/../../../ios/**"`

**Comment by VicFrolov** [comment]
A temporary solution is doing a lot of clearing and fresh building.
1) `rm -rf node_modules`
2) `rm -rf ios/build`
3) `watchman watch-del-all`
4) `npm install`
5) `npm start -- --reset-cache`
6) Open Xcode and hit `cmd + shift + k`
7) While still in Xcode, after 6 is done, `cmd + shift + option + k`, and confirm clean.

After doing this, I am able to successfully build/deploy. But this issue arises far too frequently.

**Comment by tomasgarba** [comment]
This issue is caused by this PR https://github.com/tinycreative/react-native-intercom/commit/7d80a0ce39554654d1f7560669dd0f51329f0118
