### ISSUE TITLE
When using displayHelpCenter() the help center window appears and then immediately dismisses

### ISSUE THREAD

**Issue by jayporta** [tinycreative/react-native-intercom#209]
Intercom.displayHelpCenter() doesn't work as expected. 

Intercom.displayMessageComposer() is fine though.

Upgrading is not an option because v11 with the latest Intercom framework results in <Intercom/Intercom.h> file not found errors (I've already seen the issues thread for that).

Could I be missing something? There doesn't seem to be any documentation here for displayMessageComposer()

**Comment by RostislavCn** [comment]
@jayporta just make sure Help Center is turned on in the intercom app settings :)

**Comment by jayporta** [comment]
Thanks @RostislavCn. I passed that information up the chain and it's fixed now.

**Comment by usrbowe** [comment]
If anyone looking where this settings is:
**Articles** > **Help Center** > Right upper corner: `Turn On Help Center`
`https://app.intercom.io/a/apps/APP_ID/articles/site/settings`
