### ISSUE TITLE
There is a problem starting this conversation

### ISSUE THREAD

**Issue by edo1493** [tinycreative/react-native-intercom#21]
Hi, 
I am trying to open the message composer, but when I do, I get this. 
I was wondering if anyone had stumbled across this problem or it was something related to what product has been bought on Intercom. I have just found out that only the "Support" product works on mobile. 

Thanks

**Comment by browniefed** [comment]
It doesn't appear that you posted an error message at all

**Comment by edo1493** [comment]
Yes, Intercom replied saying I have to register the user before starting a conversation (my bad).

I am trying to display the message composer in this way: 

`Intercom.setVisibility("VISIBLE");
 Intercom.setPreviewPosition("BOTTOM_RIGHT");
 Intercom.displayMessageComposer();
`

I don't see anything though. 
Thanks

**Comment by edo1493** [comment]
Everything works fine, I should have read the doc. No problem at all. :)
