### ISSUE TITLE
'Intercom/Intercom.h' not found

### ISSUE THREAD

**Issue by akyker20** [tinycreative/react-native-intercom#213]
I am trying to manually install intercom-ios. I followed the steps here https://github.com/intercom/intercom-ios, yet I still get this:

...../IntercomUserAttributesBuilder.m:10:9: 'Intercom/Intercom.h' file not found

<img width="928" alt="screen shot 2018-07-09 at 3 57 26 pm" src="https://user-images.githubusercontent.com/5449431/42472857-cce2f0ac-8390-11e8-961a-e055ea5ae5ab.png">

Most of the related issues just link to the intercom-ios repository... I followed those steps already.

**Comment by epologee** [comment]
I'm noticing the README.md tells us to import `"Intercom/intercom.h"` with a lowercase `i`. That looks like handwritten code that's not been checked by the compiler.

Changing the import to the newer angular bracket syntax worked for me, including an uppercase `i`:

    #import <Intercom/Intercom.h>

**Comment by welsh11** [comment]
I had the same problem.

First, make sure you install the Intercom framework code as per the 'Manual Installation' instruction here:

[Intercom IOS](https://github.com/intercom/intercom-ios)

Once you've done that, it seems that the `FrameworkSearchPaths` setting in the `RNIntercom` project (in the Libraries folder) of the Xcode project makes some assumptions about the location of the `Intercom.framework` file.

I removed the reference to the Documents directory and the pod directory and added 

`$(SRCROOT)/../../../ios`   (recursive)

underneath the bit that says

`$(inherited)`

In my case I have the Intercom framework file in the root of the `iOS` folder in my RN project.  You would have to adjust it if it's in a different place in your project.

Hope that helps

**Comment by akyker20** [comment]
@welsh11 That was what ended up being the problem for me. Your solution fixed it.
