### ISSUE TITLE
Crash in android IntercomClient.js

### ISSUE THREAD

**Issue by DavidPineda** [tinycreative/react-native-intercom#217]
When I updated the targetVersion of my app to 26 te react-native-intercom it broke and the error output tells me this._pushIntercomChain (method is undefined, if I comment that line and execute directly the promise the app returns to normal operation, but I do not see why this is not recognized in this class.

this work.

`
new Promise((resolve, reject) => {
      IntercomWrapper.registerIdentifiedUser(options, (error) => {
        if (error) {
          reject(error);
        } else {
          resolve();
        }
      });
    })
`

this not work
`
return this._pushIntercomChain(
   () =>
     new Promise((resolve, reject) => {
       IntercomWrapper.registerIdentifiedUser(options, (error) => {
         if (error) {
           reject(error);
         } else {
           resolve();
         }
       });
     }),
 );
`

**Comment by fyodoriv** [comment]
I had similar error when calling `IntercomWrapper.registerIdentifiedUser` in redux-saga with `call`. Resolved by extracting the function with this call and calling it from redux-saga
