### ISSUE TITLE
How to change Icon Push Notication

### ISSUE THREAD

**Issue by ththugues44** [tinycreative/react-native-intercom#221]
Hello
Please , how to change Icon Push Notication by my Icon Launcher App ?

Thanks for your reply

**Comment by mathieumg** [comment]
https://developers.intercom.com/installing-intercom/docs/android-fcm-push-notifications#section-step-4-setting-your-fcm-icon

**Comment by darbaoui** [comment]
@mathieumg 
any suggestion 
https://github.com/tinycreative/react-native-intercom/issues/259#issuecomment-575125406
