### ISSUE TITLE
Code signing "Intercom.framework" failed [IOS publish]

### ISSUE THREAD

**Issue by nicubarbaros** [tinycreative/react-native-intercom#224]
I get this error when trying to publish the app to the app store. 

Followd all steps in the documentations (multiple times). Checked my certificates and profiles.

Any help will be appreciated 

 "react-native": "^0.57.1",
 "react-native-intercom": "^12.1.0",

I could provide logs or any more information

**Comment by dumbest** [comment]
How did you manage to solve this?

**Comment by ghost** [comment]
Were you able to solve this?

**Comment by dihan** [comment]
Anyone? How did you get past it?

**Edit**:

**I missed a step**

Create a new "Run Script Phase" in your app’s target’s "Build Phases" and paste the following snippet in the script text field:

 bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Intercom.framework/strip-frameworks.sh"

This step is required to work around an App Store submission bug when archiving universal binaries.

https://github.com/intercom/intercom-ios


This fixed the issue
