### ISSUE TITLE
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'

### ISSUE THREAD

**Issue by nerboda** [tinycreative/react-native-intercom#229]
Need to replace 'compile' with 'implementation' in build.gradle file so gradle stops throwing build warning - http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by dani-mp** [comment]
Hi, @nerboda. I'm not an Android expert, so I was wondering if the change is as easy as set `implementation project(':react-native-intercom')` instead of `compile project(':react-native-intercom')`. Is this correct? Thanks!

**Comment by nerboda** [comment]
@danielmartinprieto correct, you can see the change I made here https://github.com/tinycreative/react-native-intercom/pull/230/files
