### ISSUE TITLE
Intercom opens with a default theme instead of custom one on first time open

### ISSUE THREAD

**Issue by iagormoraes** [tinycreative/react-native-intercom#232]
The Intercom is opening with a default color theme and no header texts on first Intercom open. The expected behavior is to show the custom theme color and texts right on the first instance open. 

```JS
//Example call
await Intercom.registerIdentifiedUser({ userId: user.userId });
await Intercom.updateUser({
            email: user.email,
            name: user.fullName,
            phone: user.phone
});
await Intercom.displayMessenger();
```

**Comment by iagormoraes** [comment]
Just by calling ```await Intercom.registerUnidentifiedUser();``` on app start do the trick.

**Comment by aibrahim3546** [comment]
@iagormoraes But this one create a anonymus user on the intercom user list. are they better way?

**Comment by iagormoraes** [comment]
> @iagormoraes But this one create a anonymus user on the intercom user list. are they better way?

@aibrahim3546 At the moment I only know this way to get the theme from intercom settings, I know this is just a workaround, maybe the developers from intercom SDK or the other maintainers from this repo can have a better solution.

**Comment by aibrahim3546** [comment]
@iagormoraes I found a solution for this. You can just call the `registerIdentifiedUser({ userId: user.userId })` twice:

e.g: 
```
Intercom.registerIdentifiedUser({ userId: user.userId }).then(() => {
  Intercom.registerIdentifiedUser({ userId: user.userId })
  .....
})

```
