### ISSUE TITLE
Messenger not shown on iOS when app is launched from not running state via push notification

### ISSUE THREAD

**Issue by drew-r** [tinycreative/react-native-intercom#236]
On iOS, the intercom messenger will not show when the app is not running and is launched via a push notification.
The messenger is correctly displayed when a PN is opened and the app is in the background.

On Android, the messenger is correctly displayed when a PN is opened in both scenarios.

`intercom-ios` docs state this is taken care of automatically and within `react-native-intercom` the method `handlePushMessage` is stubbed in `IntercomWrapper.m`.
Perhaps intercom's swizzled methods are kicking in before RN has finished initialising?

I'm going to try disabling `IntercomAutoIntegratePushNotifications` in Info.plist and handling the PN manually to see what happens.

Ideally, would be able to call `Intercom.handlePushNotification` from iOS to handle the payload in launchOptions when the app is good and ready.

**Comment by rajputav** [comment]
hi! I believe this is fixed in https://github.com/intercom/intercom-ios/releases/tag/5.1.10
