### ISSUE TITLE
Build failed with intercom-android v5.1.6

### ISSUE THREAD

**Issue by forsen** [tinycreative/react-native-intercom#238]
react-native-intercom depends on `io.intercom.android:intercom-sdk-base:5.+`. A few hours ago version 5.1.6 of intercom-android was released, including a bump of appCompat-v7 from 27.x to 28. In each android project all dependencies have to be built with the same appCompat version. 

It is recommended to use the same versions as RN does, and latest RN is currently using this: 

        buildToolsVersion = "27.0.3"
        compileSdkVersion = 27
        supportLibVersion = "27.1.1"

intercom-android should be pinned to v5.1.5 as long as RN still use 27.x as build/compile/supportLib version.

**Comment by The0racle** [comment]
I'm having the same issue. Did you find a work around for that?

**Comment by pushpush** [comment]
My fix. 
FIle - android/build.gradle
```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            configurations.all {
                resolutionStrategy.force 'io.intercom.android:intercom-sdk-base:5.1.5'
            }
        }
    }
}
```

**Comment by vbvxx** [comment]
new intercom sdk (5.1.6) is using android 28 (reason to fix the version to 5.1.5 as mentioned by pushpush)

**Comment by TareqElMasriDev** [comment]
@pushpush Man, you just saved my weekend, you're a hero! Thanks a lot!

**Comment by mrikirill** [comment]
For expokit, this helped me:
android/build.gradle
```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            configurations.all {
                resolutionStrategy.force 'io.intercom.android:intercom-sdk-base:5.1.5'
                resolutionStrategy.force 'com.android.support:recyclerview-v7:27.1.1'
            }
        }
    }
}
```

**Comment by mathieumg** [comment]
Had to use @pushpush 's workaround but it seems fixed now, removed it and got a green build!

Edit: Ugh, seems like it was only working for the debug build. :(

**Comment by mathieumg** [comment]
React-Native 0.58 (currently in RC2) finally bumps to SDK 28: https://github.com/facebook/react-native/commit/8e39451512b6c61e97c44b8c3091d97d62027fec
