### ISSUE TITLE
Recommended version? 12.x?

### ISSUE THREAD

**Issue by agrass** [tinycreative/react-native-intercom#244]
Hi, In the readme says that recommend installing the 10.2.0 version instead 11.x.  What about 12.x? Anyone is using 12.X in production??

Best

**Comment by vongohren** [comment]
Thanks for asking, because that is very confusing :D

**Comment by MayeuldP** [comment]
Same here, I'm lost about which versions we should use :/

**Comment by vongohren** [comment]
I can confirm that the newest works well! I have not had any troubles

**Comment by browniefed** [comment]
Removed from Readme. Just use latest.
There was a difference for which version of Intercom people were supporting, etc.
No longer necessary to recommend older versions.

**Comment by agrass** [comment]
Ok, thanks!
