### ISSUE TITLE
Build Failed Generated APK Release

### ISSUE THREAD

**Issue by ththugues44** [tinycreative/react-native-intercom#246]
Hello
I see error when i build apk release :
`
> Task :app:bundleReleaseJsAndAssets
Scanning folders for symlinks in J:\Projet\foongon\react native\Entreprise\Katika\node_modules (108ms)
Scanning folders for symlinks in J:\Projet\foongon\react native\Entreprise\Katika\node_modules (131ms)
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: Writing bundle output to: J:\Projet\foongon\react native\Entreprise\Katika\android\app\build\intermediates\assets\release\index.android.bundle
bundle: Done writing bundle output
bundle: Copying 66 asset files
bundle: Done copying assets

> Task :app:generateBundledResourcesHashRelease
3d1fca80782fac0db25794f7a92901fe4e6b2f7cbda286426116f9fe371c3559

C:\Users\BRAVE\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\37f0970dffb3014c2eb0bedc86eceb26\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

J:\Projet\foongon\react native\Entreprise\Katika\node_modules\react-native-intercom\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

C:\Users\BRAVE\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\37f0970dffb3014c2eb0bedc86eceb26\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/fontVariationSettings not found.

C:\Users\BRAVE\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\37f0970dffb3014c2eb0bedc86eceb26\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/ttcIndex not found.

error: failed linking references.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-intercom:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 10s
487 actionable tasks: 13 executed, 474 up-to-date

**My Build.gradle  is :**

`
apply plugin: "com.android.application"
apply plugin: "io.fabric"

import com.android.build.OutputFile
import groovy.json.JsonSlurper

def getVersionName() {
    def inputFile = new File("../package.json")
    def packageJson = new JsonSlurper().parseText(inputFile.text)
    return packageJson["version"]
}

def getVersionCode() {
    def versionName = getVersionName()
    def versionCode = versionName.replace('.', '').toInteger()
    return versionCode
}

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    bundleInRelease        : true,
    resourcesDirRelease   : "src/release/res"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
//def enableSeparateBuildPerCPUArchitecture = false //  reduire taille fichier release si a true
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
//def enableProguardInReleaseBuilds = false // a true pour reduire la taille du fichier
def enableProguardInReleaseBuilds = false
def generatedVersionName = getVersionName()
def generatedVersionCode = getVersionCode()
android {
    compileSdkVersion 28
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.katika"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode generatedVersionCode
        versionName generatedVersionName
		multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

	configurations.all {
	   resolutionStrategy {
		   //force 'com.android.support:design:27.0.2'
		   //force 'com.android.support:support-v4:27.0.2'
		  // force 'com.android.support:appcompat-v7:27.0.2'
	   }
	   resolutionStrategy.eachDependency { details ->
               def requested = details.requested
               if (requested.group == 'com.android.support') {
                   if (!requested.name.startsWith("multidex")) {
                       details.useVersion '27.1.1'
                   }
               }
           }
	}

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {

        releaseStaging  {
           // Note: CodePush updates should not be tested in Debug mode as they are overriden by the RN packager. However, because CodePush checks for updates in all modes, we must supply a key.
           buildConfigField "String", "CODEPUSH_KEY", "faL7X3moj_JLQKAlp50URu5ClTplSkLBgQZrQ"
           // Note: It is a good idea to provide matchingFallbacks for the new buildType you create to prevent build issues
            // Add the following line if not already there
            matchingFallbacks = ['release']

       }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
			signingConfig signingConfigs.release
            //buildConfigField "String", "CODEPUSH_KEY", "bySq16a9P0d2pIdf9ZZvyaRJbzcOSJ8Sg7bHX"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-sound')
    compile project(':react-native-push-notification')
    compile project(':react-native-device-info')
    compile project(':amazon-cognito-identity-js')
    compile project(':react-native-vector-icons')
    compile project(':react-native-android-library-freshchat-sdk')
    compile project(':@aws-amplify/pushnotification')
    implementation 'com.android.support:multidex:1.0.3'
    compile project(':react-native-intercom')
    compile project(':appcenter-push')
    compile project(':appcenter-crashes')
    compile project(':appcenter-analytics')
    compile project(':appcenter')
    compile project(':react-native-appstore-version-checker')
    compile project(':react-native-version-check')
    compile project(':react-native-code-push')
    compile project(':react-native-firebase')
    compile project(':react-native-background-timer')
    compile project(':react-native-facebook-account-kit')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:27.1.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
	compile project(':react-native-android-library-freshchat-sdk')
	compile 'com.github.freshdesk:freshchat-android:1.0.0'
	compile 'com.firebase:firebase-jobdispatcher:0.7.0'

    //compile project(':reactnativenotifications')

    implementation project(':react-native-firebase')
    apply plugin: 'com.google.gms.google-services'
    com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

// Firebase dependencies
//implementation "com.google.android.gms:play-services-base:15.0.1"
implementation "com.google.firebase:firebase-core:16.0.1"
implementation "com.google.firebase:firebase-functions:16.0.1"
implementation 'com.google.firebase:firebase-messaging:17.1.0'
implementation 'me.leolin:ShortcutBadger:1.1.21@aar' // <-- Add this line if you wish to use badge on Android
implementation "com.google.firebase:firebase-firestore:17.0.2"

implementation('com.crashlytics.sdk.android:crashlytics:2.9.4@aar') {
    transitive = true
  }
  compile 'io.intercom.android:intercom-sdk-fcm:5.+'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

`

Please what is solution ?`

**Comment by maxired** [comment]
Hey @noellaby .  I am facing a similar issue. Did you found a solution ? 

edit: seem linked to https://github.com/tinycreative/react-native-intercom/issues/238

**Comment by mtford90** [comment]
Also facing this. I had to downgrade to v10 from over a year ago.

**Comment by tomhicks** [comment]
I'm not a gradle expert in any way, shape or form, but I managed to hack mine around to get it to work. I think I used build tools 28, or something.

Not sure if posting my gradle file might help?

**Comment by spacewinds** [comment]
Yo, 
I fixed this by adding explicit version config in android/build.gradle:
````
buildscript {
ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }

````
If you are using different SDK - just replace version here.
