### ISSUE TITLE
Support new Intercom iOS SDK (v5.1) (or 5.1.10)

### ISSUE THREAD

**Issue by sheydarezaee** [tinycreative/react-native-intercom#247]
Hii
Some of the Intercom features like using the Article Inserter app in manual messages does not work with the current latest intercom-ios sdk (5.0) that is plugged in here. I need the latest sdk v5.1 (or more specifically 5.1.10) to be able to use those features on iOS, as per Intercom specialists recommended.
Can you please update ASAP?

This is the version I am using in the mobile app: "react-native-intercom": "^12.3.0"
https://www.intercom.com/help/apps-in-intercom/messenger-apps/article-inserter-proactively-share-articles-at-the-right-time

Thanks,
Sheyda

**Comment by sheydarezaee** [comment]
Some of the Intercom features like using the Article Inserter app in manual messages does not work with the current latest intercom-ios sdk (5.0) that is plugged in here. I need the latest sdk v5.1 (or more specifically 5.1.10) to be able to use those features on iOS, as per Intercom specialists recommended.
Can you please update ASAP?
 
Thanks,
Sheyda

**Comment by browniefed** [comment]
Submit a PR
