### ISSUE TITLE
Intercom.displayMessageComposer() not working on Android

### ISSUE THREAD

**Issue by luiscarlos-gonzalez** [tinycreative/react-native-intercom#25]
I followed the instructions for setup the this library.
I have already the user registration working, but when I execute `Intercom.displayMessageComposer()` I got nothing, no error and not loading the message composer.

`{
  title: 'Contactar a soporte',
  onPress: () => Intercom.displayMessageComposer()
}`

```
render() {
   var {logo, title} = this.props.link;
   var image = logo && <Image style={styles.picture} source={{uri: logo}} />;
   return (
     <Touchable onPress={this.handlePress.bind(this)}>
       <View style={styles.row}>
         {image}
           <Text style={styles.title} numberOfLines={2}>
             {title}
          </Text>
          <Image source={require('../../components/img/disclosure.png')} />
        </View>
      </Touchable>
   );
}
```

```
handlePress() {
  var {url, onPress} = this.props.link;
  if (onPress) {
    onPress();
  }
  if (url) {
    Linking.openURL(url);
  }
}
```

Any one is having the same problem that me?

**Comment by browniefed** [comment]
Can you give the latest version a try, just published v3.0 with updates.

**Comment by luisfpinto** [comment]
Same problem here, I'm not getting anything when I call Intercom.displayMessageComposer()

**Comment by luisfpinto** [comment]
Check if you are using the Android API Keys, that was my problem ;)

**Comment by dccarmo** [comment]
Also check if you registered an user.

**Comment by tranhuuthinhit** [comment]
I have the same problem, but I resolved. 

You need to an android Android API key begin with **android_sdk-**, you can get this key on Developer Hub of Intercom. 

On the left panel, open Installation menu and then choose Android option.

**Comment by ghost** [comment]
I'm getting this error. I followed the docs and users the android api key. Some solutions ?
