### ISSUE TITLE
Cannot read property 'UNREAD_CHANGE_NOTIFICATION' of undefined

### ISSUE THREAD

**Issue by jboteros** [tinycreative/react-native-intercom#252]
Hi, I need some help

I install the component in the 3 possible ways on iOS. pods, manually link from node-modules, download the framework etc ...

In all the forms I receive the same error

> Cannot read property 'UNREAD_CHANGE_NOTIFICATION' of undefined

Very very thanks!!! 

![simulator screen shot - iphone 6 - 2018-12-19 at 08 17 40](https://user-images.githubusercontent.com/20464735/50222536-9140c780-0366-11e9-9c11-2f9a53310763.png)
![screen shot 2018-12-19 at 8 17 07 am](https://user-images.githubusercontent.com/20464735/50222537-93a32180-0366-11e9-96db-fc5af480d302.png)
<img width="1006" alt="screen shot 2018-12-19 at 8 18 18 am" src="https://user-images.githubusercontent.com/20464735/50222756-32c81900-0367-11e9-8675-945787c62e0f.png">
<img width="1187" alt="screen shot 2018-12-19 at 8 22 30 am" src="https://user-images.githubusercontent.com/20464735/50222790-4ffce780-0367-11e9-835a-5999ce152501.png">

**Comment by mtford90** [comment]
I experienced this also - the solution was to run `pod install` after performing `react-native link`.
