### ISSUE TITLE
Launcher doesn't show

### ISSUE THREAD

**Issue by sanjosedennisns7593** [tinycreative/react-native-intercom#253]
Hi,

I have been followed the documentation, and it seems that it works correctly unfortunately when i run the app, i run the setLauncherVisibility either on render or componentDidMount method neither of the two doesn't work to show the launcher. 

Does anyone have an idea why this issue happen? I've already added the prefix in the api key, but still doesn't fix the issue.

**Comment by jayporta** [comment]
Are you explicitly calling Intercom.displayMessenger()?

**Comment by sanjosedennisns7593** [comment]
I've tried that one, it doesn't work either.
