### ISSUE TITLE
Undocumented Intercom Methods

### ISSUE THREAD

**Issue by AshiHarel** [tinycreative/react-native-intercom#258]
For people who straggled in here, I found 2 method not listed in documentation: 
1. Intercom.displayMessenger() === Intercom('show') - opens last conversation
 2. Intercom.displayConversationsList() === Intercom('showMessages') - opens conversation list
Please see:  https://developers.intercom.com/installing-intercom/docs/intercom-javascript For more info

Please add this to documentation.

**Comment by browniefed** [comment]
Submit a PR and I'll merge it.
