### ISSUE TITLE
How to set android push notification icon

### ISSUE THREAD

**Issue by vvusts** [tinycreative/react-native-intercom#259]
I have put icons:
mdpi - 24
hdpi - 36
xhdpi - 48
xxhdpi - 72
in /res/mipmap-*
Icon is white with translarent background.
I named icon: intercom_push_icon.png
But instead of this icon I see some green cloud icon for notification.
Can icon be customized?

**Comment by darbaoui** [comment]
why this issue closed, i have the same issue
<img width="242" alt="Screenshot 2020-01-16 at 13 09 22" src="https://user-images.githubusercontent.com/6907747/72524102-77233280-3861-11ea-95c6-2a0f562ffdb7.png">

**but the notification icon showing in my phone is**

![WhatsApp Image 2020-01-16 at 13 12 55](https://user-images.githubusercontent.com/6907747/72524373-0e888580-3862-11ea-90c9-4495fb9f4c07.jpeg)

**Comment by gabimoncha** [comment]
@darbaoui  what Android version are you using? I've noticed that for Android 7 it doesn't show the icon, while for Android 9 it shows it.

**Comment by darbaoui** [comment]
@gabrielmoncea I have huawei nova 3I `android version = 9`
