### ISSUE TITLE
IntercomWrapper.m says <Intercom/Intercom.h> not found

### ISSUE THREAD

**Issue by chandlervdw** [tinycreative/react-native-intercom#26]
I have followed the instructions exactly (they are the same as other libs that use `rnpm link`). But building the project with React Native 0.30 fails on the second line of code in `IntercomWrapper.m`.

**Comment by browniefed** [comment]
You must add Intercom to the project, we do not manually include it for you.
This has been brought up before, I should really add it to the project.

**Comment by chandlervdw** [comment]
@browniefed yeah, I _just_ figured that out. Typically, react-native libs will include the iOS deps.

Another question - do I have to `registerIdentifiedUser` before I'm able to start a conversation?

**Comment by browniefed** [comment]
@chandlervdw I actually do not use this nor did I write it, just do my best to maintain it in my free time. So since I've never used it, I'm unsure, but I do not believe you need to call it but could be wrong.

**Comment by af-inf** [comment]
"You must add Intercom to the project"

How do we do that? Any clues what do we need to add?

**Comment by kageurufu** [comment]
If you are using cocoapods, follow https://github.com/tinycreative/react-native-intercom#cocoapods and pod install, and it will pull the extra dependencies in. Otherwise, you will have to download and link  https://github.com/intercom/intercom-ios as their documentation shows.
