### ISSUE TITLE
Configuration of the app ID and key.

### ISSUE THREAD

**Issue by vongohren** [tinycreative/react-native-intercom#261]
if we were to run a test app, would it not be nice to be able to configurate the app from Javascript. Or change the identity of the current app initialized from the native.

Right now configuration needs to leak into native which adds another level of complexity. It would be nice to keep the configuration just from the javascript side.

Any suggestions on to how to work with a test environment and prod?

**Comment by tomhicks** [comment]
Here to say I have the same suggestion. Having to figure out a way to change the config in two different native languages is a pain.

**Comment by vongohren** [comment]
@browniefed on what basis are you closing these issues?

**Comment by vongohren** [comment]
@browniefed what happened with closing this?
