### ISSUE TITLE
Intercom Answer Bot Support

### ISSUE THREAD

**Issue by josephgoksu** [tinycreative/react-native-intercom#262]
I want to use intercom answer bot feature. I think we don't need to do anything with this library (react-native-intercom). It's about the native library. I chatted with the intercom operation team and they said we need to upgrade native library to 5.20. This library is already using 5.+.
The problem is that whenever we write an example sentence, answer bot won't work. Did anyone have a problem related to this issue?

**Comment by carlosa54** [comment]
@y7usuf the answer bot is working for me:

<img width="319" alt="bot" src="https://user-images.githubusercontent.com/4250593/52069068-61373780-2554-11e9-8319-f4f3f5652c06.png">

I used the answer bot example from Intercom. Maybe you are missing some configuration on the Intercom Dashboard?

**Comment by joseabraham** [comment]
Could this be an issue only with iOS? I tested in an android and it did work on my app, but not in the iOS version.

**Comment by carlosa54** [comment]
Hi @joseabraham, can you check your version of Intercom for iOS?

If you're using cocoapods you can go to the `Podfile.lock` and look for something like this:
```
PODS:
    - Intercom (5.2)
```

The Answer Bot is supported since release [5.1.6](https://github.com/intercom/intercom-ios/releases/tag/5.1.6). Make sure your version is greater or equal than 5.1.6

**Comment by joseabraham** [comment]
> Hi @joseabraham, can you check your version of Intercom for iOS?
> 
> If you're using cocoapods you can go to the `Podfile.lock` and look for something like this:
> 
> ```
> PODS:
>     - Intercom (5.2)
> ```
> The Answer Bot is supported since release [5.1.6](https://github.com/intercom/intercom-ios/releases/tag/5.1.6). Make sure your version is greater or equal than 5.1.6

Hi @carlosa54 thanks for the support,  I'm not using cocoapods, if I installed it manually how could I check for the version?

I think that's my issue but just want to make sure what version do I have.

**Comment by carlosa54** [comment]
> > Hi @joseabraham, can you check your version of Intercom for iOS?
> > If you're using cocoapods you can go to the `Podfile.lock` and look for something like this:
> > ```
> > PODS:
> >     - Intercom (5.2)
> > ```
> > The Answer Bot is supported since release [5.1.6](https://github.com/intercom/intercom-ios/releases/tag/5.1.6). Make sure your version is greater or equal than 5.1.6
> 
> Hi @carlosa54 thanks for the support, I'm not using cocoapods, if I installed it manually how could I check for the version?
> 
> I think that's my issue but just want to make sure what version do I have.

You can check the framework version by going to your Xcode project -> Right click `Intercom.framework` and click `Open in finder`. That should take you to the framework folder location, Inside there look for the file `Info.plist`, open it and look for `Bundle version`, that's the Intercom SDK version

**Comment by joseabraham** [comment]
> > > Hi @joseabraham, can you check your version of Intercom for iOS?
> > > If you're using cocoapods you can go to the `Podfile.lock` and look for something like this:
> > > ```
> > > PODS:
> > >     - Intercom (5.2)
> > > ```
> > > The Answer Bot is supported since release [5.1.6](https://github.com/intercom/intercom-ios/releases/tag/5.1.6). Make sure your version is greater or equal than 5.1.6
> > 
> > 
> > Hi @carlosa54 thanks for the support, I'm not using cocoapods, if I installed it manually how could I check for the version?
> > I think that's my issue but just want to make sure what version do I have.
> 
> You can check the framework version by going to your Xcode project -> Right click `Intercom.framework` and click `Open in finder`. That should take you to the framework folder location, Inside there look for the file `Info.plist`, open it and look for `Bundle version`, that's the Intercom SDK version

Thanks again @carlosa54 that's it I was using an earlier version of the SDK 3.2.1
