### ISSUE TITLE
How to open Help Center inside the app from messages?

### ISSUE THREAD

**Issue by fyodoriv** [tinycreative/react-native-intercom#264]
Right now if I open Intercom with this lib in ios so that I can see messages; when I click on an article I get redirected to Safari. How do I configure the Help Center so that I stay inside the app after clicking on an article?

**Comment by fyodoriv** [comment]
Why is this closed?

**Comment by forsen** [comment]
@cbrwizard probably because you're asking for help, not reporting a bug. StackOverflow is better suited to get help on how to use this library, while github issues is better suited to report bugs and feature suggestions.
