### ISSUE TITLE
WINDOW_DID_HIDE / WINDOW_DID_SHOW missing on Android

### ISSUE THREAD

**Issue by tancredi** [tinycreative/react-native-intercom#266]
The `WINDOW_DID_HIDE` / `WINDOW_DID_SHOW` events don't seem to be implemented for Android - it would be really handy to have those since whenever showing an Intercom dialog sends the RN app in background mode (or at least that's what listening to `AppState` events communicates) and there seems no way to make a distinction between - for example - the screen being locked / app being minimised / Intercom being used

I'm not the best to implement something like this, so sorry for showing up empty handed :)

**Comment by n8stowell82** [comment]
was this resolved? I am running into the same issue where `WINDOW_DID_HIDE` is not firing on Android.

**Comment by LJNGDAHL** [comment]
Same issue for me, `WINDOW_DID_HIDE` is not triggered on Android.

**Comment by tancredi** [comment]
Yah seems this wasn't fixed - issue was just closed with no PRs mentioning it? @browniefed

**Comment by jmkitavi** [comment]
Re-opened issue
https://github.com/tinycreative/react-native-intercom/issues/405
