### ISSUE TITLE
Add additional methods for Intercom integration

### ISSUE THREAD

**Issue by bhaskarmurthy** [tinycreative/react-native-intercom#27]
A few handy methods are still missing, would love an implementation for Android on these.

`Intercom.client().getUnreadConversationCount();`
`Intercom.client().addUnreadConversationCountListener(listener);`
`Intercom.client().setInAppMessageVisibility(Visibility.GONE);`
`Intercom.client().hideMessenger();`

Not sure about the process to submit a pull request, I can work on these if they're not currently in progress or not taken.

**Comment by browniefed** [comment]
I do not use this, just help maintain it, if you submitted a PR for those I'd happily merge it.

**Comment by browniefed** [comment]
I think these got added recently. Can you see if you have anything that still needs to be added.

**Comment by kageurufu** [comment]
We are still missing `addUnreadConversationCountListener`, although that is a far more complicated implementation.

**Comment by prithsharma** [comment]
Does `getUnreadConversationCount()` work well? There isn't any documentation but checking the bridge implementation, I wrote the following:-

```
Intercom.getUnreadConversationCount()
      .then((obj) => {
        console.log(obj);
      })
      .catch((err) => {
        console.log(err);
      });
```

The promise resolves but I always ended up getting `obj` as `null`. Any ideas?

**Comment by GeoffreyPlitt** [comment]
Anybody fixed this yet?

**Comment by browniefed** [comment]
Nope but happy to accept a PR

**Comment by kaadash** [comment]
Today I used method Intercom.getUnreadConversationCount() and it seems to work properly. Maybe it is good idea to close this issue?
