### ISSUE TITLE
Changelogs for major releases

### ISSUE THREAD

**Issue by gausam** [tinycreative/react-native-intercom#271]
Good day. First off, thank you for this wrapper. It really ices the cake 🍰

Now that 13.0.0 is out and available on npm, and being a major version implies there are some backwards incompatible changes - are there notes somewhere for how we might be impacted moving from v12 to v13?

**Comment by browniefed** [comment]
https://github.com/tinycreative/react-native-intercom/pull/265

**Comment by browniefed** [comment]
Mostly just native stuff

**Comment by gausam** [comment]
Well noted. Maybe we can include notes from the PRs with each release.

**Comment by gausam** [comment]
Disregard the above. I see no new tags are being pushed to Github, so there's no way to do that I suppose.

Thanks so much.

**Comment by browniefed** [comment]
Pushed tags. I don't care about this project. I let people that use it help maintain it, I review their work, merge PRs, and publish.
