### ISSUE TITLE
'Signed up' set to 49 years for Android users

### ISSUE THREAD

**Issue by willdady** [tinycreative/react-native-intercom#274]
I've discovered an issue where calling `Intercom.updateUser()` sets the _Signed up_ value to 49 years (2019 - 49 = 1970) for Android users. 

The documentation [here](https://developers.intercom.com/intercom-api-reference/reference) says `signed_up_at` needs to be provided in **seconds** which is what I'm providing to `Intercom.updateUser()` e.g.

```
Intercom.updateUser({
  signed_up_at: moment(user.createdAt).unix(),
  ...
});
```

However the android implementation is wrong (I think) as [the Date constructor expects the value to be milliseconds](https://docs.oracle.com/javase/7/docs/api/java/sql/Date.html#Date(long)):

https://github.com/tinycreative/react-native-intercom/blob/3f8fdc81ba71591ad2940f340f574628f6a60a78/android/src/main/java/com/robinpowered/react/Intercom/IntercomModule.java#L304

Where iOS appears to be correct.

https://github.com/tinycreative/react-native-intercom/blob/3f8fdc81ba71591ad2940f340f574628f6a60a78/iOS/IntercomUserAttributesBuilder.m#L101

**Comment by browniefed** [comment]
Can you submit a PR please
