### ISSUE TITLE
Can it support multiple languages?

### ISSUE THREAD

**Issue by HectorHann** [tinycreative/react-native-intercom#275]
Can it support multiple languages?
If yes, how to set it?

**Comment by conrc** [comment]
@HectorHann you can configure language settings on Intercom's website. If you log into your account and go to the Messenger tab, then click on "Say hello in (almost) any language" you can add language support and custom greetings for each. 
![Screen Shot 2019-08-15 at 4 18 24 PM](https://user-images.githubusercontent.com/40677917/63133092-6e5bc700-bf78-11e9-9448-16cc311dc361.png)
