### ISSUE TITLE
undefined is not an object (evaluating 'IntercomWrapper.registerIdentifiedUser'

### ISSUE THREAD

**Issue by caalle** [tinycreative/react-native-intercom#28]
I'm trying to get the iOS module to work. When running from xcode everything works fine, but when starting using `react-native run-ios` I get `IntercomWrapper is undefined` when trying to log events.
1. I installed intercom-ios manually
   - Added it to embedded frameworks
   - Added custom build phase
2. `npm install react-native-intercom --save`
3. `rnpm link react-native-intercom`

It is working fine on Android and on iOS when building/running from the xcode interface.

Anyone had a similar issue?

**Comment by caalle** [comment]
Not really an issue, I had `release`-scheme set as default. After changing to `debug` scheme in xcode `react-native run-ios` is working.

**Comment by browniefed** [comment]
Thanks for looking into it.

**Comment by IsTheJack** [comment]
The same issue here. In android version. Any workaround for this problem?

**Comment by wrozka** [comment]
@IsTheJack I had to register `IntercomPackage` in `MainApplication` to fix this error:

``` java
 protected List<ReactPackage> getPackages() {                                                  
     return Arrays.<ReactPackage>asList(                                                         
         new MainReactPackage(),                                                                 
         new IntercomPackage()                                                                   
    );                                                                                          
 } 
```
