### ISSUE TITLE
Android or IOS notifications.

### ISSUE THREAD

**Issue by ozanmanav** [tinycreative/react-native-intercom#280]
Hi I integrated to android and ios this repo. Everything workings fine expect for new message notifications or manual message notification.

i looked #144 #157 #269 and #101. But still not working.

This is my log from android studio : 
![image](https://user-images.githubusercontent.com/19241756/54196670-0b4e9b80-44d3-11e9-9dd8-b9c329999961.png)

**Comment by agrass** [comment]
Hello @ozanmanav! You manage to solve this?
