### ISSUE TITLE
Missing close button

### ISSUE THREAD

**Issue by pandigita** [tinycreative/react-native-intercom#282]
This problem is referenced as a side note in other issues, but I felt like a new issue just for this might be appropriate.

On a freshly installed `rn-intercom` (13.0.1) and latest `intercom` (5.2.1) on iOS, the close button is visually (but not functionally) missing from the top-right corner. i.e. you can touch it, window closes correctly - it just can't be seen.

![image](https://user-images.githubusercontent.com/764235/54476382-9911ea00-4837-11e9-9403-e55e680f331b.png)

Note: the screenshot also shows a different issue I have, namely that property names rather than property values are shown all over the messenger ("away_state", "profile_location"). Maybe this is a hint of sorts? Otherwise, I should probably create separate issue for that one..

**Comment by santiagoswinnen** [comment]
Having the same issue... Could you solve it?

**Comment by santiagoswinnen** [comment]
Solved! In XCode go to **Build Phases > Copy Pods Resources** and uncheck "Run script only when installing"
