### ISSUE TITLE
Not updating custom attributes

### ISSUE THREAD

**Issue by steinjonathan** [tinycreative/react-native-intercom#284]
I'm trying to integrate my react-native app with Intercom, but when I try to send custom attributes from a user, it doens't work. And it not give an error, so, I could not undestand why it doesn't work.

I'm using the npm package, and I had follow all steps to implement it on android OS, like is described on npm page documentation.

My android version is 8.0, and i'm using the last version of intercom npm package.

```
const intercomSettings = {
    name: user.full_name,
    email: user.email,
    user_id: `${user.id_user}`,
    // eslint-disable-next-line
    mobileSale_version: "1.0.1"
  };
```

```
Intercom.registerIdentifiedUser({ userId: `${intercomSettings.user_id}` })
    .then((p) => { console.log('iden', p) })

  Intercom.updateUser(intercomSettings)
    .then((p, e) => { console.log('promise', p, e) })
    .catch((err) => { console.log('err', err) })
```

All this console.log() logs "undefined", and the mobileSale_version from the user that I'm logged in not update on Intercom site.

**Comment by carlosa54** [comment]
Hi @steinjonathan,

For the custom attributes to work you'll need to add them as a `custom_attributes` value.

e.g.

```js
const intercomSettings = {
    name: user.full_name,
    email: user.email,
    user_id: `${user.id_user}`,
    // eslint-disable-next-line
    custom_attributes: {
        mobileSale_version: "1.0.1"
    }
  };
```

**Comment by AlphaJuliettOmega** [comment]
We don't use 'intercomSettings and everything works except a new custom attribute we've added.

does this snippet:
```
/**
 * registerUnidentifiedUser
 * @returns {Promise<void>}
 */
export function registerUnidentifiedUser(): Promise<void>;

```
mean that it's not possible to pass custom attributes for Unidentified Users?

RegisterIdentifiedUser:
```

/**
 * registerIdentifiedUser
 * @param {userId: string} | {email: string} options
 * @returns {Promise<void>}
 */
export function registerIdentifiedUser(options: { userId: string } | { email: string }): Promise<void>;
```
Same problem, no option to specify from the App-side that the custom attribute exists.

```
Argument of type '{ email: any; userId: any; custom_attributes: { error: null; }; }' is not assignable to parameter of type '{ userId: string; } | { email: string; }'.
  Object literal may only specify known properties, and 'custom_attributes' does not exist in type '{ userId: string; } | { email: string; }'.
  ```
  
 @carlosa54  So where do I use these IntercomSettings you've example'd above?

**Comment by AlphaJuliettOmega** [comment]
```
Intercom.updateUser({
  custom_attributes: {
    error: 'somestring'
  }
});
```
          
This is the snippet that is failing for me (well no error, passes request successfully but no change happens)

Custom attribute exists Intercom side but just shows 'Unknown' permanently.

**Comment by AlphaJuliettOmega** [comment]
The plot thickens, the feature works from Android (real device in debug mode)
but doesn't work from Iphone 11 iOs14 Emulator

**Comment by Teal-labs-developer** [comment]
Did you find any solution for this?

**Comment by AlphaJuliettOmega** [comment]
@Teal-labs-developer I think the issue I was having is that I had to set up the actual attribute on Intercom side

As in, the specific attribute key 'error' in my case, you can't push a key that's not defined on Intercom side beforehand.

I'm not really sure what I was struggling with re Android vs iOs as it's now working on Emulators and Real devices.

**Comment by Teal-labs-developer** [comment]
@AlphaJuliettOmega I don't think that adding the key to intercom portal would solve anything. Because in my case it is already added. I am using version 13.1.0 though. Let me try it after updating once.

**Comment by Lysander086** [comment]
> @Teal-labs-developer I think the issue I was having is that I had to set up the actual attribute on Intercom side
> 
> As in, the specific attribute key 'error' in my case, you can't push a key that's not defined on Intercom side beforehand.
> 
> I'm not really sure what I was struggling with re Android vs iOs as it's now working on Emulators and Real devices.

As of 2024, I didn't identify there is a `updateUser` method within the Intercom. 
Please check the below points about user info updating: 
- Created CDA within the Intercom
- Make sure that the created CDA are set to allow 'Attribute Updates'.
# Reference
- https://www.intercom.com/help/en/articles/179-create-and-track-custom-data-attributes-cdas
