### ISSUE TITLE
Don't show Intercom widget when the users receives a new message

### ISSUE THREAD

**Issue by dani-mp** [tinycreative/react-native-intercom#286]
Is there a way to configure that when a user receives an Intercom message, the widget with the face of the customer success agent and the message that appears as an overlay at the bottom of the screen simply doesn't appear?

I'm already subscribed to changes to the count of unread messages, so we show that information in our app in a less intrusive way, so we don't need that widget and I'm wondering if I can hide it somehow via code or Intercom configuration.

**Comment by marksantoso** [comment]
+1

**Comment by dani-mp** [comment]
Talking to Intercom around the time I opened the issue here, they told me it wasn't possible (neither via their dashboard nor directly in the native SDKs).

I did ask for it as suggestion/feature request, so I guess the more people ask for it, the better (or at all) we'll have it.

**Comment by marksantoso** [comment]
the support guys on intercom aren't usually very technical. This can probably be done by editing the plugin code.

**Comment by dawidvdh** [comment]
@dani-mp did you ever figure anything out around this?

**Comment by dawidvdh** [comment]
Setting `[Intercom setInAppMessagesVisible:NO];` in AppDelegate worked for me

**Comment by akimabs** [comment]
any update ?
