### ISSUE TITLE
Removing a company not working

### ISSUE THREAD

**Issue by idoamram2gether** [tinycreative/react-native-intercom#287]
Hi!

I'm trying to remove a company from a user, according to: 
https://developers.intercom.com/intercom-api-reference/reference#companies-and-users
```
To remove a company from a user add the field remove with a value of true to the embedded company object and submit the user as an update request. You must also submit the id of the company.
```

I can only update the company, but when I send it with `remove: true` nothing happens.
In addition, `remove` is not a property of the company object in the SDK.

Am I missing something?

Thanks in advance,
Ido

**Comment by carlosa54** [comment]
Hi @idoamram2gether,

Looked into the android and iOS SDKs, I didn't saw any support for removing companies within the SDK, you can try removing the company by using the rest api in the link you provided or try asking intercom if they plan to support or already support the company removal from their SDKs.
