### ISSUE TITLE
XCode unable to find strip-frameworks.sh

### ISSUE THREAD

**Issue by frodoe7** [tinycreative/react-native-intercom#293]
that's the error I'm getting :

> ./Frameworks/Intercom.framework/strip-frameworks.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

I downloaded the Intercom for IOS

it seems Xcode does not watch all contents inside it , it only see the headers folder ,, as shown in the below image

![code][1]

however there's more folders and files beside the headers folder , as shown below

![code][2]

the linked binaries :

![code][3]

embedding the framework and running the script

![code][4]
 
[1]: https://i.imgur.com/xlp018a.png "tooltip"
[2]: https://i.imgur.com/lg4yyaG.png "tooltip"
[3]: https://i.imgur.com/qBIorbI.png "tooltip"
[4]: https://i.imgur.com/qBIorbI.png "tooltip"

**Comment by kashi-halma** [comment]
I am encountering this same issue. Did you perhaps find a solution?

**Comment by ifero** [comment]
I had to remove this kind of build phase when I've started using Cocoapods. Don't know if it is your case

**Comment by canpoyrazoglu** [comment]
Had the same problem. I've moved the strip script to the end of the build phase list (by dragging and dropping) and it worked.
