### ISSUE TITLE
Android version not registering users or initializing app (works on iOS)

### ISSUE THREAD

**Issue by brotsky** [tinycreative/react-native-intercom#296]
I already solved my issue but hopefully this helps others:

My Android version wasn't registering users and I was getting an error that said:
`E/Intercom: Intercom not initialized`

My solution was simply to change
```
Intercom.registerIdentifiedUser({
    userId: id, // this is an int
});
```

to 

```
Intercom.registerIdentifiedUser({
    userId: `${id}`, // I converted it to a String
});
```

**Comment by Subway19** [comment]
https://github.com/tinycreative/react-native-intercom/issues/317

**Comment by onemargaro** [comment]
This works for me, `userId` must be a string to work on Android.
