### ISSUE TITLE
Xcode generic project

### ISSUE THREAD

**Issue by haabnaseem** [tinycreative/react-native-intercom#297]
I integrated and it works without any issue, but when i archive the project i get Generic Xcode project. Does anyone have a solution for this ?

**Comment by Rishu2505** [comment]
Facing same issue still not resolved yet?
I integrated and it works without any issue, but when i archive the project i get Generic Xcode project. Does anyone have a solution for this ?

**Comment by haabnaseem** [comment]
issue resolved.
