### ISSUE TITLE
Spinner loading forever

### ISSUE THREAD

**Issue by canpoyrazoglu** [tinycreative/react-native-intercom#298]
I'm trying to display Intercom using either `Intercom.displayConversationsList();` or `Intercom.displayMessageComposer();` but I'm getting a blank page that has a spinner that keeps spinning forever:

![IMG_5090](https://user-images.githubusercontent.com/4348413/59562364-4a413f80-9034-11e9-9aa0-bfaf293b45c9.jpeg)

In the logs, I'm also getting:
` [Intercom] ERROR - Tried to send metrics, but there was a problem with the SDK's initialisation.`
What am I doing wrong?

**Comment by mrlphoenix** [comment]
That happened to me when I forgot to set ApiKey and AppId in AppDelegate.m

**Comment by lachiet** [comment]
Same thing has started randomly happening for us - any updates on this?

**Comment by canpoyrazoglu** [comment]
@SpaceWind yup, that was it. I had incorrect key as the API key. @lachiet I didn't have any problems after putting the correct keys. Check your error logs in Xcode/LogCat by searching for Intercom. In my case it was telling the error was related to keys, I've just missed it.
