### ISSUE TITLE
Embed Intercom inside View

### ISSUE THREAD

**Issue by canpoyrazoglu** [tinycreative/react-native-intercom#299]
Intercom by default opens on a separate "window" (or card, whatever it is called). In our app designs the Intercom support page designs are embedded inside one of our tabs in our app.

How do I move everything in that Intercom window inside a tab in our app and get rid of that separate window completely?

**Comment by haabnaseem** [comment]
I think right now there is no solution for this, have you implemented this in your project ? also were you able to archive the project? im having this issue #297

**Comment by canpoyrazoglu** [comment]
Yup, instead of hackily-trying to get that view from the window and embed (which may cause many problems), we've decided to talk with out UX designer to fit it into the flow in a way that once a user taps a support button, it brings out the Intercom window.
