### ISSUE TITLE
Upgraded version of Android SDK

### ISSUE THREAD

**Issue by caalle** [tinycreative/react-native-intercom#30]
Just wanted to check if you've got any plans or ongoing work on updating the Intercom SDK for Android?

The current implementation looks like it is using 1.+ while Intercom has released 3.+.

**Comment by kageurufu** [comment]
I have a working update at https://github.com/disruptivelabs/react-native-intercom

**Comment by browniefed** [comment]
New version has been published on npm thanks to @kageurufu for the pull request

**Comment by caalle** [comment]
Great - Thanks for a great component!
