### ISSUE TITLE
App crashes on iPhone XS Max

### ISSUE THREAD

**Issue by ghost** [tinycreative/react-native-intercom#300]
App crashes:
Device: iPhone XS Max
Os version: 12.2
Stacktrace: 

NSInvalidArgumentException
Intercom
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
May 30th, 2019, 09:39:56 UTC

STACKTRACE

NSInvalidArgumentException *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0] 
    Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
    /usr/lib/libobjc.A.dylib _objc_exception_throw
    Frameworks/CoreFoundation.framework/CoreFoundation __CFThrowFormattedException
    Frameworks/CoreFoundation.framework/CoreFoundation -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
    Frameworks/CoreFoundation.framework/CoreFoundation +[NSDictionary dictionaryWithObjects:forKeys:count:]
    Frameworks/Intercom.framework/Intercom +[IntercomSDK_ITBBlockUtils imageBlockForUpload:appearance:]
    IntercomSDK/Classes/Network/Models/ICMConversationPart.m:108:36 +[ICMConversationPart sendingPartWithBlocks:upload:]
    IntercomSDK/Classes/Presentation/Conversation/Conversation Content/ICMConversationContentViewController.m:369:46 -[ICMConversationContentViewController replyToConversationWithBlocks:upload:]
    IntercomSDK/Classes/Presentation/Conversation/Conversation Content/ICMConversationContentViewController.m:9 -[ICMConversationContentViewController sendUpload:]
    IntercomSDK/Classes/Presentation/Conversation/ICMConversationViewController.m:9 -[ICMConversationViewController sendMessage:upload:]
    IntercomSDK/Classes/Presentation/Conversation/ICMConversationViewController.m:420:17 __74-[ICMConversationViewController inputAccessoryView:input:performedAction:]_block_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_main_queue_callback_4CF
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    PrivateFrameworks/GraphicsServices.framework/GraphicsServices _GSEventRunModal
    PrivateFrameworks/UIKitCore.framework/UIKitCore _UIApplicationMain
    /Users/jenkins/jenkins/workspace/partner-app-ios-artifactory-production-build/ios/POSMobile/main.m:16:12 main
    /usr/lib/system/libdyld.dylib _start

THREADS

Thread 0
Error reported from this thread
    Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
    /usr/lib/libobjc.A.dylib _objc_exception_throw
    Frameworks/CoreFoundation.framework/CoreFoundation __CFThrowFormattedException
    Frameworks/CoreFoundation.framework/CoreFoundation -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
    Frameworks/CoreFoundation.framework/CoreFoundation +[NSDictionary dictionaryWithObjects:forKeys:count:]
    Frameworks/Intercom.framework/Intercom +[IntercomSDK_ITBBlockUtils imageBlockForUpload:appearance:]
    IntercomSDK/Classes/Network/Models/ICMConversationPart.m:108:36 +[ICMConversationPart sendingPartWithBlocks:upload:]
    IntercomSDK/Classes/Presentation/Conversation/Conversation Content/ICMConversationContentViewController.m:369:46 -[ICMConversationContentViewController replyToConversationWithBlocks:upload:]
    IntercomSDK/Classes/Presentation/Conversation/Conversation Content/ICMConversationContentViewController.m:9 -[ICMConversationContentViewController sendUpload:]
    IntercomSDK/Classes/Presentation/Conversation/ICMConversationViewController.m:9 -[ICMConversationViewController sendMessage:upload:]
    IntercomSDK/Classes/Presentation/Conversation/ICMConversationViewController.m:420:17 __74-[ICMConversationViewController inputAccessoryView:input:performedAction:]_block_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_main_queue_callback_4CF
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    PrivateFrameworks/GraphicsServices.framework/GraphicsServices _GSEventRunModal
    PrivateFrameworks/UIKitCore.framework/UIKitCore _UIApplicationMain
    /Users/jenkins/jenkins/workspace/partner-app-ios-artifactory-production-build/ios/POSMobile/main.m:16:12 main
    /usr/lib/system/libdyld.dylib _start
Thread 1
    /usr/lib/system/libsystem_kernel.dylib _mach_msg_trap
    /usr/lib/system/libsystem_kernel.dylib _mach_msg
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopServiceMachPort
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    Frameworks/Foundation.framework/Foundation -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
    Frameworks/Foundation.framework/Foundation -[NSRunLoop(NSRunLoop) runUntilDate:]
    PrivateFrameworks/UIKitCore.framework/UIKitCore -[UIEventFetcher threadMain]
    Frameworks/Foundation.framework/Foundation -[NSThread main]
    Frameworks/Foundation.framework/Foundation ___NSThread__start__
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 2
    /usr/lib/system/libsystem_kernel.dylib _mach_msg_trap
    /usr/lib/system/libsystem_kernel.dylib _mach_msg
    /usr/lib/system/libsystem_kernel.dylib _thread_suspend
    POSMobile ksmachexc_i_handleExceptions
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 3
    /usr/lib/system/libsystem_kernel.dylib _mach_msg_trap
    /usr/lib/system/libsystem_kernel.dylib _mach_msg
    POSMobile ksmachexc_i_handleExceptions
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 4
    /usr/lib/system/libsystem_kernel.dylib _mach_msg_trap
    /usr/lib/system/libsystem_kernel.dylib _mach_msg
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopServiceMachPort
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    POSMobile +[RCTCxxBridge runRunLoop]
    Frameworks/Foundation.framework/Foundation -[NSThread main]
    Frameworks/Foundation.framework/Foundation ___NSThread__start__
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 5
    /usr/lib/system/libsystem_kernel.dylib ___psynch_cvwait
    /usr/lib/system/libsystem_pthread.dylib __pthread_cond_wait
    /usr/lib/libc++.1.dylib std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >)
    Frameworks/JavaScriptCore.framework/JavaScriptCore std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
    Frameworks/JavaScriptCore.framework/JavaScriptCore std::__1::cv_status std::__1::condition_variable_any::wait_until<std::__1::unique_lock<bmalloc::Mutex>, std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<bmalloc::Mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
    Frameworks/JavaScriptCore.framework/JavaScriptCore bmalloc::Scavenger::threadRunLoop()
    Frameworks/JavaScriptCore.framework/JavaScriptCore bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*)
    Frameworks/JavaScriptCore.framework/JavaScriptCore void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*)
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 6
    /usr/lib/system/libsystem_kernel.dylib _mach_msg_trap
    /usr/lib/system/libsystem_kernel.dylib _mach_msg
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopServiceMachPort
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    PrivateFrameworks/WebCore.framework/WebCore RunWebThread(void*)
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 7
    /usr/lib/system/libsystem_kernel.dylib ___workq_kernreturn
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
Thread 8
    /usr/lib/system/libsystem_kernel.dylib _mach_msg_trap
    /usr/lib/system/libsystem_kernel.dylib _mach_msg
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopServiceMachPort
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRun
    Frameworks/CoreMotion.framework/CoreMotion 0x18681727c (-0x81d38000 + 8729719420)
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 9
    /usr/lib/system/libsystem_kernel.dylib _mach_msg_trap
    /usr/lib/system/libsystem_kernel.dylib _mach_msg
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopServiceMachPort
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    Frameworks/CFNetwork.framework/CFNetwork -[__CoreSchedulingSetRunnable runForever]
    Frameworks/Foundation.framework/Foundation -[NSThread main]
    Frameworks/Foundation.framework/Foundation ___NSThread__start__
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 10
    /usr/lib/system/libsystem_kernel.dylib _mach_msg_trap
    /usr/lib/system/libsystem_kernel.dylib _mach_msg
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopServiceMachPort
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    Frameworks/Foundation.framework/Foundation -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
    Frameworks/Intercom.framework/Intercom -[IntercomSDK__SRRunLoopThread main]
    Frameworks/Foundation.framework/Foundation ___NSThread__start__
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 11
    /usr/lib/system/libsystem_kernel.dylib _select$DARWIN_EXTSN
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFSocketManager
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
Thread 12
    /usr/lib/system/libsystem_kernel.dylib ___workq_kernreturn
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
Thread 13
    /usr/lib/system/libsystem_kernel.dylib ___workq_kernreturn
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
Thread 14
    /usr/lib/system/libsystem_kernel.dylib ___workq_kernreturn
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
Thread 15
    /usr/lib/system/libsystem_kernel.dylib ___workq_kernreturn
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
Thread 16
Thread 17
    /usr/lib/system/libsystem_kernel.dylib _lstat64
    Frameworks/Foundation.framework/Foundation __NSFileExistsAtPath
    Frameworks/Foundation.framework/Foundation __NSStandardizePathUsingCache
    Frameworks/Foundation.framework/Foundation -[NSString(NSPathUtilities) _stringByStandardizingPathUsingCache:]
    Frameworks/Foundation.framework/Foundation __NSExpandTildeInPath
    Frameworks/Foundation.framework/Foundation -[NSString(NSPathUtilities) stringByExpandingTildeInPath]
    Frameworks/Foundation.framework/Foundation _NSSearchPathForDirectoriesInDomains
    IntercomSDK/Classes/Utils/ICMUtils.m:161:34 +[ICMUtils intercomLegacyDocumentsPath]
    IntercomSDK/Classes/Utils/ICMUtils.m:166:28 +[ICMUtils migrateDocumentsIfNeeded]
    IntercomSDK/Classes/Utils/ICMUtils.m:126:34 +[ICMUtils intercomDocumentsDirectory]
    IntercomSDK/Classes/Utils/Metrics/ICMMetric.m:128:13 +[ICMMetric archivePath]
    IntercomSDK/Classes/Utils/Metrics/ICMMetric.m:123:63 +[ICMMetric saveMetrics:]
    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_root_queue_drain
    /usr/lib/system/libdispatch.dylib __dispatch_worker_thread2
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
Thread 18
    /usr/lib/system/libsystem_kernel.dylib ___workq_kernreturn
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
Thread 19
    /usr/lib/system/libsystem_kernel.dylib ___workq_kernreturn
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
Thread 20
    /usr/lib/system/libsystem_kernel.dylib ___getdirentries64
    /usr/lib/system/libsystem_c.dylib __readdir_unlocked
    /usr/lib/system/libsystem_c.dylib _readdir
    Frameworks/CoreFoundation.framework/CoreFoundation __CFIterateDirectory
    Frameworks/CoreFoundation.framework/CoreFoundation __CFBundleReadDirectory
    Frameworks/CoreFoundation.framework/CoreFoundation __createQueryTableAtPath
    Frameworks/CoreFoundation.framework/CoreFoundation __copyQueryTable
    Frameworks/CoreFoundation.framework/CoreFoundation __copyResourceURLsFromBundle
    Frameworks/CoreFoundation.framework/CoreFoundation __CFBundleCopyFindResources
    Frameworks/CoreFoundation.framework/CoreFoundation _CFBundleCopyResourceURL
    Frameworks/Foundation.framework/Foundation -[NSBundle URLForResource:withExtension:subdirectory:]
    IntercomSDK/Classes/Utils/Appearance/ICMAssets.m:258:28 +[ICMAssets urlForFilename:]
    IntercomSDK/Classes/Presentation/ICMSoundPlayer.m:33:31 __44+[ICMSoundPlayer playSoundForSendingMessage]_block_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_root_queue_drain
    /usr/lib/system/libdispatch.dylib __dispatch_worker_thread2
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
Thread 21

**Comment by dmarkowski** [comment]
Very similar issue discovered when users start to upload very often files to the intercom. 

`NSInvalidArgumentException · *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
Frameworks/Intercom.framework/Intercom+[IntercomSDK_ITBBlockUtils imageBlockForUpload:appearance:]	
IntercomSDK/Classes/Network/Models/ICMConversationPart.m:108:36+[ICMConversationPart sendingPartWithBlocks:upload:]	
IntercomSDK/Classes/Presentation/Conversation/Conversation Content/ICMConversationContentViewController.m:369:46-[ICMConversationContentViewController replyToConversationWithBlocks:upload:]`

May be related to this ticket [issue-321](https://github.com/tinycreative/react-native-intercom/issues/321)
