### ISSUE TITLE
IOS: App crash on file upload

### ISSUE THREAD

**Issue by afotescu** [tinycreative/react-native-intercom#301]
Hi, after IOS 12.2 update, when you try to upload a file via intercom, the app crashes.
Package version:  12.0.0/12.5.1/13.1.0
IOS version: 12.2

Is there any solution to fix this ?
Thanks

**Comment by thaapasa** [comment]
Hi, we had the same problem after iOS 13 update.

For us, updating the Intercom pod to v. 5.5.1 fixed this (Intercom's changelog says that v.5.0.0 fixes compatibility with iOS 13).

Try running `pod update` in the `ios` folder (if you have autolinking), or update the version manually to `Podfile` and run `pod install` if you've linked it manually.

**Comment by smakosh** [comment]
> Hi, we had the same problem after iOS 13 update.
> 
> For us, updating the Intercom pod to v. 5.5.1 fixed this (Intercom's changelog says that v.5.0.0 fixes compatibility with iOS 13).
> 
> Try running `pod update` in the `ios` folder (if you have autolinking), or update the version manually to `Podfile` and run `pod install` if you've linked it manually.

Still unresolved, the app keeps crashing

**Comment by rhoskal** [comment]
Below are the iOS Xcode simulator devices I've tested image upload functionality (standard images available on the device were used). It looks like iOS 13.x with `react-native-intercom v12.x` has issues. We are currently on RN `0.59.10` and the package was originally installed via CocoaPods and linked, not manually installed the way the docs suggest as an alternate approach.  

| Simulator Device  | iOS Version | Pass | react-native-intercom |
| ------- | ------------ | ---- | ----------------------|
| iPhone 6  | 11.3 |✅| 12.5.1 |
| iPhone 6  | 12.1 |✅| 12.5.1 |
| iPhone 7  | 11.3 |✅| 12.5.1 |
| iPhone 7  | 12.1 |✅| 12.5.1 |
| iPhone 8  | 11.3 |✅| 12.5.1 |
| iPhone 8  | 12.1 |✅| 12.5.1 |
| iPhone 8  | 13.3 |❌| 12.5.1 |
| iPhone 11 | 13.3 |❌| 12.0.0, 12.5.1 |
| iPhone X  | 11.3 |✅| 12.5.1 |
| iPhone X  | 12.1 |✅| 12.5.1 |
| iPhone XS Max  | 12.1 |✅| 12.5.1 |
| iPad Pro 11in.  | 13.3 |❌| 12.5.1 |

There error that was popping out in the Xcode logs was: 
`libc++abi.dylib: terminating with uncaught exception of type NSException`

The solution was to do change `react-native-intercom` to `13.2.0` in `package.json` and then `pod update Intercom`. This was successfully tested on iOS simulator devices: 
- iPhone 8 (13.3)
- iPhone 11 Pro (13.3)
- iPhone XS Max (12.2) *for a sanity check

This supports what @thaapasa suggests here and what @makirby suggests in #321. The two issues seem to be duplicates.
