### ISSUE TITLE
NSInternalInconsistencyExceptionICMHomescreenViewController.m:529

### ISSUE THREAD

**Issue by ghost** [tinycreative/react-native-intercom#305]
App crashes when using intercom
O/S - 100.0% iOS
O/S Versions - 100.0% 12.3.1
Manufacturers - 100.0% Apple
Models - 100.0% iPhone XR
Stacktrace: 
NSInternalInconsistencyException Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (6) must be equal to the number of items contained in that section before the update (5), plus or minus the number of items inserted or deleted from that section (1 inserted, 1 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out). 
    Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
    /usr/lib/libobjc.A.dylib _objc_exception_throw
    Frameworks/CoreFoundation.framework/CoreFoundation +[NSException raise:format:arguments:]
    Frameworks/Foundation.framework/Foundation -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
    PrivateFrameworks/UIKitCore.framework/UIKitCore -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:]
    PrivateFrameworks/UIKitCore.framework/UIKitCore -[UICollectionView _updateRowsAtIndexPaths:updateAction:updates:]
    PrivateFrameworks/UIKitCore.framework/UIKitCore -[UICollectionView reloadItemsAtIndexPaths:]
    IntercomSDK/Classes/Presentation/Homescreen/ICMHomescreenViewController.m:529:9 -[ICMHomescreenViewController reloadConversationCardView]
    IntercomSDK/Classes/Presentation/Conversation Card/ICMConversationCardViewController.m:107:13 -[ICMConversationCardViewController configureConversationCardState]
    IntercomSDK/Classes/Presentation/Conversation Card/ICMConversationCardViewController.m:75:13 __55-[ICMConversationCardViewController fetchConversations]_block_invoke
    IntercomSDK/Classes/Network/Utils/ICMDataManager.m:178:43 __57-[ICMDataManager updateConversationsWithSuccess:failure:]_block_invoke
    IntercomSDK/Classes/Network/ICMHTTPBridge.m:119:40 __63+[ICMHTTPBridge getConversationsBefore:pageSize:success:error:]_block_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_main_queue_callback_4CF$VARIANT$armv81
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    PrivateFrameworks/GraphicsServices.framework/GraphicsServices _GSEventRunModal
    PrivateFrameworks/UIKitCore.framework/UIKitCore _UIApplicationMain
    /Users/jenkins/jenkins/workspace/partner-app-ios-artifactory-production-build/ios/POSMobile/main.m:14:12 main
    /usr/lib/system/libdyld.dylib _start

**Comment by reboot-jia** [comment]
Hi, guy. I meet this crash again. have you resolved it?

**Comment by reboot-jia** [comment]
Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of items in section 0. The number of items contained in an existing section after the update (9) must be equal to the number of items contained in that section before the update (8), plus or minus the number of items inserted or deleted from that section (1 inserted, 1 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x183b4e364 __exceptionPreprocess
1  libobjc.A.dylib                0x182d94528 objc_exception_throw
2  CoreFoundation                 0x183b4e238 +[NSException raise:format:]
3  Foundation                     0x1844e97f4 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKit                          0x18dba0770 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:]
5  UIKit                          0x18db9d198 -[UICollectionView _updateRowsAtIndexPaths:updateAction:updates:]
6  UIKit                          0x18d2b5ce0 -[UICollectionView reloadItemsAtIndexPaths:]
7  OPay                           0x1038859c0 -[ICMHomescreenViewController reloadConversationCardView]
8  OPay                           0x1038c4228 -[ICMConversationCardViewController configureConversationCardState]
9  OPay                           0x1038c3ea4 __55-[ICMConversationCardViewController fetchConversations]_block_invoke
10 OPay                           0x1038a1878 __57-[ICMDataManager updateConversationsWithSuccess:failure:]_block_invoke
11 OPay                           0x10387eb84 __63+[ICMHTTPBridge getConversationsBefore:pageSize:success:error:]_block_invoke
12 libdispatch.dylib              0x1834caa54 _dispatch_call_block_and_release
13 libdispatch.dylib              0x1834caa14 _dispatch_client_callout
14 libdispatch.dylib              0x18350bc80 _dispatch_main_queue_callback_4CF$VARIANT$armv81
15 CoreFoundation                 0x183af6544 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
16 CoreFoundation                 0x183af4120 __CFRunLoopRun
17 CoreFoundation                 0x183a13e58 CFRunLoopRunSpecific
18 GraphicsServices               0x1858c0f84 GSEventRunModal
19 UIKit                          0x18d16867c UIApplicationMain
20 OPay                           0x102ee68b4 main + 15 (main.m:15)
21 libdyld.dylib                  0x18353056c start

**Comment by reboot-jia** [comment]
Could you help me?

**Comment by ghost** [comment]
@reboot-jia Hi. I haven't got time to dwell on this error. Couldn't even reproduce it. I just reported it so intercom would be aware that this kind of issue happens. So, no sorry.  
Have you manage to reproduce it?

**Comment by reboot-jia** [comment]
I have no way to reproduce, but the crash list record it. this crash run top 3 in our app.

**Comment by ghost** [comment]
@reboot-jia  Thanks for feed back
