### ISSUE TITLE
Android handleWindowDidShowNotification and handleWindowDidHideNotification events doesnt impemented

### ISSUE THREAD

**Issue by furkanyilmazx** [tinycreative/react-native-intercom#312]
Intercom react native package doesnt support handleWindowDidHideNotification and handleWindowDidShowNotification event at android. IOS supported corrected but i didnt see in android.

IOS: handleWindowDidHideNotification  at 
https://github.com/tinycreative/react-native-intercom/blob/master/iOS/IntercomEventEmitter.m#L27

IOS: handleWindowDidShowNotification at https://github.com/tinycreative/react-native-intercom/blob/master/iOS/IntercomEventEmitter.m#L35

**Comment by joshgranttc** [comment]
Looks like this still hasn't been resolved? We have tried implementing the react-native-intercom package, and the  "Intercom.Notifcations.WINDOW_DID_HIDE" is working perfectly on iOS. However on android this doesn't seem to be fired.

**Comment by furkanyilmazx** [comment]
Hi @joshgranttc ,
You can use react native AppState API as a workaround.
[AppState API](https://reactnative.dev/docs/appstate)

**Comment by Donhv** [comment]
Hi @furkanyilmazx . i'm trying to setting push notification on my iOS app, but i have problem:  when open app(app in foreground) how to listen when notifi receive?
i try implement handleWindowDidHideNotification and handleWindowDidShowNotification but it don't help me. Have you done it?

**Comment by furkanyilmazx** [comment]
Hi @Donhv ,

I think you can use event listener as notification receive handler. 

`Intercom.addEventListener(Intercom.Notifications.UNREAD_COUNT, this._onUnreadChange)`
