### ISSUE TITLE
Something went wrong - Intercom on Android

### ISSUE THREAD

**Issue by Subway19** [tinycreative/react-native-intercom#317]
Hi,

I have followed all the steps for configuring Intercom for Android on our React Native Project.
Steps followed:
1. react-native link react-native-intercom
2. Follow manual integration with this 
   `If you'd rather not have push notifications in your app, you can use this dependency:`

Result : build success

On intercom opening
Getting this screen : 
![Screenshot_1569131751](https://user-images.githubusercontent.com/14835320/65383150-90dac000-dd2e-11e9-9154-228452eb6964.png)

On adb logcat : 
Getting this :
`Intercom: Api call failed: {"type":"error.list","request_id":"000inqj90bj3mpbrov80","errors":[{"code":"not_found","message":"User Not Found"}]}`

I rechecked again the `Android API Key` and `App Id` is correct.
Researched everywhere but solution nowhere to be found. 

This is my react-native info :

<img width="562" alt="Screen Shot 2019-09-22 at 12 06 10 PM" src="https://user-images.githubusercontent.com/14835320/65383323-8ff75d80-dd31-11e9-8077-dada068d737f.png">

Any help?

**Comment by FrenchMajesty** [comment]
Also experiencing this problem. How did you end up fixing it @Subway19 ?

**Comment by export-mike** [comment]
same problem for me I'm seeing 
```
03-25 13:20:09.229  8798  8893 E Intercom: The messenger was opened but there was no user registered on this device. Please call registerUnidentifiedUser() or registerIdentifiedUser(Registration).
03-25 13:20:09.286  8798  8798 E Intercom: Api call failed: A network request was made with no user registered on this device.Please call registerUnidentifiedUser() or registerIdentifiedUser(Registration).
```

**Comment by Dirkhuethorst** [comment]
I had the same issue on my Android Emulator, but on my phone it worked without a problem.

**Comment by JulianKingman** [comment]
This happened when I tried too invoke an Intercom function without first registering a user. I moved the bit of code that did that, and didn't realize it.

**Comment by yahm23** [comment]
Everything works fine on iOS simulator using Xcode, but greeted with this same screen as OP when using Android. I'm getting this without any Intercom related logged errors as well. Unlike @Dirkhuethorst, mine doesn't work for emulator or physical device.

**Comment by McSam94** [comment]
I faced this issue and I manage to resolve it by adding `compile project(':react-native-intercom')` under `dependencies` in `app/build.gradle`. Hope this helps someone.

**Comment by vikram-newb** [comment]
@McSam94 tried using your solution, unfortunately, it didn't work in my case, still facing the same issue. Has there been any fix for this?

**Comment by michaelVictoriaDev** [comment]
still having an issue in update package.

**Comment by soniaalabed** [comment]
For me the issue was with userId, I was using number instead of string, once I changed it Intercom worked

**Comment by SmilingFarood** [comment]
> For me the issue was with userId, I was using number instead of string, once I changed it Intercom worked
Please what documentation did you follow. I'm getting 

`The messenger was opened but there was no user registered on this device.Please call registerUnidentifiedUser() or registerIdentifiedUser(Registration)`
...as an error

**Comment by churchnotesapp** [comment]
If you're still facing this issue - just make sure you've correctly initialised Intercom in your main.dart
