### ISSUE TITLE
Import doesnt work - last version of react native

### ISSUE THREAD

**Issue by JulianaCP** [tinycreative/react-native-intercom#319]
I followed all the steps in the README and Im still getting an error when I try to import react-native-intercom

![image](https://user-images.githubusercontent.com/14304676/65537222-12af2280-dec2-11e9-9815-289a4b5cc03e.png)

I running the app in android.

This is the config on the android project

![image](https://user-images.githubusercontent.com/14304676/65538314-4ab76500-dec4-11e9-8cd0-115e7e28aa6e.png)

This is the MainApplication.java

![image](https://user-images.githubusercontent.com/14304676/65537729-011a4a80-dec3-11e9-89b4-4258b34492bd.png)

I imported "import com.robinpowered.react.Intercom.IntercomPackage;" and "import io.intercom.android.sdk.Intercom;"

In the app/bundle.gradle I added in the dependencies section

    "implementation project(':react-native-intercom')" and "implementation 'io.intercom.android:intercom-sdk-base:5.+'"

In the settings.gradle I already include react-native-intercom. Like this

    "include ':react-native-intercom'" and "project(':react-native-intercom').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-intercom/android')"

This are my values in the package.json

![image](https://user-images.githubusercontent.com/14304676/65537897-679f6880-dec3-11e9-95af-0ec50ca50177.png)

I dont know what else to do. It just doesnt work. In the moment that I added 
"import Intercom from 'react-native-intercom';" in my code the error is being display

**Comment by the-kenneth** [comment]
How did you solve this? Im facing the same issue. Thanks!
