### ISSUE TITLE
iOS deep link from messenger

### ISSUE THREAD

**Issue by bogdan-vol** [tinycreative/react-native-intercom#326]
Hi,
Is there a way we could launch the app automatically when accessing a URL from messenger? On android this launches the app but on iOS Safari is launched and then we have the top popup that says we can open the URL in the app. URL identifiers and schemas are created, we have implemented .../apple-app-site-association and even though accessing a URL from the email app for example works perfectly (it launches the app directly without launching safari) accessing a URL from intercom messenger doesn't do that.
Thanks

**Comment by parulgarg004** [comment]
@bogdan-vol did you find any solution for this?

**Comment by bogdan-vol** [comment]
@parulgarg004 unfortunately no. We were ok without this feature. If you really need it maybe ask the support in the chat box on their website. They respond pretty quick.
