### ISSUE TITLE
displayHelpCenter doesn't work every time

### ISSUE THREAD

**Issue by nikitawolfik** [tinycreative/react-native-intercom#335]
React-Native: 0.59.10
react-native-intercom: 13.1.0

Implementation:

```
import Intercom from 'react-native-intercom';

...

onPress={Intercom.displayHelpCenter}
```

Help Center is enabled in Intercom configs. It works very well on iOS, but only works every other time  on Android. Has been tested on multiple devices and simulators both in debug and release modes.

In the meantime, the promise that is returned by `Intercom.displayHelpCenter` does resolve, so that is not a rejected promise issue.

**Comment by nikitawolfik** [comment]
This appears to have been fixed by calling
`Intercom.registerUnidentifiedUser()` as app mounts. Apparently, android wouldn't open the help center to an unregistered user.

**Comment by nikitawolfik** [comment]
Actually, my solution is a pain in the ass, so the issue stands.

Apparently, though, it's only android that doesn't trigger the `displayHelpCenter` method to unregistered users. Is there a way to fix this?

**Comment by jefflewis** [comment]
I'm running into this as well. Did you find if this is a limitation of the Intercom sdk or how it's being used in this library?

**Comment by nikitawolfik** [comment]
@jefflewis no, I actually just let it go since `registerUnidentifiedUser` seemed to fix the issue and my team and I didn't care enough to fully investigate this. Though this is just a workaround and I'll try to fix this either if this issue gets addressed and fixed or when I have more spare time on the project
