### ISSUE TITLE
Action required: upgrade mobile SDKs

### ISSUE THREAD

**Issue by iagormoraes** [tinycreative/react-native-intercom#337]
Hello, the version 5 of Intercom SDK will deprecate on June 30th 2020, by upgrading the SDK to 6 will support only Android API 21+ and iOS 10. By upgrading to the version 6 it will work properly or will require to use AndroidX?

**Comment by pete183** [comment]
### Intercom announcement

To continue to provide a fast and secure experience to all Intercom users, we’re deprecating version 5 and below of the Intercom Mobile SDKs on June 30th 2020.

You’re receiving this email because you’re already up-to-date and using version 6 of Intercom’s mobile SDKs. However, we want to make you aware of what the deprecation means for your users.

From June 30th, v5 and below of the iOS and Android SDKs won't be supported. Any end users using version 5 or below of your app after this date won’t be able to access Intercom in your app. We advise that you encourage your customers to upgrade to the latest version of your app to prevent any issues.

**Comment by dmytroyarmak** [comment]
Is there a plan to add Intercom v6 support to `react-native-intercom`? 
Right now the latest version depends on `'Intercom', '~> 5.5.1'`

**Comment by mussegam** [comment]
I just created a PR to use intercom v6 SDKs: https://github.com/tinycreative/react-native-intercom/pull/338

**Comment by pete183** [comment]
PR https://github.com/tinycreative/react-native-intercom/pull/338

**Comment by soban1234** [comment]
When react-native-intercom will update the whole package? Starving for it ;-)

**Comment by soban1234** [comment]
notifications on android are not working when i updated with PR #338

**Comment by soban1234** [comment]
> notifications on android are not working when i updated with PR #338

android/app build.gradle 
update this line     compile 'io.intercom.android:intercom-sdk-fcm:5.+'

to

    compile 'io.intercom.android:intercom-sdk-fcm:6.+'

and it'll work

**Comment by soban1234** [comment]
when i upgrade to #338 
this error is being occured while installing the pods\

[!] CocoaPods could not find compatible versions for pod "Intercom":
  In snapshot (Podfile.lock):
    Intercom (= 5.5.2, ~> 5.0)

  In Podfile:
    react-native-intercom (from `../node_modules/react-native-intercom`) was resolved to 13.0.1, which depends on
      Intercom (~> 6.0.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Intercom` inside your development pod `react-native-intercom`.
   You should run `pod update Intercom` to apply changes you've made.

**Comment by soban1234** [comment]
> when i upgrade to #338
> this error is being occured while installing the pods\
> 
> !] CocoaPods could not find compatible versions for pod "Intercom":
> In snapshot (Podfile.lock):
> Intercom (= 5.0, ~> 5.0)
> 
> In Podfile:
> react-native-intercom (from `../node_modules/react-native-intercom`) was resolved to 13.0.1, which depends on
> Intercom (~> 6.0.0)
> 
> You have either:
> 
> * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> * changed the constraints of dependency `Intercom` inside your development pod `react-native-intercom`.
>   You should run `pod update Intercom` to apply changes you've made.

in your podfile.lock

- react-native-intercom (13.1.0):
    - Intercom (~> 5.0)
**to**
update - react-native-intercom (13.0.1):
    - Intercom (~> 6.0.0)
#######################
  - Intercom (5.5.2)
**to**
  - Intercom (6.0.0)

 it'll work

**Comment by mptorz** [comment]
@browniefed Any estimate on when will one of these PR's be merged?

**Comment by browniefed** [comment]
Merged it. I can release it later

**Comment by browniefed** [comment]
v14 published
