### ISSUE TITLE
Android notification icon.

### ISSUE THREAD

**Issue by YevheniiShabelnykkk** [tinycreative/react-native-intercom#345]
Hello, guys!
Can somebody help with icon for Android notifications?
This icon is always gray and I can't change it. If I do `.android.setSmallIcon(‘ic_launcher’)` it isn't working. Check the same for firebase - everything is ok.
Also tried to add this:
`<meta-data
        android:name=“com.google.firebase.messaging.default_notification_icon”
        android:resource=“@mipmap/ic_launcher” />` - nothing.
Also tried to add icon like wrote in docs for Intercom Android - nothing.

Maybe somebody know what to do? Thanks! :)

**Comment by gabimoncha** [comment]
The problem with the notification icon is that Android has updated the notification logic.
First, you need to create the notification icon in the right format. You can use this [online tool](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_ac_unit). You will need to upload a png glyph for the icon to work, exactly like in this [blog post](https://clevertap.com/blog/fixing-notification-icon-for-android-lollipop-and-above/).

When you download the zip, you need to change the name of the files to `intercom_push_icon.png` and that's it! 🚀

The `meta-data` tag from AndroidManifest is for the default notification icon that you want for your entire app's notifications.
You will need to add that too, in the same way but with the different name. First, create the icon, rename all of them to `notification_icon.png` and then add the following tag to the manifest.

```
<meta-data
    android:name=“com.google.firebase.messaging.default_notification_icon”
    android:resource=“@drawable/notification_icon” />
```

Hope this will help you and the others. The docs clearly need an update.
