### ISSUE TITLE
updateUser problem on Android

### ISSUE THREAD

**Issue by HapitatEric** [tinycreative/react-native-intercom#346]
I have a custom button for triggering Intercom in our app. The code looks like this:

`handleOnPressSupport = () => {
    Intercom.registerUnidentifiedUser();
    Intercom.updateUser({
      name: this.context.user._id + ' - ' + this.context.user.fullName,
    });
    Intercom.displayConversationsList();
  };`

It works fine on iOS where, in Intercom admin, it shows our internal User ID + their full name. But when a user with Android sends a message it just says "User XXXX" where "XXXX" is just random characters.

Anyone know why this is? And maybe some suggestions on how to fix it?

Cheers!

**Comment by albinekb** [comment]
I have the same issue, did you find anything to fix this? @HapitatEric

**Comment by HapitatEric** [comment]
@albinekb Nope, no luck. And it seems like this repo is not active anymore? Might need to switch to native code.

**Comment by albinekb** [comment]
This patch http://news.mit.edu/2020/artificial-intelligence-identifies-new-antibiotic-0220 fixes the issue on android, at the moment I forked that to our company and will use that fork until it's merged: https://github.com/equipmentloop/react-native-intercom

**Comment by albinekb** [comment]
@HapitatEric This patch https://github.com/tinycreative/react-native-intercom/pull/343 fixes the issue on android, at the moment I forked that to our company and will use that fork until it's merged: https://github.com/equipmentloop/react-native-intercom
