### ISSUE TITLE
Intercom.registerUnidentifiedUser() create users on my admin console

### ISSUE THREAD

**Issue by MayoudP** [tinycreative/react-native-intercom#348]
Hello folks, 

for users using my mobile application without being registered, for example peoples who doesn't created their account but still can access to the live chat Intercom).
I need to do this to allow them to access to the live chat : 
```
Intercom.registerUnidentifiedUser().
            then(() => {
                Intercom.displayMessenger();
            })
```

but then it's creating some random users on my admin console : 
<img width="471" alt="Capture d’écran 2020-02-27 à 14 13 37" src="https://user-images.githubusercontent.com/48682041/75448715-039a3800-596c-11ea-8a76-b2d59c28259c.png">

Is there a way to allow non-registered users to access live chat without having to create these kind of users on the DB ? 

Thanks for the help ! And sorry if someone already answered this questions, didn't found a similar thread in the existing issues tho. 

```
react-native-cli: 2.0.1
react-native: 0.59.10
react-native-intercom: 13.0.0,
```

**Comment by Br1an-Boyle** [comment]
👋 unidentified users are assigned a random id within Intercom. This is what you’re seeing here.

**Comment by MayoudP** [comment]
> 👋 unidentified users are assigned a random id within Intercom. This is what you’re seeing here.

And we can't disable this feature ? By any chance...

**Comment by Br1an-Boyle** [comment]
@MayoudP Unfortunately not. Intercom assigns a random id to unidentified users.
You could, however, set a user's name or email via `userAttributes`. Or just register the user as an identified user if you know these details.
