### ISSUE TITLE
Message marked as seen on iOS when app minimized

### ISSUE THREAD

**Issue by marcinkornek** [tinycreative/react-native-intercom#350]
**Problem**
When I reply on Intercom dashboard to iOS app which was just minimized, message is marked as Seen (even if app is minimized) and notification is not sent

**Reproduction steps**
1) open Intercom conversation on iPhone
2) minimize app (go to home screen) and don't do anything else (don't sleep phone, don't open another app)
3) send message to user
In this case message immediately changes to **Seen** and notification is not sent.
In other cases (eg when you sleep phone and send message or open another app and send message, it's fine - it doesn't mark message as seen and notification is sent)

**Stack**
```
react-native: 0.61.5
react-native-intercom: 14.0.0
```

**Comment by Br1an-Boyle** [comment]
👋 This is fixed in version 7.1.0 of the sdk 🙂
