### ISSUE TITLE
Android push. notification does not open chat

### ISSUE THREAD

**Issue by acollazomayer** [tinycreative/react-native-intercom#352]
I installed latest version of the library and now when I press a push notification coming from intercom it does not open the intercom chat

**Comment by Stjng** [comment]
@acollazomayer  did you resolve this issue, im only see bubble, its not open chat conversation like iOS

**Comment by Donhv** [comment]
same issue on android. is there any way fix it on native side?

**Comment by Donhv** [comment]
@acollazomayer @Stjng you need add function handlePushMessage

**Comment by abgaryanharutyun** [comment]
Same to me, did you solve this issue, guys? @Stjng @acollazomayer
