### ISSUE TITLE
Update README to say autolinking is supported

### ISSUE THREAD

**Issue by nabilfreeman** [tinycreative/react-native-intercom#357]
Hey there, despite the README saying I had to manually link Intercom I was able to install it on a fresh RN 61 project simply by autolinking.

Is this widely known? I think it might be time to update the README saying this is the case. I'm happy to contribute the time to do this if you agree.

p.s. I haven't tested Android yet, just iOS.

**Comment by WadhahEssam** [comment]
I am having a tough time trying to let it work with 0.62.2,

I always get this error when doing a `pod install`

<img width="1055" alt="Screen Shot 2020-04-16 at 11 10 51 AM" src="https://user-images.githubusercontent.com/24798045/79431473-2f808400-7fd3-11ea-9574-418a6b7da0b8.png">

and not sure how you get it to work.

I would appreciate it if you could help by showing your steps.

**Comment by WadhahEssam** [comment]
I was bypass this error by downgrading the package to version 13.0.0

**Comment by nabilfreeman** [comment]
I think your error says it all - the spec was found but the minimum deployment target is different. iOS 10 is the minimum so you need to edit your Podfile and Xcode project to only target that version and higher.

This should be fine as it includes the last 5 years of iPhones and iPads

p.s. Don't use `13.0.0` as it has Intercom 5 which will be disabled remotely in June 2020, you need to be on v6

**Comment by WadhahEssam** [comment]
Thank you @nabilfreeman, I will look into this, thank you again for the clarification note sir

**Comment by nabilfreeman** [comment]
No problem, hope this helps and you get back in the game! RN 62 is next on my list so I'm watching closely 😁

**Comment by pablojoral** [comment]
This helped me a lot, the actual process on the readme  didn't work for me. Many thanks, and would be great to add this workaround to the readme :)
