### ISSUE TITLE
IOS build error

### ISSUE THREAD

**Issue by wadeyw** [tinycreative/react-native-intercom#359]
Hi, I'm following the steps to setup the project, but I'm facing below issues 

**IOS: pod install showing error**
[!] CocoaPods could not find compatible versions for pod "react-native-intercom":
  In Podfile:
    react-native-intercom (from `../node_modules/react-native-intercom`)

Specs satisfying the `react-native-intercom (from `../node_modules/react-native-intercom`)` dependency were found, but they required a higher minimum deployment target.

My package version:
"react": "16.9.0",
"react-native": "0.61.4",
 "react-native-intercom": "^15.0.0",

**Comment by hemche** [comment]
Can you see if the target is set to iOS 10.0 ? @wadeyw 
intercom now, supports only iOS 10 and above.

<img width="764" alt="Screen Shot 2020-04-20 at 4 32 39 PM" src="https://user-images.githubusercontent.com/4380406/79797179-d000dc00-8324-11ea-9e46-c5b9577c8529.png">

**Comment by wiredots01** [comment]
hi, 

after solving the above pod install problem,

this error appears
<img width="892" alt="Screen Shot 2020-05-13 at 10 05 20 PM" src="https://user-images.githubusercontent.com/4254904/81822812-26e58400-9566-11ea-8e1a-270412720d13.png">

**Comment by filipchr** [comment]
@wadeyw
@wiredots01 

This might do the trick.

Create the file `react-native.config.js` in the root of your project, then add this config.

```
module.exports = {
  dependencies: {
    'react-native-intercom': {
      platforms: {
        ios: null,
      },
    },
  },
};
```

For more info on [how to disable autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library)

**Comment by kamyab-tatva** [comment]
I am facing the same error 
  **"/ios/Intercom.framework/Headers/Intercom.h:14:2: This version of Intercom for iOS supports iOS 10.0 upwards."**
  Version : 
  "react": "16.13.1",
  "react-native": "0.63.3",
  "react-native-intercom": "^18.0.0"

IOS version in Xcode is: 11.0

**Comment by ramisalem** [comment]
@kamyab-tatva Have you fixed your issue? I am facing the same error
