### ISSUE TITLE
No podspec found

### ISSUE THREAD

**Issue by afilp** [tinycreative/react-native-intercom#36]
Instructions say that you support POD, but I get this error:

"No podscpec found"

How can this be solved please?

**Comment by kageurufu** [comment]
Did you add the pod line, with :path as shown in the README? You have to specify the path to your node_modules/react-native-intercom directly as follows:

```
pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'
```

**Comment by afilp** [comment]
Ok, the problem was that I had an earlier version installed through package.json. Now it is OK, thanks.
