### ISSUE TITLE
How to verify which exact unread messages were read

### ISSUE THREAD

**Issue by BohdanIvanov** [tinycreative/react-native-intercom#364]
Hello everyone!

I've noticed that this library does provide an opportunity to have a listener, which can return on a callback the amount of unread messages `{ count: n }`. As I understood, this is the only option to define that the user does have a certain amount of unread messages. Is it possible to verify which exact messages were read and which one is still pending to be read?

Thank you in advance.

**Comment by Br1an-Boyle** [comment]
👋 This is not currently possible I’m afraid. Please get in touch with Intercom support and submit a feature request.
