### ISSUE TITLE
How to change widget horizontal position ?

### ISSUE THREAD

**Issue by ranAlbagli** [tinycreative/react-native-intercom#365]
hello ! 

**how can i control the widget horizontal position ?**

i want to be able to move the widget to the left bottom.

![Screen Shot 2020-05-17 at 14 09 44](https://user-images.githubusercontent.com/51116008/82142893-79fe5600-9848-11ea-8f8d-abc09a4c4237.png)

**Comment by Br1an-Boyle** [comment]
👋 This is not currently possible I’m afraid.

**Comment by Seamus1989** [comment]
is there any way we can do this? It's blocking the usability of some pages on my app.
