### ISSUE TITLE
Crash on open from alert

### ISSUE THREAD

**Issue by renanpupin** [tinycreative/react-native-intercom#368]
The following code causes app crash when is opened twice.

Steps to reproduce:
- Click in a button that executes this alert.
- Click the YES button.
- The intercom message composer is opened.
- Close the message composer.
- Click the in button to open it again
- CRASH

`Alert.alert(
            'Open intercom', 
            'Do you want to open it?',
            [
                {
                    text: 'YES',
                    onPress: () => {
                        Intercom.displayMessageComposer();
                    }
                }
            ],
        );
`

**Comment by renanpupin** [comment]
I can confirm that it is happening triggering an alert after open messenger.

**Comment by cbrevik** [comment]
I've also encountered this error. Showing an alert at a later point (after the messenger has been opened) will crash the app with the following message:
```
Tried to display alert view but there is no application window. args: {
    <snip>
}

-[RCTAlertManager alertWithArgs:callback:]
    RCTAlertManager.mm:108
__invoking___
-[NSInvocation invoke]
-[NSInvocation invokeWithTarget:]
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0

```

**Comment by renanpupin** [comment]
Solved in https://github.com/tinycreative/react-native-intercom/pull/370
