### ISSUE TITLE
Crash app on Open Large Images on Chat

### ISSUE THREAD

**Issue by marcoaureliovrs** [tinycreative/react-native-intercom#371]
Hello everyone, everything good

I'm having trouble opening large / long images in the Intercom chat, when I receive an image in this feature the application closes without giving any feedback, the debug logs simply do not capture anything.

Anyone with the same problem could reinforce this issue so that we know if it impacts everyone or if it is an integration problem on my part.

**Comment by Br1an-Boyle** [comment]
Please get in touch with Intercom customer support. We can investigate this issue for you. It’s unlikely to be an integration issue for you.
