### ISSUE TITLE
Missing Release 16.0.0 on repository

### ISSUE THREAD

**Issue by gabriel-franzoni-pier** [tinycreative/react-native-intercom#373]
There's no commit link/tag to release 16.0.0 on this repository

**Comment by willdady** [comment]
Same for 14.0.0, in fact nothing > 13.2.0?

**Comment by willdady** [comment]
@browniefed is this something you can fix? Asking you since it looks like you most-recently bumped the version in package.json. Seems like tags aren't being added which makes navigating the repo difficult. Cheers.
