### ISSUE TITLE
Implementation: Mobile Carousels

### ISSUE THREAD

**Issue by ghost** [tinycreative/react-native-intercom#374]
Have you see the new "[Mobile Carousels](https://www.intercom.com/mobile-carousels)" feature that they just came out with?

How hard would this be to implement? I'd be interested in sponsoring this addition if its a lot of work.

**Comment by Br1an-Boyle** [comment]
👋 Mobile Carousels is available by simply updating the Intercom iOS sdk dependency time v7.1.0. 
Should just work out if the box, no configuration or code changes required. 🙂

**Comment by aditibarbhai** [comment]
> 👋 Mobile Carousels is available by simply updating the Intercom iOS sdk dependency time v7.1.0.
> Should just work out if the box, no configuration or code changes required. 🙂

Were you successfully able to do this? How did you install the Intercom SDK? 

When I upgraded to the latest Intercom via cocoapods, I get an error when running `react-native run-ios`:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UIPointerLiftEffect", referenced from:
      objc-class-ref in Intercom(ICMPointerInteraction.o)
  "_OBJC_CLASS_$_UIPointerStyle", referenced from:
      objc-class-ref in Intercom(ICMPointerInteraction.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


** BUILD FAILED **


The following build commands failed:
	Ld build/Butter/Build/Products/Debug-iphonesimulator/MyAppName.app/MyAppName normal x86_64
(1 failure)
```
See more: https://github.com/tinycreative/react-native-intercom/issues/378#issuecomment-656299086

**Comment by Br1an-Boyle** [comment]
You need to make sure you’re using Xcode 11.4

**Comment by hamoudaarfaoui** [comment]
@bboyle18 do you know what minimum version on `react-native-intercom` supports `SDK 7.1.0+`, cause `react-native-intercom@17.0.0` `requries react-native@0.62` (which should be mentioned) and not all user able to upgrade `react-native`

**Comment by dancixx** [comment]
Hi guys,

is there any way to use this feature in this library?

**Comment by dmarkowski** [comment]
I have the similar problem with react-native 0.62.2 and react-native-intercom 19.0.0 and Xcode 11.5

`
ld: warning: Could not find or use auto-linked framework 'UniformTypeIdentifiers'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PHPickerConfiguration", referenced from:
      objc-class-ref in Intercom(IIMPhotosInput.o)
  "_OBJC_CLASS_$_PHPickerFilter", referenced from:
      objc-class-ref in Intercom(IIMPhotosInput.o)
  "_OBJC_CLASS_$_PHPickerViewController", referenced from:
      objc-class-ref in Intercom(IIMPhotosInput.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by 77TecShaeer** [comment]
++++
