### ISSUE TITLE
IntercomEventEmitter.UNREAD_CHANGE_NOTIFICATION Error

### ISSUE THREAD

**Issue by teodora-techpods** [tinycreative/react-native-intercom#376]
Hi there, I'm trying to get Intercom chat working on our project. Followed all of the instructions from the docs setting up manually the configuration for both Android and iOS but I can't seem to get it working...this error keeps appearing : 
`null is not an object (evaluating 'IntercomEventEmitter.UNREAD_CHANGE_NOTIFICATION') `

Keep in mind we're using Expo in our project but we're using the bare workflow so integrating Intercom from what I've read should not be an issue..

My app config:
```
"expo": "~36.0.0",
"react-native": "~0.61.4",
"react-native-intercom": "^16.0.0",
```

**Comment by HigorAlves** [comment]
Same error here

**Comment by dziter** [comment]
Same problem, but I just tested on iOS. I am not using Expo, bare RN project.
@teodora-techpods : Did you solve your problem?

Xcode version 11.5, no error in Xcode. Only the red error screen on React Native.

Cocoapods + react-native link: FAILED
Cocoapods + Manual link: FAILED
Manually downloading .zip framework from Intercom website and following their instructions: FAILED

#109 is not solving the issue for me.

Thanks for any help.

**Comment by tedselig** [comment]
I have this problem also

**Comment by tedselig** [comment]
@dziter @teodora-techpods I fixed the problem. I un-ejected expo, upgraded to the latest expo 38 version, ejected expo, ran `npm install react-native-intercom`  did the steps in option 3 of the Install for ios intercom docs found here (https://developers.intercom.com/installing-intercom/docs/ios-installation#section-option-3-install-intercom-manually), did `npm install`, `cd ios`,`pod update`,`pod install` and then went to Xcode and built the workspace, then pressed the play button and the simulator popped up with the intercom chat. It still doesn't work when I run the simulator through expo though but it's a different error now.

**Comment by FlawaCLV** [comment]
@teodora-techpods have you solved your issue? I'm using Expo and get this error as well... :/

**Comment by Arkan4ik** [comment]
@browniefed I faced with the same issue but I dont use expo.

**Comment by browniefed** [comment]
Intercom has released an official package for React Native. Please use it.

https://github.com/intercom/intercom-react-native

**Comment by Arkan4ik** [comment]
@browniefed I solved this issue. I used the official package but there is no 'issues' tab in that repository.

**Comment by binismail** [comment]
Hi Guys, I'm still facing the same error even with `@intercom/intercom-react-native`, any way out please

**Comment by browniefed** [comment]
@binismail this repo has nothing to do with the official repo. Please contact Intercom

**Comment by aldbgh** [comment]
I have the exact same issue, using:
@intercom/intercom-react-native": "^3.0.3"
"expo": "~47.0.8"

I would be very happy for a solution, this is blocking us from migrating our project to expo
