### ISSUE TITLE
run-ios error: Undefined symbols for architecture x86_64 - Intercom

### ISSUE THREAD

**Issue by aditibarbhai** [tinycreative/react-native-intercom#378]
The project I am working on used to have a deployment target of ios 9 - `IPHONEOS_DEPLOYMENT_TARGET = 9.0`  and was using `"react-native-intercom": "13.1.0"`

Currently, I'm trying to upgrade to the latest version (16.0.0). I set the deployment target to ios 10, but I'm getting the following error when I do `pod install`:
```
[!] CocoaPods could not find compatible versions for pod "Intercom":
  In snapshot (Podfile.lock):
    Intercom (= 5.5.1, ~> 5.0)

  In Podfile:
    react-native-intercom (from `../node_modules/react-native-intercom`) was resolved to 16.0.0, which depends on
      Intercom (~> 6.1.0)

Specs satisfying the `Intercom (= 5.5.1, ~> 5.0), Intercom (~> 6.1.0)` dependency were found, but they required a higher minimum deployment target.
```

What is the minimum deployment target for the latest version? I couldn't find it in the READ.ME

**Comment by hemche** [comment]
Update `Intercom (= 5.5.1, ~> 5.0)` to `Intercom (~> 6.1.0)` in `podfile.lock`
Minimum deployment target is 10.

**Comment by aditibarbhai** [comment]
> Update `Intercom (= 5.5.1, ~> 5.0)` to `Intercom (~> 6.1.0)` in `podfile.lock`
> Minimum deployment target is 10.

I tried doing this and ran into more errors, so I deleted the `podfile.lock` and tried running `pod install` again, but still getting this error:

```
[!] CocoaPods could not find compatible versions for pod "react-native-intercom":
  In Podfile:
    react-native-intercom (from `../node_modules/react-native-intercom`)

Specs satisfying the `react-native-intercom (from `../node_modules/react-native-intercom`)` dependency were found, but they required a higher minimum deployment target.
```
I've set the `IPHONEOS_DEPLOYMENT_TARGET = 12.2`, so not sure why this is happening...?

**Comment by hemche** [comment]
Also, have this line in podfile at the beginning.

`platform :ios, '10.0'`

**Comment by aditibarbhai** [comment]
Thanks, I was able to `pod install` successfully (I ended up upgrading to the 7.1 PR:`"react-native-intercom": "tinycreative/react-native-intercom#04007d2"`). Now, however, I get the following error when I run `react-native run-ios`:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UIPointerLiftEffect", referenced from:
      objc-class-ref in Intercom(ICMPointerInteraction.o)
  "_OBJC_CLASS_$_UIPointerStyle", referenced from:
      objc-class-ref in Intercom(ICMPointerInteraction.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Br1an-Boyle** [comment]
@aditibarbhai You'll need to make sure you're using Xcode 11.4 to build your app.

**Comment by aditibarbhai** [comment]
Resolved by upgrading Xcode. Thanks!

**Comment by 77TecShaeer** [comment]
++++
