### ISSUE TITLE
Implementing a test workspace in Intercom

### ISSUE THREAD

**Issue by agnieszkabugla** [tinycreative/react-native-intercom#381]
I have implemented a test workspace in Intercom (https://www.intercom.com/help/en/articles/188-create-a-test-workspace-in-intercom)

So now i have two AppIds: one for PRD and the other for DEV and TST.

How can i implement it now in AppDelegate.m and MainApplication.java so that Intercom AppId is dynamic, based on my environment?

**Comment by minhnc** [comment]
You can define intercom key & id in different env files with [react-native-config](https://github.com/luggit/react-native-config), and use them in AppDelegate.m and MainApplication.java.

**Comment by agnieszkabugla** [comment]
yes, i did it this way. I used react-native-config ;)
