### ISSUE TITLE
17.0.0 - build error

### ISSUE THREAD

**Issue by Lukkub** [tinycreative/react-native-intercom#383]
On version 17.0.0 following error occurs during build process:

```
'React/RCTUtilsUIOverride.h' file not found
```

Connected with `IntercomWrapper.m` file changes that were merged together with intercom version update.

**Comment by romainbriand** [comment]
I've got the same error

**Comment by EricMcRay** [comment]
`React/RCTUtilsUIOverride.h` this file comes with react native version 0.62. Probably, your react-native version is lower than that.

**Comment by romainbriand** [comment]
@EricMcRay absolutely, we are still using 0.61 so it makes sense. Thanks for your help! 👍 
Maybe this this kind of minimum requirement should be mentioned in the docs somewhere.

**Comment by sakarisson** [comment]
In general, a changelog would be super useful.

**Comment by vgm8** [comment]
Is there any way to support older versions of react-native?

**Comment by beinginorbit** [comment]
Looks like we need to downgrade to version 15 of this plugin for it to work as the use of this Util was implemented then https://github.com/tinycreative/react-native-intercom/commit/d1655faafde23e646a91592cff56fdefbe6e33dc
