### ISSUE TITLE
Error /react-native/React/Modules/RCTEventEmitter.h:8:9: 'React/RCTBridge.h' file not found

### ISSUE THREAD

**Issue by alexsilvadev** [tinycreative/react-native-intercom#385]
Has anyone had this error and knows how to fix it?

**I am using:**
react-native: 0.62.1
react-native-intercom: 17.0.0
xcode: 10.3

<img width="1277" alt="Captura de Tela 2020-07-23 às 10 30 34" src="https://user-images.githubusercontent.com/61877680/88292609-3ef92280-ccd0-11ea-8203-7babbc209ebe.png">

<img width="1280" alt="Captura de Tela 2020-07-23 às 10 30 47" src="https://user-images.githubusercontent.com/61877680/88292679-533d1f80-ccd0-11ea-9b31-2ef33feda348.png">

**Comment by VincentQuillien** [comment]
I had the same issue and I resolved it by setting the correct path to React's headers in the header search paths of the library.
It should be something like this: `${SRCROOT}/../../../ios/Pods/Headers/Public/**` (recursive)

**Comment by surgetom** [comment]
> I had the same issue and I resolved it by setting the correct path to React's headers in the header search paths of the library.
> It should be something like this: `${SRCROOT}/../../../ios/Pods/Headers/Public/**` (recursive)

What version of "react-native-intercom" are you using? I tried adding the the path but it didnt work for me.

**Comment by surgetom** [comment]
> Has anyone had this error and knows how to fix it?
> 
> **I am using:**
> react-native: 0.62.1
> react-native-intercom: 17.0.0
> xcode: 10.3
> 
> <img alt="Captura de Tela 2020-07-23 às 10 30 34" width="1277" src="https://user-images.githubusercontent.com/61877680/88292609-3ef92280-ccd0-11ea-8203-7babbc209ebe.png">
> 
> <img alt="Captura de Tela 2020-07-23 às 10 30 47" width="1280" src="https://user-images.githubusercontent.com/61877680/88292679-533d1f80-ccd0-11ea-9b31-2ef33feda348.png">

did this work for you ?

**Comment by surgetom** [comment]
> > Has anyone had this error and knows how to fix it?
> > **I am using:**
> > react-native: 0.62.1
> > react-native-intercom: 17.0.0
> > xcode: 10.3
> > <img alt="Captura de Tela 2020-07-23 às 10 30 34" width="1277" src="https://user-images.githubusercontent.com/61877680/88292609-3ef92280-ccd0-11ea-8203-7babbc209ebe.png">
> > <img alt="Captura de Tela 2020-07-23 às 10 30 47" width="1280" src="https://user-images.githubusercontent.com/61877680/88292679-533d1f80-ccd0-11ea-9b31-2ef33feda348.png">
> 
> did the solution work for you ?
