### ISSUE TITLE
Numerous congratulations alerts

### ISSUE THREAD

**Issue by afilp** [tinycreative/react-native-intercom#39]
I get alerts that say "Your iOS app is now integrated with the Intercom platform".

See exactly the same issue on the "cordova" package here:
https://github.com/intercom/intercom-cordova/issues/83

How can this be solved? The app cannot be released when such alerts appear, we need to find a way to suppress them.

Thank you in advance!

**Comment by IcyEagle** [comment]
@afilp I'm not sure what helped me with this but try to perform the next steps:
1. Remove other push notification plugins (for example phonegap-push-plugin, onesignal-push-plugin etc.). They may conflict with each other.
2. Make sure there is no multiple Intercom accounts with a single APN certificate. I had two so it was a mistake.

Finally I resolved the problem using intercom-push-plugin with forked version of phonegap-push-plugin provided by intercom team (see intercom docs).

Good luck.

**Comment by jtreanor** [comment]
Hi @afilp and @IcyEagle 

James here from Intercom. Unfortunately I haven't been able to reproduce this issue. However, I'm happy to help track this down. I'm not sure how this could be related to push notifications.

**Comment by jtreanor** [comment]
We have made some updates in 3.0.13 to how the alert is displayed.
Let me know if you are still seeing an issue.

**Comment by afilp** [comment]
@jtreanor Hi, I see that npm is still on 3.0.3:
https://www.npmjs.com/package/react-native-intercom

Can you update please so that I can "npm i" your latest version?

**Comment by kageurufu** [comment]
@aflip, @jtreanor is not the owner of this project, you need to update your iOS Intercom framework, either through cocoapods if you installed that way, or by following the relevant guide for installation from https://github.com/intercom/intercom-ios

**Comment by amitgajjar510** [comment]
Hi there,
I am facing the same issue. I am using OneSignal Push Notification for my app and I can't remove it as per requirements. 
I have only one application registered on Intercom platform.
Kindly help me to resolve this issue.

Thank you in advance.
:) :) :)
