### ISSUE TITLE
Android (APK) and iOS (ipa) cannot receive push notifications when build. App is downloaded via app center.

### ISSUE THREAD

**Issue by aibrahim3546** [tinycreative/react-native-intercom#390]
Push notification working fine for both devices when running in development mood.

How ever after build and install it properly from app center. It's not working.

Here is the step.

1. build release APK and ipa files for both platform.
2. Upload both files to microsoft app center.
3. Install the app properly from microsoft app center
4. Push notification is not working. However when i open the app i can receive the message.

Any idea? Anyone encounter this?

**Comment by Br1an-Boyle** [comment]
@aibrahim3546 are you sure you have a production push cert uploaded to intercom, instead of just a development one?

**Comment by aibrahim3546** [comment]
@bboyle18 I used development cert for TEST workspace. It is working find on device in debug mode. Only not working when i Install it via appcenter.

Production is working fine. I can receive notification from my testflight app.
