### ISSUE TITLE
Intercom not displaying, loading spinner only

### ISSUE THREAD

**Issue by PatrickYoung03** [tinycreative/react-native-intercom#403]
Hi i have followed the steps to install Intercom into my react native project but i am only getting a blank screen when calling any of the methods

![simulator_screenshot_48BC21EE-A459-4ACF-BF50-0FAAE2D1CC91](https://user-images.githubusercontent.com/45243614/95344541-a8410880-08b1-11eb-9f87-a45af37d9590.png)
<img width="504" alt="Screenshot 2020-10-07 at 15 28 19" src="https://user-images.githubusercontent.com/45243614/95344598-bbec6f00-08b1-11eb-941a-46d8d7f1544e.png">

"react-native": "0.63.2"
"react-native-intercom": "^18.0.0",

APP.DELEGATE
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [Intercom setApiKey:@"**SDK_IOS**" forAppId:@"**APP_ID**"];
›
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [Intercom registerUnidentifiedUser];
}

**Comment by mccooll** [comment]
Try it on a physical hardware device.

**Comment by mellisdesigns** [comment]
I tried on my actual device and also have the same problem with `displayMessageComposer()` popping up. I have registered the users and I am also able to get to that screen by going through the `displayMessageComposer()` flow first. No errors are being caught when try to call the function `displayMessageComposer()`. IOS pops up the loading ui and does not progress. Android does not show any screen when calling it.

EDIT:
Just an update, if you are using staging your IOS and Android SDK Api Key will change as well as the APP Key

Solution:
Check that you have replaced your INTERCOM_APP_KEY and INTERCOM_API_KEY if you are using a staging environment.

**Comment by mikevercoelen** [comment]
I'm having the same problem here, just infinitely loading.

@mellisdesigns Did you manage to get it working by using different keys?

**Comment by mellisdesigns** [comment]
@mikevercoelen yeah, just had to double check the intercom keys which are different for android and ios as well as for each environment, staging or prod.

**Comment by mikevercoelen** [comment]
@mellisdesigns got it, thanks for letting me know!

**Comment by akinolu52** [comment]
@mellisdesigns pls how'll i get the keys for those environment, I'm having the same issue
