### ISSUE TITLE
In RN : 0.63 ,This version of Intercom for iOS supports iOS 10.0 upwards.

### ISSUE THREAD

**Issue by kamyab-tatva** [tinycreative/react-native-intercom#404]
I am error like
  **"/ios/Intercom.framework/Headers/Intercom.h:14:2: This version of Intercom for iOS supports iOS 10.0 upwards."**
  Version : 
  "react": "16.13.1",
  "react-native": "0.63.3",
  "react-native-intercom": "^18.0.0"

![Inkeddownload (2)_LI](https://user-images.githubusercontent.com/60596229/96126611-ccd05c80-0f11-11eb-923f-06b854ce0042.jpg)

**Comment by slopez93** [comment]
@kamyab-tatva  In my case i put "Deployment info -> target" to 10.0 and it work ! 🚀

**Comment by surgetom** [comment]
> I am error like
> **"/ios/Intercom.framework/Headers/Intercom.h:14:2: This version of Intercom for iOS supports iOS 10.0 upwards."**
> Version :
> "react": "16.13.1",
> "react-native": "0.63.3",
> "react-native-intercom": "^18.0.0"
> 
> ![Inkeddownload (2)_LI](https://user-images.githubusercontent.com/60596229/96126611-ccd05c80-0f11-11eb-923f-06b854ce0042.jpg)

@kamyab-tatva How did you solve the 'React/RCTBridge.h' file not found error?
also which install method did you do?  pods or manual ? 

Regards Tom
