### ISSUE TITLE
Could not find com.android.support:recyclerview-v7:24.2.1

### ISSUE THREAD

**Issue by afilp** [tinycreative/react-native-intercom#41]
Any ideas why we are getting this error message upon compiling on Android? (the compilation fails)

> A problem occurred configuring project ':react-native-intercom'.
> Could not resolve all dependencies for configuration ':react-native-intercom:_debugCompile'.
>       > Could not find com.android.support:recyclerview-v7:24.2.1.

**Comment by joehoyle** [comment]
@afilp could you document how you fixed this?
