### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by cristianrosu** [tinycreative/react-native-intercom#416]
I tried to implement this library but there are so many issues with it that it's pretty much unusable. Has anyone tried to use this successfully? Any plans on updating it?

**Comment by michaelVictoriaDev** [comment]
still no answer :/ its now 2021.

**Comment by nabilfreeman** [comment]
Works well for us on a bunch of production apps. The notifications were a little bit hard to get working, but the rest is totally good. I recently integrated from scratch on a new app in summer 2021 so definitely still ok to use!
