### ISSUE TITLE
Issue with alerts after library integration

### ISSUE THREAD

**Issue by atrofimenko** [tinycreative/react-native-intercom#417]
Hello! In my project i'm using react-native-navigation for navigation. After integration of intercom i have a problems with default alerts usage in IOS. Need your help, if this library still maintained.
 Attempt to present <UIAlertController: 0x7f8a88851800> on <RNNStackController: 0x7f8a89045c00> (from <RNNStackController: 0x7f8a89045c00>) whose view is not in the window hierarchy.

**Comment by nathsimpson** [comment]
Having a similar issue. Alerts which are called in a screen with 'stackPresentation: modal' are not appearing.

Edit: This error is showing in Xcode logs...
`[Presentation] Attempt to present <UIAlertController: 0x7fd37c0e0c00> on <UIViewController: 0x7fd379c176f0> (from <UIViewController: 0x7fd379c176f0>) which is already presenting <RNSScreen: 0x7fd381254bd0>.`

System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 82.79 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.4 - /var/folders/k6/d6gp0_p97nx1cft5tbywl3r80000gn/T/yarn--1619047970843-0.7069985906549368/node
    Yarn: 1.22.10 - /var/folders/k6/d6gp0_p97nx1cft5tbywl3r80000gn/T/yarn--1619047970843-0.7069985906549368/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/USERNAME/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by ajaykumar97** [comment]
Hey guys!
Any luck on this?
