### ISSUE TITLE
Support for the latest intercome sdk 9.+

### ISSUE THREAD

**Issue by JDMathew** [tinycreative/react-native-intercom#422]
Is it possible to update packages to added support for the latest intercom skd? If not what is the latest sdk version react-native-intercom supports? I seems to be having app crashes on sdk 9.+ in release mode on android. 

Please also update the readme to reflect the latest sdk version currently it is version 5 but I see packages referencing v7+
```
dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation 'io.intercom.android:intercom-sdk-base:7.+'
}
```

**Comment by export-mike** [comment]
@JDMathew update the podspec and the build.gradle and see how it behaves

**Comment by JDMathew** [comment]
@export-mike `9.+` caused crashes on android. I have been running `7.+` on android and `~> 8.0.0` on iOS since Jan with no issues.

**Comment by export-mike** [comment]
likely a breaking change on the android sdk that needs updating

**Comment by JDMathew** [comment]
Yeah, I as far as I remember it was causing the app to crash on android as soon as hitting Intercom API (I was doing this on Login).  I would need to upgrade to `9+` again to confirm. The version of `react-native-intercom` I have is `^18.0.0`. These app crashes may have only been a physical device thing and so I think I picked it up when testing builds for production.

**Comment by akshayLuthraDev** [comment]
Thanks for a quick fix on Android release mode. I have downgraded the package to version 18.0.0 and used sdk 7.+ which is not crashing the Android app now, but the UI of the Intercom message screen is distorted. 
Have you also faced this UI issue?

**Comment by akshayLuthraDev** [comment]
@JDMathew You can check the issue thread https://github.com/tinycreative/react-native-intercom/issues/441 , and make the Android run with the latest package version.

**Comment by JDMathew** [comment]
@akshayLuthraDev, Thanks for the link, I'll be sure to upgrade when we move the project into the next phase of development. I did not have issues with UI on the intercome message screen but may have not tested a wide enough range of devices.

**Comment by ws7one** [comment]
> Thanks for a quick fix on Android release mode. I have downgraded the package to version 18.0.0 and used sdk 7.+ which is not crashing the Android app now, but the UI of the Intercom message screen is distorted. Have you also faced this UI issue?

I have tried everything else. It seems like, this is the only configuration this does't seem to break the build or crash the app. Even tried the new library, app kept crashing. Anyone, any ideas?
