### ISSUE TITLE
App Size Drastically Increased

### ISSUE THREAD

**Issue by hbole** [tinycreative/react-native-intercom#423]
Hi All,

I have used this package to integrate intercom in my react-native app.
Earlier my app size was around 35 - 36 MB, now after the intercom configuration the app build is now around 80+ MBs.
Is there a way to reduce the app size. I suspect this size increase primarily due to the sdk.

Please help

**Comment by nicoburns** [comment]
Is this Android or iOS. If your issue is on Android then you may want to look into using Android App Bundles.

**Comment by grifotv** [comment]
I had the same in Android. I’ll look into android app bundle as suggested.

**Comment by grifotv** [comment]
Following @nicoburns advice, after generating `.aab` insteak of `.apk` the Android app size has drastically decreased from over 40MB to 17MB.

 Based on that I think this issue should be closed.
