### ISSUE TITLE
The last version of the lib is supporting Mobile Carousels but triggering it programmatically is missing

### ISSUE THREAD

**Issue by paomosca** [tinycreative/react-native-intercom#425]
Mobile Carousels are already supported but due the version of the Sdk used there is no access to the code trigger. any plan to update the sdks?

**Comment by bradenpowers** [comment]
Looking at some documentation, I see this https://developers.intercom.com/installing-intercom/docs/cordova-phonegap-configuration#present-a-carousel-programmatically. I tried it and this doesn't work for this package.

**Comment by export-mike** [comment]
https://github.com/tinycreative/react-native-intercom/pull/431 added

**Comment by paomosca** [comment]
thanks @export-mike looking forward to seeing it merged!! <3
