### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by thomas-forster1** [tinycreative/react-native-intercom#429]
Hi guys,

`"react": "16.13.1",`
`"react-native": "0.63.3",`
`"react-native-intercom": "^18.0.0",`

**issue**
after calling `Intercom.logout()` i'm still able to send messages to the user via Intercom Dashboard. 

how i'm using `'react-native-intercom'`

after a user logs in I do the following:

`Intercom.logout()`
`Intercom.registerUnidentifiedUser()`
`Intercom.registerIdentifiedUser()`
`Intercom.updateUser()`
       
You might ask why I logout then registerUnidentifiedUser then registerIdentifiedUser. This is a hack to get user details to update.

when a user logs out I call:
`Intercom.logout()`

the user will now be back on the login screen of my app. But I can still push messages to the user. Which I shouldn't be able to do. 

does anyone have a solution to the logout issue?

Thanks in advance

**Comment by Ahmedhamed77** [comment]
how did you solve that ?
