### ISSUE TITLE
Could not find com.android.tools.build:gradle:4.1.2.

### ISSUE THREAD

**Issue by yogendrakumar96** [tinycreative/react-native-intercom#434]
I am getting this error while running my app on android studio using physical device and I am unable to trace it why the build is failing by showing this type of error
My build.gradle file  looks like this :

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath 'com.google.gms:google-services:4.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
    }
}

**Comment by joseph-jordan** [comment]
deleting node_modules and reinstalling worked for me

**Comment by tohure** [comment]
deleting .gradle folder in your home_folder. Then, sync your project again. Works for me
