### ISSUE TITLE
Release notes missing for new releases

### ISSUE THREAD

**Issue by walterholohan** [tinycreative/react-native-intercom#435]
I just noticed that this library has stopped publishing Github releases since v13.4.1. Is this something that you plan on reintroducing as it can be difficult to understand what is included in new releases if no release notes or changelog can be found. 

Ive noticed on NPM that the latest version is `19.0.0` but on Github the latest release is `13.4.1`

**Comment by AlphaJuliettOmega** [comment]
This has been an issue for at least two months (release of 19)

I was using 18 for a long time but after noticing 19 on a Yarn Outdated I tried to find information on it, it's discerning that there are no release notes to be found
