### ISSUE TITLE
Intercom.presentCarousel Problem

### ISSUE THREAD

**Issue by ahmedmshatat** [tinycreative/react-native-intercom#437]
when trying use Intercom.presentCarousel, an error appear "TypeError: _reactNativeIntercom.default.presentCarousel is not a function. (In '_reactNativeIntercom.default.presentCarousel("4444444")', '_reactNativeIntercom.default.presentCarousel' is undefined)".
 Is there anyway to solve this ?
this version i use "react-native-intercom": "^19.0.0"
![simulator_screenshot_6240C99D-5BFC-4E78-A445-5C901EBCE5C8](https://user-images.githubusercontent.com/69888974/111295908-94fe4a00-8654-11eb-9caa-6596b3f16f43.png)

**Comment by jaexplorer** [comment]
I'm having this issue too. Any update?

**Comment by export-mike** [comment]
Hey I'm not sure whats going with this repo, it appears npm is on 19.x.x and the master branch is on 17.x.x ?

**Comment by mnsrv** [comment]
> Hey I'm not sure whats going with this repo, it appears npm is on 19.x.x and the master branch is on 17.x.x ?

Hello @export-mike, I checked and the only difference is version in package.json, I created pull request to fix this #442
