### ISSUE TITLE
Building iOS failed

### ISSUE THREAD

**Issue by ngkhoawork** [tinycreative/react-native-intercom#44]
I followed instructions mentioned in README.md but I couldn't build the iOS app.

Here's Steps that I followed.
1. npm install react-native-intercom
2. rnpm link
3. react-native run-ios

`The following build commands failed:
    CompileC ../ios/build/Build/Intermediates/RNIntercom.build/Debug-iphonesimulator/RNIntercom.build/Objects-normal/x86_64/IntercomWrapper.o IntercomWrapper.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

`#import <Intercom/Intercom.h>` in IntercomWrapper.m file of react-native-intercom npm module causes above build error.

Did i miss any step that need to be done before do `react-native run-ios`?

**Comment by kageurufu** [comment]
You need to download and link https://github.com/intercom/intercom-ios either manually, or through cocoapods

Linking react-native-intercom for ios through cocoapods handles this for you automatically

**Comment by ngkhoawork** [comment]
Hello @kageurufu 

Thank you for your reply.

I followed your instructions.
1. npm install react-native-intercom
2. create pod file in /iOS/ with following contents
   `target "Grow" do
   pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'
   end`
3. run pod install in /iOS folder and I'm able to install pod successfully.
4. When I do react-native run-ios I still get error( but it is different from last one I had before)

```
....

CTImage.a(RCTImageLoader.o)
      _RCTDecodeImageWithData in libRCTImage.a(RCTImageUtils.o)
  "__RCTLogNativeInternal", referenced from:
      -[RCTActionSheetManager showActionSheetWithOptions:callback:] in libRCTActionSheet.a(RCTActionSheetManager.o)
      -[RCTActionSheetManager showShareActionSheetWithOptions:failureCallback:successCallback:] in libRCTActionSheet.a(RCTActionSheetManager.o)
      -[RCTActionSheetManager actionSheet:clickedButtonAtIndex:] in libRCTActionSheet.a(RCTActionSheetManager.o)
      -[RCTLocationObserver getCurrentPosition:withSuccessCallback:errorCallback:] in libRCTGeolocation.a(RCTLocationObserver.o)
      _checkLocationConfig in libRCTGeolocation.a(RCTLocationObserver.o)
      -[RCTImageLoader setImageCache:] in libRCTImage.a(RCTImageLoader.o)
      -[RCTImageLoader imageURLLoaderForURL:] in libRCTImage.a(RCTImageLoader.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
    Ld build/Build/Products/Debug-iphonesimulator/Grow.app/Grow normal x86_64
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/Grow.app
An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/youd/Library/Developer/CoreSimulator/Devices/D08139A3-3546-4ACF-B140-8F76621A55B7/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/3E9939AD-E1EE-4392-A880-9D382C5640D6/Grow.app/Grow : No such file or directory
Launching org.reactjs.native.example.Grow
org.reactjs.native.example.Grow: 60844

```

Any ideas?

**Comment by ngkhoawork** [comment]
Solved by integrating intercom-ios framework manually.
