### ISSUE TITLE
Use of undeclared identifier 'Intercom' in AppDelegate.m

### ISSUE THREAD

**Issue by dulcemunoz** [tinycreative/react-native-intercom#447]
Me encuentro utilizando React-native y cuando realizo la implementación en iOS y trata de generar el .IPA me arroja el siguiente error    Use of undeclared identifier 'Intercom'           dentro de las lineas de código donde declaré INTERCOM en el AppDelegate.m

#import "Intercom/Intercom.h"
![Captura de Pantalla 2021-06-08 a la(s) 15 44 36](https://user-images.githubusercontent.com/69825936/121254920-7208be00-c870-11eb-8667-354f71641bad.png)

Lo importe de esa manera en un principio

**Comment by FlawaCLV** [comment]
Same issue for me. @dulcemunoz did you manage to solve it?

**Comment by dulcemunoz** [comment]
Hola! @FlawaCLV  si logré solucionarlo tuve que declarar antes de la etiqueta #if def y lo tuve que realizar de la siguiente manera
...
#import <Intercom/intercom.h>
...
// Intercom
[Intercom setApiKey:@"IOS-API-KEY" forAppId:@"APP-ID"];
...
- (void)application:(UIApplication *)application
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  // Intercom
  [Intercom setDeviceToken:deviceToken];
}

Ademas de añadir el archivo swift y el puente ya que me encontraba desarrollando con React-native.

Disculpa la demora para contestar, pero si puedo ayudar aún más hazmelo saber :+1:
