### ISSUE TITLE
Expo config plug-in

### ISSUE THREAD

**Issue by nandorojo** [tinycreative/react-native-intercom#448]
It would be awesome to support expo's new config plug-in system. That would allow this library to work with expo SDK 41+.

**Comment by giaset** [comment]
Bumping this, as this would be amazing for us as well!

**Comment by SimenB** [comment]
https://github.com/tinycreative/react-native-intercom/commit/982e6344c6ae91621887e510cf7ad8ca2797f20d

**Comment by cmaycumber** [comment]
Still a WIP but if anyone needs it for the official `react-native-intercom` package: https://github.com/cmaycumber/config-plugin-react-native-intercom.

**Comment by nandorojo** [comment]
For anyone else facing issues with Expo, I ended up using a modal with a web view to our website that opens intercom

**Comment by nandorojo** [comment]
Thanks for sharing that @cmaycumber!
