### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by zibs** [tinycreative/react-native-intercom#45]
I'm trying to use this library on a react-native 0.34.0 project, and I cannot get this library to work. I've fought through a number of problems, but am still unable to get it working. I am following the instructions thoroughly.
I install the library `npm install react-native-intercom --save`
I link the library `react-native link` 
I use cocoapods to install the app `'react-native-intercom', :path => '../node_modules/react-native-intercom'`.

I've tried many variations on this theme, but I either end up getting a 'Dependency analysis error, recursion etc.' or 'Intercom/Intercom.h cannot be found' error, or a duplicate symbols error, or a linker error of some sorts. 

I've even tried just manually downloading Intercom and installing the framework, and then trying to use the library on top of the manually downloaded/installed framework.

Any tips on how to make this library work? 

Update:

Solved this by manually installing Intercom, no pods, and then using installing this package, and react-native linking it afterwards. Cheers.

**Comment by vinicius-sabadim** [comment]
I installed by the manual installing without pods and after that, linking using `react-native link`. This worked for me too.

**Comment by ogtfaber** [comment]
Pods don't work for me either. Also, having errors with running the script: https://github.com/intercom/intercom-ios/pull/185

Are you able to add the script without any issues @vinicius-sabadim @zibs ?
