### ISSUE TITLE
Remove bintray maven repository

### ISSUE THREAD

**Issue by JulianKingman** [tinycreative/react-native-intercom#454]
In the build.gradle file, it uses the following dependency under repositories:
```
maven {
     url 'https://dl.bintray.com/intercom/intercom-maven'
   }
```
Bintray has been shut down and will no longer work.

**Comment by GeoFro** [comment]
Any update on this?

**Comment by JulianKingman** [comment]
I've upgraded to intercom's official library, it's not too hard. @intercom/intercom-react-native

**Comment by walterholohan** [comment]
Any update on this? Should we migrate to the official library from Intercom or will this library be maintained?

**Comment by LordParsley** [comment]
Related build error: https://github.com/tinycreative/react-native-intercom/issues/456
