### ISSUE TITLE
Where is the 22.0.1 mentioned here https://yarnpkg.com/package/react-native-intercom

### ISSUE THREAD

**Issue by mlostekk** [tinycreative/react-native-intercom#461]
I cant find the tag/release. Where can i find the version `22.0.1`

**Comment by mlostekk** [comment]
the package json version does not seem to be coherent with the git tags

**Comment by mlostekk** [comment]
Oh, no. I was looking for the 22.0.1.. sorry for confusion. The repo just tells me about 21.x

**Comment by anehustorov** [comment]
did you find version 22.0.1?

**Comment by mlostekk** [comment]
No i did not, i ended up using the zip from yarnpkg

**Comment by mlostekk** [comment]
@browniefed why was this issue closed? is there no way to get the `22.0.1`?!
