### ISSUE TITLE
502 error during the build for android

### ISSUE THREAD

**Issue by yavorsky** [tinycreative/react-native-intercom#463]
Recently, I can't build my project. The error is appearing referring to the repo is not available.

https://dl.bintray.com/intercom/intercom-maven/com/facebook/react/react-native/maven-metadata.xml is returning 504 status code.

Error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-intercom:generateReleaseRFile'.
> Could not resolve all task dependencies for configuration ':react-native-intercom:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-intercom
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://dl.bintray.com/intercom/intercom-maven/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/intercom/intercom-maven/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/intercom/intercom-maven/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

### Environment
npm version: 18
io.intercom.android:intercom-sdk-base:7.+

Tried different versions and the result is the same

**Comment by qburst-subins** [comment]
@yavorsky Facing the same issue since yesterday. Any updates on this? I am using v20.1.0
I think https://github.com/tinycreative/react-native-intercom/blob/master/android/build.gradle this file causes the issue.

**Comment by rickyalmeidadev** [comment]
Same issue here. It has stopped working suddenly.

**Comment by dmackinn** [comment]
My team is also unable to generate android builds because of this

**Comment by lzakrzewski** [comment]
hello @dmackinn, your PR seems to be fixing the issue :pray:

**Comment by dmackinn** [comment]
@browniefed would you be open to merging this in? I know there is an official Intercom package now but not everyone has migrated to it yet.

**Comment by browniefed** [comment]
This will be the last PR that I merge for this project. 

Please migrate to https://github.com/intercom/intercom-react-native as soon as you can

**Comment by browniefed** [comment]
react-native-intercom@21.1.1

**Comment by TamaraMalakhova** [comment]
> react-native-intercom@21.1.1
I had problem the same as in this issue but after updating I have another problem:

Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class kotlin.reflect.KClasses found in modules jetified-kotlin-reflect-1.1 (org.jetbrains.kotlin:kotlin-reflect:1.1.1) and jetified-kotlin-stdlib-1.4.32 (org.jetbrains.kotlin:kotlin-stdlib:1.4.32)

**Comment by qburst-subins** [comment]
Issue resolved when I use "https://github.com/intercom/intercom-react-native". Please try this

**Comment by TamaraMalakhova** [comment]
> https://github.com/intercom/intercom-react-native

This issue or mine?

**Comment by TamaraMalakhova** [comment]
> Issue resolved when I use "https://github.com/intercom/intercom-react-native". Please try this

It also haven't helped me
