### ISSUE TITLE
Replace call to registerForRemoteNotifications with setDevice

### ISSUE THREAD

**Issue by talkain** [tinycreative/react-native-intercom#5]
Intercom [v2.0.7](https://github.com/intercom/intercom-ios/blob/2.0.7/Intercom/Intercom.h#L438) was the last version that supported the `registerForRemoteNotifications` function. v2.1 deprecated this function and replaced it with `setDeviceToken`

From [v2.1](https://github.com/intercom/intercom-ios/blob/2.1/ios/Intercom.framework/Versions/A/Headers/Intercom.h#L73):

```

 ## How do push notifications work?

 The Intercom iOS SDK enables your users to receive push notifications for new messages. Simply call:

    - (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
        [Intercom setDeviceToken:deviceToken];
    }

 in your `didRegisterForRemoteNotificationsWithDeviceToken:` method once you have registered your app for 
 push notifications with the `UIApplicationDelegate`.
```

We should call `setDevice` and remove the [old call](https://github.com/asamiller/react-native-intercom/blob/0bdc2c45743a01d03669962660b511953a8170bc/iOS/IntercomWrapper.m#L158) (mentioned in #1)

**Comment by hojberg** [comment]
This issue prevents me from building..
<img width="257" alt="screen shot 2015-12-30 at 11 32 30 pm" src="https://cloud.githubusercontent.com/assets/2371/12058559/9e9047a0-af4d-11e5-8887-08116a7a7d6c.png">
