### ISSUE TITLE
Can we change the 'Api Key' dynamically from JavaScript after login?

### ISSUE THREAD

**Issue by afilp** [tinycreative/react-native-intercom#54]
Hello,

as per instructions, we initialize intercom inside MainApplication.java:
Intercom.initialize(this, "android_sdk-8ee58c77f126f7cb2f12319c116081723de30717e", "yq2easq1b");

However, how can we *dynamically* change the intercom api key while we are in the JavaScript side?

Why?

We need to use the intercom for our users, but there are customers that want to use their own Intercom for their end users. So, we need to change the api key dynamically depending on the login of the user.

Is this possible, somehow?

Thanks!

**Comment by browniefed** [comment]
I don't know if that is possible. Ask Intercom if it is.

**Comment by jtreanor** [comment]
Hi @afilp and @browniefed. I'm one of the engineers at Intercom.

Unfortunately changing the app or api key at runtime is not supported. This is because app specific setup takes place early in the lifecycle of the app.

**Comment by browniefed** [comment]
@jtreanor thanks for the info, sorry @afilp you will likely need to find another solution.

**Comment by afilp** [comment]
@jtreanor 

May I recommend a new feature then? 

I do not know the internals, but you could provide a new **method** to change who uses the Intercom (not necessarily the API key) at runtime. 

It could also be something like a "forwarder/subaccount", meaning that under my Intercom account I have setup "forwarders" that yield the server logic to another Intercom account (which handles someone else, not me). So, by running this method, while the app has the same API key it takes messages from a different account ("subaccount/forwarding account/whatever-name-it-will-be").

I am trying to find a solution here, as there may also be other use cases related to that.

Thanks!

**Comment by jtreanor** [comment]
Thanks @afilp. I'll make sure we consider this request.
