### ISSUE TITLE
Android: can't evaluate IntercomEventEmmiter.UNREAD_CHANGE_NOTIFICATION

### ISSUE THREAD

**Issue by tanujs-tech** [tinycreative/react-native-intercom#58]
with iOS its working fine but with android I'm getting the following error

![screen shot 2016-12-13 at 3 57 21 pm](https://cloud.githubusercontent.com/assets/23055028/21136748/e475bacc-c14c-11e6-9e2c-8de9177083bb.png)

I've setup react-native-intercom, and added dependencies in build.gradle as described in readme.

Thanks in advance!

**Comment by Piwaii** [comment]
Hello. I faced the same issue and I found this : https://github.com/tinycreative/react-native-intercom/issues/4 (last comment)

You need to add IntercomPackage on your MainApplication.java : 
- add import com.robinpowered.react.Intercom.IntercomPackage; 
- add new IntercomPackage like this : 
```
@Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new IntercomPackage() 
    );
  }
```

**Comment by seanadkinson** [comment]
I added the package, and am now getting an error: "Please call Intercom.initialize() before requesting the client".

If I work past it, I'll update this issue.

**Comment by MattyK14** [comment]
Unfortunately, I can't get past the UNREAD_CHANGE_NOTIFICATION error.

`new IntercomPackage()` is in the `getPackages()` in `MainApplication.java` along with `import com.robinpowered.react.Intercom.IntercomPackage;` `import io.intercom.android.sdk.Intercom;`
As well as in the `onCreate()` is `Intercom.initialize(this, API_KEY, APP_ID);`

`settings.gradle` has `include ':react-native-intercom'
project(':react-native-intercom').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-intercom/android')`

`app/build.gradle` has `compile "io.intercom.android:intercom-sdk-base:3.+"
    compile "io.intercom.android:intercom-sdk-fcm:3.+"`
