### ISSUE TITLE
IntercomWrapper.setBottomPadding is not a function

### ISSUE THREAD

**Issue by vinicius-sabadim** [tinycreative/react-native-intercom#59]
I'm trying to change the padding of messenger and this error happen. On iOS works fine.

![screen shot 2016-12-21 at 17 40 19](https://cloud.githubusercontent.com/assets/7515783/21403589/98e321ae-c7a4-11e6-803f-219312ae25b4.png)

**Update:** Looking on the `IntercomModule.java` there is no method to easy change the position of icon.

What you think is the best way to do this on Android?

**Comment by browniefed** [comment]
Submit a PR for it and I'll accept it

**Comment by mirtinika** [comment]
Hi! I did a tiny PR to fix add the`setBottomPadding` function on the `IntercomModule.java`.
Hope It looks good for you guys! 😊

**Comment by stevula** [comment]
Should this be closed now that #130 is merged?
