### ISSUE TITLE
Share extension on release mode: UNREAD_CHANGE_NOTIFICATION

### ISSUE THREAD

**Issue by adrianotadao** [tinycreative/react-native-intercom#62]
Anyone has a clue what is happening with my project? If a run on debugging mode, everything works fine but, when I run in release mode, the Extension raises this error.

Does this error really come from Intercom?

```
2017-01-19 11:44:59.896 MyShareEx[28356:4408998] Failed to inherit CoreMedia permissions from 28348: (null)
2017-01-19 11:45:00.108 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'u.UNREAD_CHANGE_NOTIFICATION')
2017-01-19 11:45:00.111 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'u.UNREAD_CHANGE_NOTIFICATION')
2017-01-19 11:45:00.112 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module (calling runApplication)
2017-01-19 11:45:00.122 MyShareEx[28356:4409019] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'u.UNREAD_CHANGE_NOTIFICATION')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'u.UNREAD_CH..., stack:
e@734:217
<unknown>@734:2802
n@2:545
<unknown>@726:162
n@2:545
<unknown>@718:284
n@2:545
<unknown>@376:243
n@2:545
<unknown>@12:185
n@2:545
i@2:266
global code@942:9
'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010eb21d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010dec021e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010eb8b2b5 +[NSException raise:format:] + 197
	3   MyShareEx                           0x000000010d6920fd RCTFatal + 393
	4   MyShareEx                           0x000000010d68b4a2 -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 515
	5   CoreFoundation                      0x000000010eaa844c __invoking___ + 140
	6   CoreFoundation                      0x000000010eaa82d1 -[NSInvocation invoke] + 289
	7   CoreFoundation                      0x000000010eac0326 -[NSInvocation invokeWithTarget:] + 54
	8   MyShareEx                           0x000000010d68f0cc -[RCTModuleMethod invokeWithBridge:module:arguments:] + 585
	9   MyShareEx                           0x000000010d6b63ea -[RCTBatchedBridge callNativeModule:method:params:] + 220
	10  MyShareEx                           0x000000010d6b5c46 __33-[RCTBatchedBridge handleBuffer:]_block_invoke.357 + 503
	11  libdispatch.dylib                   0x0000000112a16808 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x0000000112a3812e _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x0000000112a1d4cf _dispatch_queue_serial_drain + 1018
	14  libdispatch.dylib                   0x0000000112a1dc9f _dispatch_queue_invoke + 1118
	15  libdispatch.dylib                   0x0000000112a1e047 _dispatch_queue_override_invoke + 376
	16  libdispatch.dylib                   0x0000000112a1f9dc _dispatch_root_queue_drain + 506
	17  libdispatch.dylib                   0x0000000112a1f782 _dispatch_worker_thread3 + 113
	18  libsystem_pthread.dylib             0x0000000112de4712 _pthread_wqthread + 1299
	19  libsystem_pthread.dylib             0x0000000112de41ed start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by adrianotadao** [comment]
The error come from here: https://github.com/tinycreative/react-native-intercom/blob/master/lib/IntercomClient.js#L20-L31

**Comment by kanerogers** [comment]
Hey, @adrianotadao! That's definitely a weird error.

Long shot, but is the module linked correctly? If it's not then `NativeModules.IntercomEventEmitter` will return undefined, and trigger the error you're seeing.

**Comment by adrianotadao** [comment]
Hello @kanerogers it's really a strange error. I don't know what is happening when I try to run as release. I'm having a weird problem with my app. I added a shared extension to my app and when I send it to a test fairy for example, the app doesn't open :(

**Comment by tatva-nisarg** [comment]
Any update on this?

**Comment by adrianotadao** [comment]
@tatva-nisarg the problem here was in another thing, it was my mistake. React native has this weird behavior... sometimes it shows an error but the cause of it are other things... Can I close this issue or are you having the same problem?

**Comment by tatva-nisarg** [comment]
@adrianotadao Yes I am having same problem
I got this issue while run app

**Comment by tatva-nisarg** [comment]
![simulator screen shot may 18 2017 5 08 30 pm](https://cloud.githubusercontent.com/assets/25173398/26200644/b9b38fba-3bec-11e7-82f9-81019fb53eca.png)

**Comment by tatva-nisarg** [comment]
Sorry this was my bad 

I forgot to link lRNIntercom.a  file in link module that will solved my issues

**Comment by adrianotadao** [comment]
@tatva-nisarg no problem. So, is there no error? Can I close this issue?

**Comment by tatva-nisarg** [comment]
Yes please close.

**Comment by grifotv** [comment]
is this issue related to https://github.com/tinycreative/react-native-intercom/issues/109 ?

**Comment by tatva-nisarg** [comment]
@grifotv  Yes, I think so both are same

**Comment by PrimeLens** [comment]
I've followed the instructions exactly and I'm stuck at this point as well.   I've searched the folder structure and there is no file named "lRNIntercom.a".   
Please help. Am stuck.  What library or file do you mean and  how do you link it in Android studio?

edit:
I solved my problem by editing App > build.gradle and changing 
`buildToolsVersion "23.0.2"` to `buildToolsVersion "25.0.2"`

**Comment by kanerogers** [comment]
Hi, PrimeLens,

Thanks for writing in! Sorry you're having issues, hopefully this is an
easy fix.

What is recommend you do is run the command `react native link
react-native-intercom` at the command line in the directory of your react
native project. This will do all the necessary steps for you automatically,
except for putting in things like your App ID and API key.

Hope that helps,
Kane

PS. I'm not sure if you're new to GitHub, but for future reference, you
have replied to an issue relating to another topic. If you're still
experiencing difficulties, please feel free to email me directly at
kane.m.rogers@gmail.com. 😊

**Comment by luskin** [comment]
I am receiving this error as well. I followed the instructions precisely and several times removed the package entirely and reinstalled, relinked... etc, however still getting this error. Currently all I am trying to do is present the messenger. The error occurs however in the import: _import Intercom from 'react-native-intercom'_

Screenshots:

**iOS 10.3 iPhone 6 Simulator**
![simulator screen shot jul 20 2017 10 48 00 am](https://user-images.githubusercontent.com/5702322/28431340-e8c59e24-6d38-11e7-8f9b-b127fd76cc4e.png)

<img width="701" alt="screen shot 2017-07-20 at 10 48 18 am" src="https://user-images.githubusercontent.com/5702322/28431356-f64e1c9c-6d38-11e7-9fa1-fc31ce4e780e.png">

**Comment by PrimeLens** [comment]
@luskin   you should specify if the crash is android or ios, you should include screenshots of your error logs, you should post anything you can that will help others help you. What you posted is pretty vague

**Comment by luskin** [comment]
@PrimeLens Thanks, my bad. Post updated.

**Comment by bsjaffer** [comment]
@luskin you are able to get this issue fixed. i am getting same error in IOS , but in android its working good.

**Comment by alexlevy0** [comment]
Same issue on iOS :
```
2018-04-06 15:57:59.958 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'IntercomEventEmitter.UNREAD_CHANGE_NOTIFICATION')
2018-04-06 15:57:59.960 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'IntercomEventEmitter.UNREAD_CHANGE_NOTIFICATION')

```

**Comment by luskin** [comment]
nearly a year later and issue still exists, trying to add intercom again to a new project and running into the exact same issue as I posted before. Anybody seen any luck with this?

**Comment by idan6189** [comment]
anyone found a solution?

**Comment by alexlevy0** [comment]
@idan6189 Linking native library manually and not using CocoaPods resolves this issue

**Comment by FlawaCLV** [comment]
@alexlevy0 I still have the issue. Does it work with Expo?

**Comment by alexlevy0** [comment]
> @alexlevy0 I still have the issue. Does it work with Expo?

@FlawaCLV I don't know I never tried but I would be surprised if it works
