### ISSUE TITLE
'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by the-mold** [tinycreative/react-native-intercom#65]
guys, 

first of all, thank you for the awesome job!

I have a small problem though: I am developing an IOS app and I struggle with this for hours now.
When I build project in xCode I get the following:
![image](https://cloud.githubusercontent.com/assets/15109844/22463853/484db71a-e7b4-11e6-8c39-262859109492.png)

Any idea why does it happen? Thank you!

**Comment by the-mold** [comment]
sorry guys, 

has nothing to do with the package. The xcode was misconfigured. 

I am closing the issue

**Comment by mmckinley8** [comment]
How did you resolve this @petromoldovan? I am facing the same issue

**Comment by browniefed** [comment]
This may have been due to some recent changes in removing some of the header paths from the library. I will get a potential fix out for this later.

**Comment by mmckinley8** [comment]
thanks @browniefed. Do you know of a timeline, or even better, can you provide the potential fix?

**Comment by browniefed** [comment]
v5.3 has been published with the paths added back and compatibility with react-native .40 and before. 
The previous version would only support .40

**Comment by browniefed** [comment]
@mmckinley8

**Comment by mmckinley8** [comment]
@browniefed terrific! I'll let you know if I have issues...I figured it was something related to 0.40.0 because of the new import syntax for iOS - reason I have not upgraded yet

**Comment by mmckinley8** [comment]
![screen shot 2017-01-31 at 4 54 52 pm](https://cloud.githubusercontent.com/assets/11301364/22488136/0cbddcbc-e7d6-11e6-8b18-c15d98b7167d.png)

same result after update @browniefed

**Comment by browniefed** [comment]
Sorry, I'm not sure then. Maybe @petromoldovan can clarify.

I'm guessing it's a header search path issue.

**Comment by browniefed** [comment]
I may also recommend install older versions. If you can find where the error occurs I can narrow it down.

**Comment by the-mold** [comment]
@browniefed @mmckinley8 I am on RN 0.40.0.

the way I "solved" it was to start over. When installing the package I followed so many advices from different sources that I misconfigured something in the xcode. It would not build. So I pulled a project again and gave it fresh start in xcode.

I made it work like this: 

**1.** npm install react-native-intercom --save
**2.** react-native link
**3.** Setup manually libs
https://github.com/intercom/intercom-ios
Add run Script like this:
http://runscriptbuildphase.com/

**4.** Add config
**IOS**
Add in AppDelegate.m
```
#import "Intercom/intercom.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [Intercom setApiKey:@"YOUR_KEY" forAppId:@"YOU_APP_ID"];
}
```

**5.** Render 
```
var Intercom = require('react-native-intercom');
Intercom.registerIdentifiedUser({ userId: 'bob' });
Intercom.displayMessageComposer();
```

hope this helps!

**Comment by mmckinley8** [comment]
@petromoldovan your run script link takes me to fabric, can you provide the contents of your script?

**Comment by mmckinley8** [comment]
I created a fresh react-native project using 0.40.0, and still received errors when compiling iOS. I have already successfully integrated android. I am receiving the same error referenced in https://github.com/tinycreative/react-native-intercom/issues/58 but for iOS. I also attempted @petromoldovan steps, but no luck :(. @browniefed I have seen the updates and appreciate the effort. I will reattempt once RN 0.41.0 is released.

**Comment by browniefed** [comment]
@mmckinley8 can you step backwards in version and find out if there is a version that works for you?

**Comment by mmckinley8** [comment]
@browniefed I went all the way back to 4.1, this resulted in errors also. I believe it was a React dependency issue for 4.1. I also tried 4.2, 4.4, and 5.1.

**Comment by browniefed** [comment]
I'll do my best to get something work and if I do I can record a screencast and let you know. Sorry, I'm just not sure what your issues are

**Comment by mmckinley8** [comment]
No worries at all. Appreciate the responsiveness and effort.

**Comment by browniefed** [comment]
Seeing similar issues here https://github.com/airbnb/lottie-react-native/pull/20

**Comment by lelandrichardson** [comment]
I think the fix is to import headers like:

```
// import RCTEventEmitter.h
#if __has_include("RCTEventEmitter.h")
#import "RCTEventEmitter.h"
#elif __has_include(<React/RCTEventEmitter.h>)
#import <React/RCTEventEmitter.h>
#else
#import "React/RCTEventEmitter.h"
#endif
```

Otherwise, i'm not sure it's possible to remain backwards compatible with older version of React, and also support CocoaPods :/

**Comment by browniefed** [comment]
Ahhhhh I see, it's a potential cocoapods issue. 

Thanks @lelandrichardson (totally forgot when linking to other topics it shows up on that thread haha)

**Comment by parkerproject** [comment]
@lelandrichardson I have tried your solution but still doesn't work. I'm on RN@0.42
I'still getting the RCTEventEmitter not found error

**Comment by parkerproject** [comment]
I also tried 
`#if __has_include(<React/RCTAssert.h>)
#import <React/RCTEventEmitter.h>
#else // back compatibility for RN version < 0.40
#import "RCTEventEmitter.h"
#endif`

**Comment by lelandrichardson** [comment]
looking at my original comment, I think the ordering i typically use now is:

```
#if __has_include(<React/RCTBridgeModule.h>)
#import <React/RCTBridgeModule.h>
#elif __has_include("RCTBridgeModule.h")
#import "RCTBridgeModule.h"
#else
#import "React/RCTBridgeModule.h"
#endif
```

I'm not sure if that will make any difference for you or not...

**Comment by browniefed** [comment]
He got it fixed, was an issue with xcode on a separate issue. I'll fix the
code to be that. Thanks Leland

**Comment by dinodsaurus** [comment]
I have run into the same  issue as @mmckinley8  today, are there any news how to fix it?
Im using `Intercom@3.2.1` and `react-native-intercom@6.0.0`

Basically it says that `RCTBridgeModue.h` is not found and also that `RCTEventEmitter.h` is missing.

**Comment by afilp** [comment]
I have similar problems.

"react-native": "0.44.2 ",
"react-native-intercom": "5.7.0",  // use old one due to the *other* problem with Android SDK APIs version

Any ideas what we should do? 

At first, I had manual installation and the "strip-frameworks" script failed (non-existed)
Then I added these in the podfile and updated:
    pod 'Intercom'
    pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'

So, now, after the pod logic, I have the 'React/RCTEventEmitter.h' file not found issue.

**Comment by leimonio** [comment]
This issue is still happening:
"react-native": "0.45.1"
"react-native-intercom": "6.2.0"

Installation guide is not correct!

**Comment by the-mold** [comment]
@kwnccc try starting a new RN project and follow my instruction. I checked it few times already. It must be working.

**Comment by eduardoleal** [comment]
Happening here too

react-native@0.44.0
react-native-intercom@6.2.0

It's working (without notifications) on Android but not on iOS.

**Comment by eduardoleal** [comment]
Anyone who have succeeded installing on React Native >= 44?

**Comment by BenjaminG** [comment]
Unable to build with react-native@0.46.4 and react-native-intercom@6.3.0...

**Comment by syzer** [comment]
👍

**Comment by cauboy** [comment]
👍

**Comment by eduardoleal** [comment]
I solved my problem by adding the following entries to Intercom Build Target >  **header search paths**:
```
../../../ios/Pods/Headers/Public
../../../ios/Pods/Headers/Public/React (recursive)
```

<img width="1914" alt="screen shot 2017-08-04 at 10 46 09" src="https://user-images.githubusercontent.com/2083506/28971403-2d554740-7902-11e7-81ad-9b7c56855e2e.png">

**Comment by afilp** [comment]
I am having the same issue, how can this be solved?

**Comment by lupena** [comment]
Same issue here. I Tried @eduardoleal solution but didn't work. :( 
    "react": "^16.0.0",
    "react-native": "0.51.0",
    "react-native-intercom": "^9.0.0",

**Comment by jamesjara** [comment]
Same

**Comment by maartenvandillen** [comment]
I got it working, it looks like it was unable to find all needed React headers from the include dir

**Comment by StefanoCremona** [comment]
@maartenvandillen what did you add to you header search path to get it work?
Thank you

**Comment by maartenvandillen** [comment]
@StefanoCremona I can't remember. I have since then changed the way Intercom is integrated into the project. I am now using

`pod 'Intercom', '> 3'`

successfully instead

**Comment by rashidul-hasan** [comment]
Anyone tried it with RN 0.61.5 & react-native-intercom 16.0.0? I'm stuck with this same error for 3 days.
