### ISSUE TITLE
Latest build fails on android sim 

### ISSUE THREAD

**Issue by j-mendez** [tinycreative/react-native-intercom#68]
Here's a screenshot below of the issue.

**Comment by j-mendez** [comment]
<img width="655" alt="screen shot 2017-02-05 at 12 18 30 pm" src="https://cloud.githubusercontent.com/assets/8095978/22628168/463e2ca6-eb9d-11e6-9ed7-a49690181906.png">

**Comment by javiercr** [comment]
@jeffreymendez1993 could you share some of your code? I'm using react-native-intercom on Android without problems (using a real device, not the emulator).
