### ISSUE TITLE
displayMessageComposerWithInitialMessage() is now deprecated by Intercom

### ISSUE THREAD

**Issue by chuckhacker** [tinycreative/react-native-intercom#69]
We see a blank screen when we call both displayMessageComposer() and displayMessageComposerWithInitialMessage() as such (see included screenshot here):

http://imgur.com/a/Qmgvv

In the latter case, Intercom support mentioned that "the method you are after was deprecated and currently there is now way to open the messenger on mobile with a predefined message."

**Comment by jtreanor** [comment]
Hi @TheChuckster,

I'm one of the engineers that works on Intercom's mobile Messengers. Sorry for the mix up but this method is actually not deprecated. I have let the support team know.

The screenshot looks like you don't have inbound messaging on your Intercom account.

**Comment by chuckhacker** [comment]
I see, now I see many other people having this problem (just needed the right Google search query).

As feedback, perhaps logging a warning to the console would help avoid future confusion and support headaches.
