### ISSUE TITLE
Intercom/Intercom.h file not found

### ISSUE THREAD

**Issue by MattyK14** [tinycreative/react-native-intercom#70]
I've tried linking it through the terminal, and manually several times and cannot get it functioning. 
I add RNIntercom to the libraries folder and link libRNIntercom.a under Link Binary With Libraries.

Running RN 0.40.0.

![screen shot 2017-02-08 at 2 10 10 pm](https://cloud.githubusercontent.com/assets/16196171/22749660/b1feb3c6-ee08-11e6-9c30-19c7f9ffb24d.png)

**Comment by browniefed** [comment]
You need to add the Intercom library, this library doesn't come with it.

**Comment by MattyK14** [comment]
https://github.com/tinycreative/react-native-intercom/issues/26#issuecomment-247409017
