### ISSUE TITLE
iOS missing X and Back button and response overlay is transparent

### ISSUE THREAD

**Issue by mmckinley8** [tinycreative/react-native-intercom#71]
![img_0023](https://cloud.githubusercontent.com/assets/11301364/22846848/529dbf96-efaf-11e6-99d7-28782c23424c.png)
![img_0024 png copy](https://cloud.githubusercontent.com/assets/11301364/22846849/529eaf6e-efaf-11e6-8b2d-37b935b0fd2c.png)

As you can see, the X button and back button are missing in the chat interface. Also the response is transparent as shown in the bottom of the list UI. I am running version 5.5.0. Please let me know if this is something I can fix.

**Comment by browniefed** [comment]
I have no clue. Maybe ask the intercom people?

**Comment by feliperun** [comment]
We have similar issues here. 

![img_7296](https://cloud.githubusercontent.com/assets/6460296/23079911/03a68e68-f536-11e6-804a-22d19d4655ea.PNG)
![img_7295 2](https://cloud.githubusercontent.com/assets/6460296/23079912/03b03b34-f536-11e6-9b87-e9217b580dcb.PNG)

**Comment by feliperun** [comment]
Talking with intercom support, they suggested to upgrade the Intercom iOS SDK version. Witch version of the SDK this Reactive Native Wrapper use? Can we use the latest version?

**Comment by browniefed** [comment]
@feliperbroering we do not ship with a version Intercom, you can upgrade to any version of Intercom you desire.

**Comment by Dimasik911** [comment]
Having the same issue... @feliperbroering, Did you find any workaround for that... Updating sdk to 4.1.9 did not work for me.
