### ISSUE TITLE
Segment.io vs logEvent

### ISSUE THREAD

**Issue by GeoffreyPlitt** [tinycreative/react-native-intercom#74]
Hello,

We've been sending event data to Intercom via the https://segment.com/ pipeline so far. We've noticed that there's quite a delay (10-30s) using this method, so we're looking for something faster, so that our "open messenger if X event happens" stuff happens immediately.

So then I saw that this library provides for the following type of API call:
```Intercom.logEvent('viewed_screen', { extra: 'metadata' });```

Questions:
1) Would this make our automatic events like above happen faster?
2) Would this cause duplication if all actions also being sent on segment.com?

**Comment by browniefed** [comment]
This would be something to ask the Intercom folks.

**Comment by GeoffreyPlitt** [comment]
Thanks!
