### ISSUE TITLE
"no known class method for selector 'presentMessageComposerWithInitialMessage:'"

### ISSUE THREAD

**Issue by adamgrossman** [tinycreative/react-native-intercom#77]
Hello.

I just received this error while trying to deploy my app. 
```
/node_modules/react-native-intercom/iOS/IntercomWrapper.m:127:19: no known class method for selector 'presentMessageComposerWithInitialMessage:'

[Intercom presentMessageComposerWithInitialMessage:message];
```

Do you have any idea what may be going on here? Thanks!

**Comment by browniefed** [comment]
Nope, I'm not sure sorry. Did you upgrade your intercom version per chance?

**Comment by adamgrossman** [comment]
In this mobile app, we're only using react-native intercom: `"react-native-intercom": "5.7.0",`. 

We just upgraded this yesterday after fixing this problem: https://github.com/tinycreative/react-native-intercom/issues/76. It was working before upgrading to this version.

**Comment by adamgrossman** [comment]
In my build.gradle file I have `compile 'io.intercom.android:intercom-sdk:3.+'` Should this be `compile 'io.intercom.android:intercom-sdk-base:3.0.+'`?

**Comment by browniefed** [comment]
@adamgrossman yes it should be `3.0.+`. However for the iOS version I was referring to your `Intercom` package itself, not the react-native-intercom version.

**Comment by adamgrossman** [comment]
I've updated to `3.0.+` and my version of Intercom is: `Intercom for iOS - Version 3.0.12`

**Comment by adamgrossman** [comment]
Looking at their changelog it seems they added: `[Intercom presentMessageComposerWithInitialMessage:]` in version 3.0.13. 

It should be resolved once I upgrade. Thanks for your prompt responses!
