### ISSUE TITLE
RCTBridgeModule.h' file not found (RN@0.42.3)

### ISSUE THREAD

**Issue by parkerproject** [tinycreative/react-native-intercom#78]
I have tried everything suggested on [issue 72](https://github.com/tinycreative/react-native-intercom/issues/72) but still, doesn't work

**Comment by browniefed** [comment]
Are you sure you're using the latest `react-native-intercom` v5.7?

**Comment by parkerproject** [comment]
Yep am on v5.7, really strange. my Podfile includes this two lines
  `pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'`
  `pod 'Intercom'`

**Comment by parkerproject** [comment]
ignore me, I guess my XCode was messed up.

**Comment by dinodsaurus** [comment]
How did you fix this @parkerproject ?

**Comment by parkerproject** [comment]
@dinodsaurus 
1.  Remove intercom and clean up your build
2. Re-install "react-native-intercom"
3. link "react-native-intercom" rather than adding in Podfile
4. Setup intercom for IOS [https://github.com/intercom/intercom-ios](https://github.com/intercom/intercom-ios)
5. Finally, build RNIntercom scheme before running
