### ISSUE TITLE
Temporary support

### ISSUE THREAD

**Issue by grabbou** [tinycreative/react-native-intercom#8]
Hey,

Thanks for the awesome module and your help so far! Looks like there are few PRs awaiting merging - is anyone having a more up to date fork? I'd be interested in maintaining it

Cheers

**Comment by browniefed** [comment]
Sorry about that If you submit a PR I'll get to it!

**Comment by grabbou** [comment]
I have some bits made internally, can send it over when i am back from Amsterdam

**Comment by browniefed** [comment]
Awesome thanks!
