### ISSUE TITLE
Trigger Notifications

### ISSUE THREAD

**Issue by MattyK14** [tinycreative/react-native-intercom#80]
I was wondering if the `addEventListener` for `Intercom.Notifications.UNREAD_COUNT` is supposed to trigger when the app is not in the foreground for local notification purposes? Otherwise how would I go about notifying the user they have a new message when the app is not in the foreground?

Because right now it's not.

**Comment by browniefed** [comment]
This will likely require some native code to work. I would look into React Native and background processing.

**Comment by LucasBassetti** [comment]
Hey @MattyK14,

Did you solve this problem?
