### ISSUE TITLE
5.8.0: EXC_BAD_ACCESS crash when Reloading in Dev mode

### ISSUE THREAD

**Issue by seanadkinson** [tinycreative/react-native-intercom#84]
The latest changes in 5.8.0 are causing an EXC_BAD_ACCESS when Reloading in dev mode (Cmnd+R) if there is a mounted component that is currently listening for UNREAD_COUNT changes.

If I unmount the component before reloading, no crash.  If I downgrade to 5.7, no crash.

Let me know if you need more info.

**Comment by seanadkinson** [comment]
@kuglemic Thoughts on this?  What timing issue was solved in 5.8?  Thanks for any input.

**Comment by kuglemic** [comment]
Hi everyone, I will try to reproduce the issue and will have a look at it.

**Comment by kuglemic** [comment]
Hi, 
I can confirm the Bug and I'm really sorry, that I introduced it with my last PR. 

Just to recap what the problem was:

> Just on release builds, we encountered the issue, that the body of the IntercomUnreadConversationCountDidChangeNotification event was invalid.
> 
> We investigated the issue by creating an App with a bundled main.jsbundle, running on a real device, just debugging the objc code in IntercomEventEmitter.m.
> 
> We realised that whenever `[Intercom unreadConversationCount]` was accessed directly after `- (void)handleUpdateUnreadCount:(NSNotification *)notification {` was called, we didn't get a valid value.
> 
> If we set a breakpoint or a NSLog before, we got the correct value.
> 
> Our current solution is to wait for 0.1 seconds until [Intercom unreadConversationCount] is called.

That was the real issue and the solution to my problem!

What I have done next caused your bug and was actually not necessary:

> Furthermore we are dispatching [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleUpdateUnreadCount:) name:IntercomUnreadConversationCountDidChangeNotification object:nil]; and [[NSNotificationCenter defaultCenter] removeObserver:self]; to the main queue - just to be sure. Propably this is not necessary.

Sorry for that! I Shouldn't have done that.

I will create a PR solving your reloading (Cmd+R) issue and improving my bugfixing by changing the code to:
```
- (void)handleUpdateUnreadCount:(NSNotification *)notification {
    __weak IntercomEventEmitter *weakSelf = self;
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        IntercomEventEmitter *strongSelf = weakSelf;
        NSUInteger unreadCount = [Intercom unreadConversationCount];
        NSNumber *unreadCountNumber = [NSNumber numberWithUnsignedInteger: unreadCount];
        NSDictionary *body = @{@"count": unreadCountNumber};
        [strongSelf sendEventWithName:IntercomUnreadConversationCountDidChangeNotification body:body];
    });
}
```

Added lines:
`    __weak IntercomEventEmitter *weakSelf = self;`
`        IntercomEventEmitter *strongSelf = weakSelf;`

**Comment by kuglemic** [comment]
I created a Pull Request to fix this issue:
https://github.com/tinycreative/react-native-intercom/pull/85

**Comment by browniefed** [comment]
Published as 5.8.1

**Comment by seanadkinson** [comment]
Thanks for the quick turnaround on this @kuglemic, I appreciate it.

**Comment by seanadkinson** [comment]
And @browniefed  for that matter 👍
