### ISSUE TITLE
Generating apk

### ISSUE THREAD

**Issue by the-mold** [tinycreative/react-native-intercom#87]
Dear Team,

this must be something really simple but i just cannot find solution to this.

I am trying to generate apk file with `./gradlew assembleRelease` and I am getting this:
![image](https://cloud.githubusercontent.com/assets/15109844/25381793/681f859e-29b5-11e7-833b-1befe4d050b4.png)

Any idea what is going on? Please let me know.

Many thanks!

**Comment by tlenclos** [comment]
Hi !
The latest version of this package needs build tools 25. See the discussion here https://github.com/tinycreative/react-native-intercom/pull/92.
