### ISSUE TITLE
Notifications appear duplicated

### ISSUE THREAD

**Issue by jsdario** [tinycreative/react-native-intercom#88]
Hi!

Since I integrated Intercom Android native push notifications correctly, I am always seeing notifications displayer twice. I am also using `react-native-push-notification` to handle pushes from the server anddisplay some local notifications. For those cases it works just fine.

Any ideas?

**Comment by Xaeonn** [comment]
For anyone else still stumbling across this; the build.gradle for react-native-intercom imports GCM with this line `compile 'io.intercom.android:intercom-sdk-gcm:3.1.+'` and both `react-native-push-notification` and `react-native-fcm` (which I'm using) import their own version of GCM/FCM so the app ends up with each notification being picked up twice. Push #97 fixes the issue, so if you're having this issue still make sure you update to the latest version of `react-native-intercom`.
