### ISSUE TITLE
cannot find symbol "Intercom.client().setUserHash(userHash);"

### ISSUE THREAD

**Issue by ccstorch** [tinycreative/react-native-intercom#91]
I follow the steps to integrate my react native app with Intercom, but everytime I run react-native run-android I got this error:

```
:react-native-intercom:compileReleaseJavaWithJavac
Full recompilation is required because 'IntercomModule.java' was changed. Analysis took 0.058 secs.
/Users/username/pathtoapp/AppName/node_modules/react-native-intercom/android/src/main/java/com/robinpowered/react/Intercom/IntercomModule.java:137: error: cannot find symbol
        Intercom.client().setUserHash(userHash);
                         ^
  symbol:   method setUserHash(String)
  location: class Intercom
Note: /Users/username/pathtoapp/AppName/node_modules/react-native-intercom/android/src/main/java/com/robinpowered/react/Intercom/IntercomModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-intercom:compileReleaseJavaWithJavac FAILED
```

I'm using the version 6.0.0 of this library and react native 0.44.0.

**Comment by ccstorch** [comment]
I've change the react-native-intercom version to 5.9.0 and the error is gone. 
I don't know what it was but it is related to the new version 6.0.0.

**Comment by skleest** [comment]
worked for me, thanks!

**Comment by tlenclos** [comment]
Same here with version 6.1.0. Can you reopen this issue ?

**Comment by tlenclos** [comment]
Hello @browniefed !

I believe it's broken since this commit forcing the 3.0
https://github.com/tinycreative/react-native-intercom/commit/6a1dbed91675f559c992bb15ea350dadb4e2db95#diff-7ae5a9093507568eabbf35c3b0665732R37

The setUserHash method is available since version 3.2.0 (https://github.com/intercom/intercom-android/blob/bd175e0430ced432eb812be3ddab215726b53fec/CHANGELOG.md#version-320).

**Comment by chitezh** [comment]
I fixed mine by excluding the forced `3.1.+`

   ```
compile (project(':react-native-intercom')) {
        exclude group: 'io.intercom.android', module: 'intercom-sdk-gcm'
    }
```

**Comment by nabilfreeman** [comment]
I also had this issue, and I fixed it by making sure my CocoaPods version of Intercom was greater than 3.2.0. I had 3.1 installed.

**Comment by Mythrim** [comment]
I am new to Intercom. Can You suggest some reference to integrate intercom with React-native. Basically like how to install intercom with react-native.
