### ISSUE TITLE
Messenger not showing in the app

### ISSUE THREAD

**Issue by skleest** [tinycreative/react-native-intercom#93]
Messenger button is not showing in the app. It shows briefly if the agent answers, but as soon as you click on the messenger button and go into the chat, the messenger button is gone. 

The settings for messenger visibility are on. Is this the intended behavior on mobile? Thank you.

**Comment by tatva-nisarg** [comment]
Have you got any solution?

**Comment by tatva-nisarg** [comment]
Hello @skleest 

Please check your key it may be wrong

Android it has prefix like `android_sdk-`
iOS it has prefix like `ios_sdk-`

Please check it and let know your feedback.

**Comment by skleest** [comment]
Hi @tatva-nisarg sorry for the late response! We couldn't get it to work. iOS has the right prefix.
The intended behavior of intercom mobile is having the messenger button shown throughout the app, is that correct?

**Comment by tatva-nisarg** [comment]
try this function displayMessageComposer();

**Comment by JulianKingman** [comment]
The function you want is  `Intercom.setLauncherVisibility('VISIBLE');`

**Comment by sanjosedennisns7593** [comment]
Have tried both displayMessageComposer and setLauncherVisibility, still not showing anything.

**Comment by JulianKingman** [comment]
Do other intercom functions work, and can you post code?

**Comment by econner** [comment]
For me this wasn't working because I had not yet called `registerIdentifiedUser`. The launcher shows if I have:
```
componentDidMount() {
        Intercom.registerIdentifiedUser({ userId: DeviceInfo.getDeviceId() });
        Intercom.setLauncherVisibility('VISIBLE')
}
```
