### ISSUE TITLE
io.intercom.android.sdk.exceptions.IntercomIntegrationException: Both Intercom FCM and GCM modules were included. Please include only one of these dependencies in your project. 

### ISSUE THREAD

**Issue by Kottidev** [tinycreative/react-native-intercom#95]
![image](https://cloud.githubusercontent.com/assets/12915009/25942865/e0f5e440-3635-11e7-9fe9-cef7413716bd.png)

app crash and dosen't open 

my config is

`
  compile project(':react-native-fcm')
  compile project(':react-native-intercom')
    compile 'io.intercom.android:intercom-sdk-base:3.+'
    compile('io.intercom.android:intercom-sdk-fcm:3.+') {
        exclude group: 'io.intercom.android', module: 'intercom-sdk-base'
   }
`

**Comment by prachil007** [comment]
After pulling library using 
`npm install react-native-intercom`
go to `node_modules/react-native-intercom/android/build.gradle`

and at bottom find `dependencies`

make sure you have only one of following - 
1. For GCM
`compile 'io.intercom.android:intercom-sdk:3.+'`
2. For FCM
`compile 'io.intercom.android:intercom-sdk-base:3.+'`
`compile 'io.intercom.android:intercom-sdk-fcm:3.+'`

keep rest same.
Also try removing
`compile 'io.intercom.android:intercom-sdk-base:3.+' `
`compile('io.intercom.android:intercom-sdk-fcm:3.+') `
`{ exclude group: 'io.intercom.android', module: 'intercom-sdk-base' }`
let us know the results

PS : This is working for me.
